### ISSUE TITLE
Exchange two letters in sway (Wayland) on bone

### ISSUE THREAD

**Issue by mielouk** [xkbcommon/libxkbcommon#102]
As a swayWM user I've [learned](https://github.com/swaywm/sway/issues/4250) that I need to make a partial new layout if I want to exchange two letters.

This is my attempt to [make](https://8n1.org/15697/4279) a  $HOME/.xkb/symbols/de-bone-j-q, 

which would be evoked by this:

input * xkb_layout "de"
input * xkb_variant "bone"
input "DasKeyboard" xkb_model "pc105"
input type:keyboard xkb_layout "de-bone-j-q" 

in my sway config.

This results in a change to QWERTY, which wasn't the intention. 

I know this isn't a bug, but rather a support question. Though I don't know where to put it otherwise. If someone could point me to a place where I may ask this question.

**Comment by progandy** [comment]
Not a xkbcommon bug or issue.

It is probably a misconfiguration of sway. It collects all input settings and tries to apply a configuration with ```layout=de-bone-j-q, variant=bone```. This doesn't exists and therefore fails and keeps the previous keymap or a nomral us keymap if there was none.

Set the variant back to empty or ```basic``` before changing to your new layout.

**Comment by mielouk** [comment]
Thank you very, very much!
