### ISSUE TITLE
Wrong codepoint for almost equal to

### ISSUE THREAD

**Issue by svenssonaxel** [xkbcommon/libxkbcommon#110]
In `xkbcommon/xkbcommon-keysyms.h`, the line:
```
#define XKB_KEY_approxeq                   0x1002248  /* U+2245 ALMOST EQUAL TO */
```

should probably be changed to
```
#define XKB_KEY_approxeq                   0x1002248  /* U+2248 ALMOST EQUAL TO */
```

**Comment by bluetech** [comment]
The file is autogenerated. Here is the source: https://gitlab.freedesktop.org/xorg/proto/xorgproto/blob/e0d4e02710e6d66408ecbbd2fee64ae4c6748739/include/X11/keysymdef.h#L2136

Once it is fixed there, we can regenerate the file here.

**Comment by fooishbar** [comment]
Dupe of #82.

**Comment by svenssonaxel** [comment]
Fixed in source by deprecating `XK_approxeq` and `XK_notapproxeq`.
