### ISSUE TITLE
xkbcommon: ERROR: Key "<CAPS>"

### ISSUE THREAD

**Issue by HadrianDiaz** [xkbcommon/libxkbcommon#111]
xkbcommon: ERROR: Key "<CAPS>" added to modifier map for multiple modifiers; Using Mod3, ignoring Lock
Failed to open /proc/modules: No such file or directory
[CDROM] No sg devices found, could not check if sg kernel module is loaded.

Im trying to run an app downloaded from flatpak but that error doesn't let me. Any clue?

**Comment by bluetech** [comment]
> xkbcommon: ERROR: Key "" added to modifier map for multiple modifiers; Using Mod3, ignoring Lock

This error is not fatal, i.e. it doesn't prevent your program from starting up.

>  Failed to open /proc/modules: No such file or directory
> [CDROM] No sg devices found, could not check if sg kernel module is loaded.

These errors are not from libxkbcommon. You should report it to flatpak.
