### ISSUE TITLE
Invalid names for levels above Level8 in xkb_keymap_get_as_string

### ISSUE THREAD

**Issue by progandy** [xkbcommon/libxkbcommon#113]
```xkb_keymap_get_as_string``` translates levels greater than Level8 to a name starting with "Level". This is incorrect, since those are only defined for Level1 through Level8. All others have to be specified as integers.

[keymap-dump.c#L222](https://github.com/xkbcommon/libxkbcommon/blob/110d17c6bee504569f68a105b2d4d06fe5e7e0b0/src/xkbcomp/keymap-dump.c#L222)
[keymap-dump.c#L233](https://github.com/xkbcommon/libxkbcommon/blob/110d17c6bee504569f68a105b2d4d06fe5e7e0b0/src/xkbcomp/keymap-dump.c#L233)

Original report: swaywm/sway#4637

**Comment by bluetech** [comment]
Thanks! I'll do a release with this fix this weekend.
