### ISSUE TITLE
xkbcommon: ERROR: Key "<CAPS>" :  Replication?

### ISSUE THREAD

**Issue by jackmolyneaux** [xkbcommon/libxkbcommon#128]
I am repeatedly receiving the following a non-fatal error message:
    xkbcommon: ERROR: Key "<CAPS>" added to modifier map for multiple modifiers; #
        Using Mod3, ignoring Lock
It appears to obstruct CAPS LOCK capability in gedit.  No other known effects.
Is this a replication of #111 xkbcommon: ERROR: Key "<CAPS>"?

Context:
    Running Ubuntu 18.04 under Crostini on a Pixelbook

**Comment by bluetech** [comment]
Thanks for the report. I figure it's just better to hide this message by default. I've added a commit which does this, will be included in the next xkbcommon release (0.10.0).

**Comment by cefn** [comment]
Thanks for your attention on this. 

It's great to think the error will go away, but is there a shorter-term workaround beyond upgrading core packages. This error is spamming my diff invocations with Meld on Crostini. I suspect this package is versioned in the container implementation too, rather than in any Debian packages installed within the Crostini container so I may be unable to upgrade anyway...

```
cefn@penguin:~/Documents/github/lauf-mono$ git difftool -t meld -y -R main
xkbcommon: ERROR: Key "<CAPS>" added to modifier map for multiple modifiers; Using Mod3, ignoring Lock
xkbcommon: ERROR: Key "<CAPS>" added to modifier map for multiple modifiers; Using Mod3, ignoring Lock
xkbcommon: ERROR: Key "<CAPS>" added to modifier map for multiple modifiers; Using Mod3, ignoring Lock
xkbcommon: ERROR: Key "<CAPS>" added to modifier map for multiple modifiers; Using Mod3, ignoring Lock
xkbcommon: ERROR: Key "<CAPS>" added to modifier map for multiple modifiers; Using Mod3, ignoring Lock
xkbcommon: ERROR: Key "<CAPS>" added to modifier map for multiple modifiers; Using Mod3, ignoring Lock
xkbcommon: ERROR: Key "<CAPS>" added to modifier map for multiple modifiers; Using Mod3, ignoring Lock
xkbcommon: ERROR: Key "<CAPS>" added to modifier map for multiple modifiers; Using Mod3, ignoring Lock
xkbcommon: ERROR: Key "<CAPS>" added to modifier map for multiple modifiers; Using Mod3, ignoring Lock
xkbcommon: ERROR: Key "<CAPS>" added to modifier map for multiple modifiers; Using Mod3, ignoring Lock
xkbcommon: ERROR: Key "<CAPS>" added to modifier map for multiple modifiers; Using Mod3, ignoring Lock
```

```
cefn@penguin:~/Documents/github/lauf-mono$ sudo dpkg-query --list xkb
dpkg-query: no packages found matching xkb
```

**Comment by tomlanyon** [comment]
@cefn yes, add "export XKB_LOG_LEVEL=critical" to your shell config.
