### ISSUE TITLE
How to read a modifier file in ~/.xkb/symbols under X(FCE)

### ISSUE THREAD

**Issue by mielouk** [xkbcommon/libxkbcommon#144]
Hello, I got a question about a problem that is haunting me for a while now. I use an improved German layout called Bone, in which I modified two [keys](https://github.com/swaywm/sway/issues/4397) with your [help](https://github.com/xkbcommon/libxkbcommon/issues/102).

The [file](https://8n1.org/17148/11e4) in ~/.xkb/symbols is called upon in my swayWM config with

`input * xkb_layout "de-bone-j-q"`
`input "DasKeyboard" xkb_model "pc105"`

which works like a charm on my Wayland based [swayWM](https://github.com/swaywm/sway). 

Now I face the problem of doing the same in X especially in XFCE (Manjaro 20). Me and the people from the IRC channel #neo (neo came before bone) try to figure out how to call upon this file, without success. This should supposedly be done with setxkbmap, but we are not even sure if this is the right way. 

Would one of you be able to shed some light on this?

**Comment by whot** [comment]
drive-by comment: look at `setxkbmap -I ~/.xkb/symbols`. but you'll need to upload the map to the server directly through `setxkbmap -I ... -print | xkbcomp - $DISPLAY` because the server's `xkbcomp` invocation won't look at `~/.xkb`

**Comment by mielouk** [comment]
Thank you for your comment! 
I've played around wit the -I option before, but can't figure out what the right options would be. 

`setxkbmap -I .xkb/symbols de-bone-j-q | xkbcomp - $DISPLAY`

produces

`Error loading new keyboard description`
`syntax error: line 1 of stdin`
`last scanned symbol is:`
`Errors encountered in stdin; not compiled.`

Maybe I'm going with this the wrong way. Is there another (persistent) option to accomplish this. It would also be great to have this in other parts of the X session, like the ligthdm login or the lock screen. Until now I invoke 
`setxkbmap de bone` which works only in the logged in session, but nowhere else.

**Comment by whot** [comment]
you forgot the `-print` argument to `setxkbmap`. without that, it'll try to poke the server directly rather than printing something useful for `xkbcomp` :)

**Comment by mielouk** [comment]
Thx for the hint! Unfortunately it doesn't work either, but it produces a different error:

`setxkbmap -I .xkb/symbols de-bone-j-q -print | xkbcomp - $DISPLAY`

`Warning:   Unsupported high keycode 372 for name <I372> ignored`
                  `X11 cannot support keycodes above 255.`
                 ` This warning only shows for the first high keycode.`
`Error:            Can't find file "de-bone-j-q" for symbols include`
                `  Exiting`
                 ` Abandoning symbols file "(null)"`
`Error:            success in unknown`
                  `Couldn't write keyboard description to :0.0`

If I omit the space between the path and the filename [this](https://8n1.org/17152/245b) is the result, which I'm not able to interpret, unfortunately.

**Comment by mielouk** [comment]
This is the [output](https://8n1.org/17153/a31b) which is piped to xkbcomp

**Comment by mielouk** [comment]
We found a solution that works but still throws errors, which don't seem to have any consequences.

`setxkbmap -I$HOME/.xkb/symbols de-bone-j-q -print | xkbcomp -I$HOME/.xkb - $DISPLAY`
Is there a way to get rid of these [errors](https://8n1.org/17154/42e9)?

**Comment by whot** [comment]
please don't link to external pastebin sites, attach the files here. These warnings are common, it's a result of the various parts being too generic and thus defining things that the next part may not have. Nothing to worry about.

**Comment by mielouk** [comment]
The solution is to copy the file de-bone-j-q with the modified layout to /usr/share/X11/xkb/symbols/ and use

`localectl --no-convert set-x11-keymap de-bone-j-q`

Which not only sets this layout for X in XFCE but also for lightDM. In XFCE the option to honour the system settings has to be activated.

The resulting /etc/X11/xorg.conf.d/00-keyboard.conf is
```
# Written by systemd-localed(8), read by systemd-localed and Xorg. It's
# probably wise not to edit this file manually. Use localectl(1) to
# instruct systemd-localed to update it.
Section "InputClass"
        Identifier "system-keyboard"
        MatchIsKeyboard "on"
        Option "XkbLayout" "de-bone-j-q"
EndSection
```
