### ISSUE TITLE
Add XF86XK_FullScreen symbol

### ISSUE THREAD

**Issue by Niek** [xkbcommon/libxkbcommon#147]
The ``XF86XK_FullScreen`` symbol seems to be missing from ``xkbcommon/xkbcommon-keysyms.h``. See also: https://gitlab.freedesktop.org/xorg/proto/xorgproto/-/merge_requests/11

**Comment by Niek** [comment]
Another reference: https://bugs.archlinux.org/task/65730

**Comment by bluetech** [comment]
Thanks, this will be in the next release.
