### ISSUE TITLE
xkbcommon: ERROR: couldn't find a Compose file for locale "en_NG"

### ISSUE THREAD

**Issue by SavvyProgrammer** [xkbcommon/libxkbcommon#149]
`xkbcommon`: ERROR: couldn't find a Compose file for locale "en_NG"

## Platform
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/sam/go"
GOROOT="/opt/goSDK/go1.14.3"
GOTOOLDIR="/opt/goSDK/go1.14.3/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"

**Comment by SavvyProgrammer** [comment]
changing your current locale to a supported locale resolves the issue. All you have to do is navigate to settings, language settings, change the keyboard mapping to a supported locale and language also

**Comment by bluetech** [comment]
FYI, libxkbcommon uses the following file to find the locale: `/usr/share/X11/locale/compose.dir`. This file is shipped as part of the libX11 package, whose origin is here, specifically this file: https://gitlab.freedesktop.org/xorg/lib/libx11/-/blob/master/nls/compose.dir.pre

So if you want `en_NG` to work, you may submit a merge request to https://gitlab.freedesktop.org/xorg/lib/libx11/ adding a line like

```
en_US.UTF-8/Compose:		en_NG.UTF-8
```

to the file.

**Comment by SavvyProgrammer** [comment]
Thank you @bluetech :+1:
