### ISSUE TITLE
Unnoticed parsing error in xkeyboard-config

### ISSUE THREAD

**Issue by whot** [xkbcommon/libxkbcommon#153]
Haven't fully triaged this yet but: xkeyboard-config 2.30 shipped with a leftover merge conflict marker (`======`) in the `symbols/in` file. This was not detected by the `rmlvo-to-keymap` tool that we run as part of the CI in xkeyboard-config.

Manually verified that it succeeds:
```
$ rmlvo-to-keymap --print --rules evdev --model pc105 --layout in --variant ben_probhat
```
but `xkbcomp` fails:
```
$ setxkbmap -print -layout in -variant ben_probhat | xkbcomp -xkb - -
[...]
syntax error: line 2329 of in
last scanned symbol is: question
Error:            Error interpreting include file "in"
                  Exiting
                  Abandoning symbols file "(null)"
```

This ~~could be a bug in the `rmlvo-to-keymap` tool or a~~ is a bug in the parser where it's too lenient for these cases, not sure.

**Comment by whot** [comment]
Ok, the `rmlvo-to-keymap` tool only calls one function that matters here: `xkb_keymap_new_from_names()`. That one returns a valid keymap so the bug is definitely in the parser.

Whether it's intentionally more lenient or not I can't say. @bluetech, @fooishbar ?

For reference, the syntax error was: https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/commit/c8d68304c826567f27f5a913dd38f6e045b81483

**Comment by bluetech** [comment]
xkbcommon has an optimization where it stops parsing once it reaches the map it needs (map == `xkb_symbols` section in this case). If I'm reading the commit you linked correctly, then only `-layout in -variant modi-kagapa` would cause it to reach the syntax error. Maybe this particular variant isn't triggered by `xkeyboard-config-test.py`?

**Comment by whot** [comment]
oh, good point. Indeed, `modi-kagapa` wasn't used [1] because it's in `evdev.extras.xml` and the test tool doesn't check those. I've filed #156 for this now, thanks!


[1] see pipeline artifacts [here](https://gitlab.freedesktop.org/pmenzel/xkeyboard-config/-/jobs/3010151) but they'll be gone in 20h according to gitlab.
