### ISSUE TITLE
API documentation update needed on website

### ISSUE THREAD

**Issue by whot** [xkbcommon/libxkbcommon#158]
I wanted to link to the user-config guide in the docs today but I noticed the [doc as hosted](https://xkbcommon.org/doc/current/md_doc_quick-guide.html) is still on the old version. I guess this is a manual job atm? Would it make sense to figure out how to make this part of the CI? Maybe even move to github pages to make that process easier.

**Comment by bluetech** [comment]
The docs are hosted by @fooishbar and I update them on each release. Since we're doing a release in the next few days (when I get the chance) it should come up then.

**Comment by bluetech** [comment]
Updated with the new release.
