### ISSUE TITLE
Why is getopt_long() optional?

### ISSUE THREAD

**Issue by whot** [xkbcommon/libxkbcommon#161]
I'm wondering: which systems do we need to support on where `getopt.h` is available but `getopt_long` isn't? Windows doesn't ship `getopt.h` as I found out today so now I'm wondering whether I'm making my life complicated for ourselves by `ifdef`ing this out and handling both `getopt` and `getopt_long` separately.

The first check for `getopt_long` was added in f09ae987bffc2ede00341bc6f0e903ae6810def5 by @aperezdc, I'm wondering if this was supposed to be a generic `<getopt.h>` check rather than the specific one for `getopt_long`. @aperezdc?

**Comment by bluetech** [comment]
Maybe we should parse the arguments ourselves. "Shouldn't be that hard" :) I can do it if you wouldn't mind the conflicts.

**Comment by whot** [comment]
there are a few implementations of `getopt` floating around that should work on windows, might be better to just take one of those. I encountered them while searching for getopt on windows. But still, the question remains - to me it looks like we either have `getopt_long()` anyway or we don't have `getopt.h` at all, so the double ifdef isn't required. And this would also allow us to make the tools consistent with each other.

**Comment by aperezdc** [comment]
@whot IIRC the idea to check for `getopt_long` was that the check would on Windows and also in other “Unixy” systems which may have `getopt` (as is part of the POSIX specification) but not `getopt_long` (which is a GNUism)… case example: most BSDs don't have `getopt_long`, but have a perfectly good `getopt`.

**Comment by whot** [comment]
FreeBSD and OpenBSD both list them, I think that should cover the vast majority of our target systems:
- FreeBSD: https://www.freebsd.org/cgi/man.cgi?getopt_long(3)
- OpenBSD: https://man.openbsd.org/getopt_long

> have a perfectly good getopt.

Maybe this is controversial, but I think `getopt` is perfectly terrible. It encourages you to use `foo -xlfwd` which no-one understands unless you deal with the tool in question every day (e.g. `ls`). For occasional tools that users (or even developers) will never use after they've debugged their issue, long options are a lot more useful.

But back to the topic: glibc has it, the two biggest BSDs have it so IMO there's no need to special-case it for debugging tools.

**Comment by bluetech** [comment]
Let's assume that if `getopt` exists, then so does `getopt_long`. @whot I think you can mark your commit `tools: drop getopt vs getopt_long differentiation ` as fixing this issue.
