### ISSUE TITLE
Unrecognized keysym on left-hand side

### ISSUE THREAD

**Issue by brenoguim** [xkbcommon/libxkbcommon#163]
Hi,

I ported my application to Qt5, and which required xkbcommon. I compiled xkbcommon 0.10.0 for that.

After debuging through Qt, I got to xkbcommon, for which I enabled debug messages and got this:

```
xkbcommon: ERROR: /home/breno/.XCompose:1461:1: unrecognized keysym "dead_double_grave" on left-hand side
xkbcommon: ERROR: /home/breno/.XCompose:1462:1: unrecognized keysym "dead_double_grave" on left-hand side
xkbcommon: ERROR: /home/breno/.XCompose:1463:1: unrecognized keysym "dead_inverted_breve" on left-hand side
xkbcommon: ERROR: /home/breno/.XCompose:1464:1: unrecognized keysym "dead_inverted_breve" on left-hand side
xkbcommon: ERROR: /home/breno/.XCompose:1465:1: unrecognized keysym "dead_double_grave" on left-hand side
xkbcommon: ERROR: /home/breno/.XCompose:1466:1: unrecognized keysym "dead_double_grave" on left-hand side
xkbcommon: ERROR: /home/breno/.XCompose:1467:1: unrecognized keysym "dead_inverted_breve" on left-hand side
xkbcommon: ERROR: /home/breno/.XCompose:1468:1: unrecognized keysym "dead_inverted_breve" on left-hand side
xkbcommon: ERROR: /home/breno/.XCompose:1469:1: unrecognized keysym "dead_double_grave" on left-hand side
xkbcommon: ERROR: /home/breno/.XCompose:1470:1: unrecognized keysym "dead_double_grave" on left-hand side
xkbcommon: ERROR: /home/breno/.XCompose:1471:1: unrecognized keysym "dead_inverted_breve" on left-hand side
```

As an example, this is the line it complains about:
```
1461 <dead_double_grave> <A>                     : "Ȁ"   U0200 # LATIN CAPITAL LETTER A WITH DOUBLE GRAVE
```

This .XCompose is a file I copied from machine installation (/usr/share/X11/locale/en_US.UTF-8/Compose) to do my own testing.

I'm a bit stuck now. Is this really a bad file? Many of my users got this.
If not a bad file, could I have compiled the library in a wrong way?

```
/inout/meson/meson.py setup build -Denable-wayland=false -Dxkb-config-root=/usr/share/X11/xkb -Dx-locale-root=/usr/share/X11/locale                                                                                                                                                                                         
ninja -C build                                                                                                          
ninja -C build install
```

Let me know if you need more information.

Thanks!

**Comment by brenoguim** [comment]
Ok, I just found out that if I replace "double_grave" by "doublegrave" and "inverted_breve" by "invertedbreve" it works.

I have machines with both spellings. Weird.

**Comment by bluetech** [comment]
Looks like this was fixed in libX11 7 years ago: https://gitlab.freedesktop.org/xorg/lib/libx11/-/commit/47d2eff64d167b3245d346d7f38ca703be645e26

I don't think there is much we can do about this.

**Comment by brenoguim** [comment]
I understand, thanks for looking into this @bluetech .

I have patched libxkbcommon locally to raise the tolerable error count from 10 to 1000, so at least it mostly works aside from these specific characters.
