### ISSUE TITLE
how to add keysym

### ISSUE THREAD

**Issue by marcusatiliusregulus** [xkbcommon/libxkbcommon#176]
how do i add a new keysym? i want to use the name "Ssharp" as for the capital ssharp (U1E9E).

ps: is it possible to define a character sequence like s+c+h as "sch" so i can type make a key symbols[Group1]= [ sch ] and type the three characters with one keypress?

**Comment by whot** [comment]
keysyms are defined in the xorgproto repo in [keysymdef.h](https://gitlab.freedesktop.org/xorg/proto/xorgproto/-/blob/master/include/X11/keysymdef.h) and [XF86keysym.h](https://gitlab.freedesktop.org/xorg/proto/xorgproto/-/blob/master/include/X11/XF86keysym.h). Given the complexity of unicode, we don't usually add all keysyms though, the `U` prefix is good enough for many. Why do you need to add it specifically? [1]

XKB does not originally provide a one-keycode-to-many-keysyms mapping, only the other way round through e.g. dead keys and compose. I think libxbkcommon does provide the infrastructure but nothing else is hooked up so expect it to not work.

[1] there's also a problem with dependencies, you need to add it to xorgproto, make sure there's a release out, then you can add it to xkeyboard-config, so it takes a while at best.

**Comment by marcusatiliusregulus** [comment]
Thanks for the answer. I wanted to add this because I read on Stackoverflow that you can't put multiple Unicode-points in your keymap - but you can assign several to one keysym and then use this in the keymap. However, since I'm on wayland I don't use xmodmap and cannot just use this to assign the keysym as the answer suggested.

Creating an Ssharp keysym would just be for convenience to still know what this key does, even when the comment is lost due to compilation with `wev -M`.
What I REALLY want is a way to write common character groups with one keystroke (in English for example -ing). This is the reason why I don't just use the compose key: the char groups are to short to make it worth is (Multi_key and having to add some way to end the sequence to not be the prefix of other compose sequences take every advantage away).
I think this should be supported as this would be immensely useful for many languages and does not need any logic (no figuring out which chars are meant/how they are combined (in hangeul syllables the same letter sequence can be laid out differently according to syllable-length etc), just output the predefined characters in sequence).

**Comment by whot** [comment]
> since I'm on wayland I don't use xmodmap

[this post](https://who-t.blogspot.com/2020/08/user-specific-xkb-configuration-part-3.html) will be interesting then, it's part 3 but has the links to parts 1 and 2 to start with. libxkbcommon master but part 1 some things will already work with the current version.

> What I REALLY want is a way to write common character groups with one keystroke

unfortunately, XKB is not designed for that and you need to look into Input Methods (that's the google term to get started, good luck ;)

**Comment by marcusatiliusregulus** [comment]
> this [post](https://who-t.blogspot.com/2020/08/user-specific-xkb-configuration-part-3.html?m=1)

interesting post.

> look into Input Methods

thanks for the directions.

> unfortunately, XKB is not designed for that

too bad, i guess i'll close this now.
