### ISSUE TITLE
ci: windows can't find win_bison

### ISSUE THREAD

**Issue by bluetech** [xkbcommon/libxkbcommon#179]
For some reason meson stopped finding the `win_bison` program that should be installed by `choco install winflexbison3` command (which runs successfully): https://github.com/xkbcommon/libxkbcommon/runs/1048401113

**Comment by fooishbar** [comment]
At a guess, probably because Chocolatey doesn't actually change the path you're using, so you might have to manually add `C:\ProgramData\chocolatey\bin` to the path.
