### ISSUE TITLE
request: add support for setting repeat in symbols

### ISSUE THREAD

**Issue by dhead666** [xkbcommon/libxkbcommon#19]
It seems like when mapping an action to a key it lose its repeat value.
It would be nice if we can manually set this value.
Currently this feature also broken in X so I manually set the repeat with `xset r keycode`.

I should add that I requested this feature as complementary to my other request to [add RedirectKey action](https://github.com/xkbcommon/libxkbcommon/issues/18) and if it will not be added then I don't need the repeat feature.

See [my changes to xkeyboard-config](https://github.com/dhead666/archlinux-pkgbuilds/blob/chromebook_redirect_key/xkeyboard-config-chromebook/0003-chromebook-set-alt-shift-arrows-as-pgup-pgdown-home-.patch) <- Edit: Updated link the patch

**Comment by bluetech** [comment]
I applied your patch to our `test/data` directory, and played with `./test/interactive-evdev`, changing `repeat=yes`, `repeat=no` for `UP` in `symbols/pc`. It behaves as expected.

Or did I misunderstand the issue?

**Comment by dhead666** [comment]
That's strange, with this patch (against xkeyboard-config of course) on Gnome's Wayland session I need to manually set repeat with xset so it actually repeat the arrow keys.
I'll try the interactive-evdev test.

**Comment by bluetech** [comment]
I think we agreed there's no problem here, so closing.
