### ISSUE TITLE
modifying indicator "Num Lock" turns on keypad

### ISSUE THREAD

**Issue by marcusatiliusregulus** [xkbcommon/libxkbcommon#190]
If I put this:
```
default partial xkb_compatibility
"leds" {
        indicator "Num Lock" {
                modifiers= Shift;
                whichModState= effective+latched+locked;
        };
};
```
into ~/.xkb/compat/lednum ,
the LEDs work as I want them to, but some keys do not behave correctly anymore:
My keyboard (raspberry pi keyboard) has an overlay numblock
(= not a physical one but the 7-0,u-p, ... -keys send the numblock/keypad key if numlock is active)
which now is triggered every time I press shift.
Eg. if I want to type capital i (shift+i) I get the 5 of the numblock.
On keyboards with physical numblock the numblock-numbers are sent if I press a numblock key while holding shift.
Keys can still be capitalized with capslock correctly.

I use sway/wayland; my keyboard config is:
```
input type:keyboard {
    xkb_layout "de"
    #xkb_options misc:assign_shift_left_action  # does not help
}
```

When nothing is in ~/.xkb or if I copy /usr/share/X11/xkb/compat/ in it the keyboard works as it should,
but if I modify this copy of lednum as above the described behaviour occurs.

how do i fix this?

**Comment by bluetech** [comment]
I haven't looked into your scenario in detail, but one note is that `~/.xkb/compat/lednum` *overrides* the system `compat/lednum` file which has some other definitions and that's maybe what's causing the problem.

My suggestion is to add an option as described in https://xkbcommon.org/doc/current/md_doc_user-configuration.html#autotoc_md17 (although be sure to replace `symbols` with `compat` in your case), add the option to your sway config and see if the problem still occurs.

**Comment by bluetech** [comment]
I'll close this now, but feel free to reopen.
