### ISSUE TITLE
Documentation for keymap format text v1 still has todos

### ISSUE THREAD

**Issue by bl4ckb0ne** [xkbcommon/libxkbcommon#198]
[`xkb_symbols`][1] and [virtual modifiers][2] are still TODO in the XKB keymap text format V1 document file.

I am in the process of writing a virtual keyboard and writing my own keymap file and I would like to know if there is documentation elsewhere, or if this is planned to be done.

Simon

[1]: https://github.com/xkbcommon/libxkbcommon/blob/master/doc/keymap-format-text-v1.md#the-xkb_symbols-section
[2]: https://github.com/xkbcommon/libxkbcommon/blob/master/doc/keymap-format-text-v1.md#virtual-modifier-statements

**Comment by fooishbar** [comment]
Nothing to the best of my knowledge, just the documentation in the parser itself. Thanks a lot for taking this on, really looking forward to your contribution :)

**Comment by bl4ckb0ne** [comment]
I'll document as I write my keymap file, do you mind if I message you on IRC for quick questions?

**Comment by fooishbar** [comment]
Yep, no problem. Asking in `#wayland` would be best, I'm `daniels` there.

**Comment by whot** [comment]
fwiw, xkb_symbols is probably the one that's best documented online since it's the section most users would've modified in the past. So googling around for a bit should find quite a fair bit of info.

**Comment by bluetech** [comment]
Ivan Pascal's XKB page is the only other in-depth doc on the XKB format that I know of: https://web.archive.org/web/20190724015820/http://pascal.tsu.ru/en/xkb/

**Comment by bl4ckb0ne** [comment]
Thanks for the tip! The translation is a bit rough, Ill try to synthesize it for the doc entry.
