### ISSUE TITLE
xkb_rule_names alternatives for setting variant

### ISSUE THREAD

**Issue by bam80** [xkbcommon/libxkbcommon#199]
Here we don't use `.variant` field for setting the variant, instead passing it in parentheses in `.layout` field (as `"us(intl)"`):
https://lxr.kde.org/source/kde/workspace/kwin/xkb.cpp#0183

Is it actually the same as if we passed `"us"` in `.layout` and `"intl"` in `.variant`?

#192 @bluetech

**Comment by bluetech** [comment]
> Is it actually the same as if we passed "us" in .layout and "intl" in .variant?

Short answer: no -- you should use the `variant` field. Using the `us(intl)` form basically skips a translation layer.

Long answer:

As you know the high-level configuration RMLVO (rules, model, layout, variant, options) -- what's used by `xkb_rule_names` -- gets translated to a lower-level configuration KcCGST (keycodes, compat, geometry, symbols, types).

Now the two ways you mention in this case happen to translate to the same thing:

```
~/src/libxkbcommon$ ./build/compile-keymap --kccgst --layout 'us' --variant 'intl'
xkb_keymap {
  xkb_keycodes { include "evdev+aliases(qwerty)" };
  xkb_types { include "complete" };
  xkb_compat { include "complete" };
  xkb_symbols { include "pc+us(intl)+inet(evdev)" };
};

~/src/libxkbcommon$ ./build/compile-keymap --kccgst --layout 'us(intl)'
xkb_keymap {
  xkb_keycodes { include "evdev+aliases(qwerty)" };
  xkb_types { include "complete" };
  xkb_compat { include "complete" };
  xkb_symbols { include "pc+us(intl)+inet(evdev)" };
};
```

but that will not always be the case.

At the KcCGST level the `xkb_symbols = us(intl)` means "go to `<xkb-path>/symbols/us` file and find a `xkb_symbols "intl"` map".

At the RMLVO level the `layout = us(intl)` means "go to the evdev rules file and find the match for the `us(intl)` layout and add it to the KcCGST".

In this case `us(intl)` doesn't match any special rule so just uses some fallback rule which translates it straight to the `xkb_symbols`. But if there is a special rule then the variant needs to be separate:

```
~/src/libxkbcommon$ ./build/compile-keymap --kccgst --layout 'de' --variant 'neo'
xkb_keymap {
  xkb_keycodes { include "evdev+aliases(qwertz)" };
  xkb_types { include "complete" };
  xkb_compat { include "complete+caps(caps_lock)+misc(assign_shift_left_action)+level5(level5_lock)" };
  xkb_symbols { include "pc+de(neo)+inet(evdev)" };
};

$ ./build/compile-keymap --kccgst --layout 'de(neo)'
xkb_keymap {
  xkb_keycodes { include "evdev+aliases(qwerty)" };
  xkb_types { include "complete" };
  xkb_compat { include "complete" };
  xkb_symbols { include "pc+de(neo)+inet(evdev)" };
};
```

**Comment by bam80** [comment]
Oh, many thank! This reveals some problems in our implementation.
And also separate `variant` is easier for parsing - no need to do [Regex's for stripping the parentheses](https://invent.kde.org/plasma/kwin/-/merge_requests/457/diffs?commit_id=dd693855a90f40159b54c4f151c2f3e8638a4b3e#620854d26181bbd9e88786bdd451f7b1cbacd556_166_169) ;)
That was legacy code which needs to be revisited.
