### ISSUE TITLE
request: add xkb_state_get_active_layout functions.

### ISSUE THREAD

**Issue by rilian-la-te** [xkbcommon/libxkbcommon#20]
Similar to xkb_state_layout_name_is_active, but not checks active layout name, returns it instead.
This is useful for XKB plugins (keyboard layout switchers/indicators)

**Comment by bluetech** [comment]
If I understand correctly, you want to get the name of the currently
active layout.

You can do this as follows:

```.c
struct xkb_keymap *keymap = <...>;
struct xkb_state *state = <...>;
xkb_layout_index_t layout;
const char *layout_name;

layout = xkb_state_serialize_layout(state, XKB_STATE_LAYOUT_EFFECTIVE);
layout_name = xkb_keymap_layout_get_name(keymap, layout);
```

Please note that `layout_name` may be `NULL`; the reason is that a
layout is not required to have a name. In practice they almost always
do, but make sure to handle that in the code.

**Comment by rilian-la-te** [comment]
But can I use xkb_state_serialize_layout in client?

**Comment by bluetech** [comment]
It was not originally meant to be used by clients, but it is :) And
we're not going to break that.

But if you don't want to use it, you can do this:

```.c
const xkb_layout_index_t num_layouts = xkb_keymap_num_layouts(keymap);
xkb_layout_index_t layout;

for (layout = 0; layout < num_layouts; layout++)
    if (xkb_state_layout_index_is_active(state, i, XKB_STATE_LAYOUT_EFFECTIVE) > 0)
        break;

/* This should always be true: */
assert(layout < num_layouts);
```

**Comment by rilian-la-te** [comment]
Ok, I will use serialize_layout. It is better suit my code;) Do you need a VAPI for your library?

**Comment by bluetech** [comment]
What is a VAPI?

**Comment by rilian-la-te** [comment]
Vala bindings file for library. I write xkb plugin in Vala and force to write a vapi for xkbcommon.

**Comment by bluetech** [comment]
I'm not familiar with Vala personally. But if the bindings you wrote are reusable, then I'm sure future people who want to use libxkbcommon from Vala would appreciate it if you put them up on github. For example, there are bindings for Haskell.

**Comment by bam80** [comment]
> layout_name = xkb_keymap_layout_get_name(keymap, layout);

@bluetech AFAIK it returns descriptive layout name ("English (US)" or such).
But what if I want to know short name (mostly 2-letter country code: en, ru, ..) passed to `xkb_keymap_new_from_names()` as Layout in RMLVO set?
