### ISSUE TITLE
Proposal: xkb_compose_state_get_utf32

### ISSUE THREAD

**Issue by smilingthax** [xkbcommon/libxkbcommon#204]
xkbcommon already has both `xkb_state_key_get_utf8` and `xkb_state_key_get_utf32`, as well as `xkb_keysym_to_utf8` and `xkb_keysym_to_utf32`. There is even `xkb_utf32_to_keysym` (but not `xkb_utf8_to_keysym` ?).

So, when adding Compose support to an application that currently uses `xkb_state_key_get_utf32`, it now has to deal with `xkb_compose_state_get_utf8`, just because `xkb_compose_state_get_utf32` has not been implemented.

Thus I propose that a `uint32_t xkb_compose_state_get_utf32(struct xkb_compose_state *state)` function should be added.

And maybe `xkb_keysym_t xkb_utf8_to_keysym(const char *buffer, size_t size)` should be considered, too.

**Comment by bluetech** [comment]
The utf8 in `xkb_compose_state_get_utf8` can be any string, not necessarily one codepoint. For example you can happily have a line like

```
<Multi_key> <d>            : "DOG!"
```
