### ISSUE TITLE
single-item list without "," in the end is not accepted for xkb_rule_names::variant

### ISSUE THREAD

**Issue by bam80** [xkbcommon/libxkbcommon#208]
This is what I have learned experimenting way:
- if only one item in xkb_rule_names::layout list, it's OK to pass a string not ended with "," in xkb_rule_names::variant
- if xkb_rule_names::layout list contains more than one items, xkb_rule_names::variant must always end with ",", even if we have variant for the first layout only.

Should we fix that "," requirement in the end of the list maybe? Or at least document what list notion the library expects.

**Comment by whot** [comment]
I'm not sure if it's a implementation detail or an intended requirement, but the X tools had the same requirements. And the simple reason for it is to make it explicit which layout  the variant applies to. Without a trailing `,` the variant could arguably apply to *all* layouts, with the trailing comma it's more explicit to only apply to the first one.

Documenting this would be fine, but I'd argue against changing this behaviour.

**Comment by bam80** [comment]
Probably it needs to be documented better indeed - I assumed single "variant" item could only apply to single layout, regardless if it ends with `,` or not.
Anyway, does my investigation above describe the situation right, or there are some more details?

**Comment by whot** [comment]
fwiw, these two are very different 
- `layout=us,de variant=dvorak,` is equivalent to `us(dvorak),de`
- `layout=us,de variant=,dvorak` is equivalent to `us,de(dvorak)`

So the comma is merely the separator between the items to make it clear which one it applies to, that's why it's required.

But yeah, your description is correct and accurate, thanks, it's just a documentation issue that needs to be addressed.

**Comment by bam80** [comment]
Thanks for the clarifying.
And what about extra "," in the end of variants list?
- `layout=us variant=intl,`

I'm asking because library I'm going to handle these lists doesn't add comma to the end: https://api.kde.org/frameworks/kconfig/html/classKConfigGroup.html#a2b935a52d80b2e1af6aa3f26ee0833ef, so I'll have to do that manually. The easiest way would probably be just add the comma unconditionally.

**Comment by whot** [comment]
not 100% if that parses correctly but I'd assume in this case it's ignored since the layout list and variant list matches up. And if it doesn't parse correctly, I'd say it's a bug.

**Comment by bam80** [comment]
Ok. I think for Plasma Wayland session I'll handle it with extra "," then.
Will report how it goes. Thanks.

**Comment by bluetech** [comment]
The behavior is, in Python,

```py
variants = [v.strip() for v in rmlvo.variant.split(',')]
```

i.e.

```
""      -> { "" }
"a"     -> { "a" }
"a,"    -> { "a", "" }
"a,b"   -> { "a", "b"}
"a,b,"  -> { "a", "b", "" }
"a,b,c" -> { "a", "b", "c"}
"a,,c"  -> { "a", "", "c"}
```

And the layout is split in the same way. The rules file then refers to the positions as `layout[1]`, `variant[3]` etc (1-based indexing).

**Comment by bam80** [comment]
So I modified the function used to clean trailing commas from the list.
Would appreciate for feedback if it looks good for you.
Another option would be to eliminate that function completely, having thus the same amount of commas in all lists always. Not sure how it handled in other utils.
https://invent.kde.org/plasma/plasma-desktop/-/merge_requests/340/diffs

**Comment by bluetech** [comment]
> Another option would be to eliminate that function completely, having thus the same amount of commas in all lists always. Not sure how it handled in other utils.

right, the amount of parts in the variants list should be the same as in the layout list. So

layouts | variants | valid?
----------|------------|--------
us | intl | VALID
us | intl,intl | INVALID
us,us | intl,intl | VALID
us,us | intl | INVALID
us,us | intl, | VALID
us,us | ,intl | VALID
us,us | intl,intl,intl | INVALID
us,us | , | VALID
us,us |  | VALID (no variant)
us,us,us | intl,,intl | VALID
us,us,us | intl,, | VALID
us,us,us | ,intl, | VALID
us,us,us | intl, | INVALID (but works)

**Comment by bam80** [comment]
layouts | variants | valid?
-- | -- | --
us,us,us | intl, | INVALID (but works)

Oops, seems I fixed it wrong way then. Thanks for letting me know!

**Comment by bam80** [comment]
layouts | variants | valid?
-- | -- | --
us,us | , | VALID
us,us |   | VALID (no variant)

Currently there will always be at least one comma.
Is it makes any difference?

**Comment by bluetech** [comment]
No, for empty it's the same.

**Comment by bam80** [comment]
Thanks!
