### ISSUE TITLE
Feature request: add xkb_x11_set_keymap_for_device

### ISSUE THREAD

**Issue by rilian-la-te** [xkbcommon/libxkbcommon#21]
for setting keymap on X server via xkbcommon-x11.

**Comment by bluetech** [comment]
That makes sense to add. The reason it isn't already there is that it requires a *lot* of grunt work, and probably some xcb-xkb changes. Hopefully I'll get to it at some point.

For now I've rebased some old work I had (just some stubs) and put it here: https://github.com/bluetech/libxkbcommon/tree/wip-x11-keymap-set

**Comment by bluetech** [comment]
So TBH, I don't think this is ever going to be implemented, it is quite a lot of work, for ever declining benefit. So I'll close this now as `TOOMUCHWORK` :) But if someone ever wants to work on it, that would be fine.
