### ISSUE TITLE
"modifier_map None" is not supported

### ISSUE THREAD

**Issue by wismill** [xkbcommon/libxkbcommon#211]
Using Xorg setxkbmap & xkbcomp tools it is possible to clear a `modifier_map` of a key using `modifier_map None`.

However, using `xkbcli compile-keymap` on a custom layout containing `modifier_map None { Caps_Lock };` I get:

```
xkbcommon: ERROR: Illegal modifier map definition; Ignoring map for non-modifier "None"
xkbcommon: ERROR: Failed to compile xkb_symbols
xkbcommon: ERROR: Failed to compile keymap
```

* setxkbmap 1.3.2
* xkbcomp 1.4.4
* xkbcli 1.0.3

**Comment by bluetech** [comment]
Thanks, I can confirm. This got lost on the way somewhere.

Looks like xkbcomp translate `"none"` into `XkbNoModifier = 0xff` (from X11/extensions/XKB.h) which is some sorts of in-band hackery that the X server understands. Needs some looking into.
