### ISSUE TITLE
No 1.1.0 tarball/announcement

### ISSUE THREAD

**Issue by mattst88** [xkbcommon/libxkbcommon#215]
There doesn't seem to have been a 1.1.0 announcement email sent, and there's no tarball available in https://xkbcommon.org/download/

Did the process change and I shouldn't expect those things anymore? That is, should I just always get the tarball directly from github?

**Comment by bluetech** [comment]
I uploaded [the tarball](https://github.com/xkbcommon/libxkbcommon/releases/download/xkbcommon-1.1.0/libxkbcommon-1.1.0.tar.xz) to GitHub now and sent the [announcement](https://lists.freedesktop.org/archives/wayland-devel/2021-March/041747.html). Sorry for the inconvenience.

**Comment by mattst88** [comment]
No problem. Thanks a bunch.

I just wanted to check whether the process changed. It's happened with other projects switching from tarballs to git tags and sometimes they're not very nice if you ask them about tarballs. So thank you :)

**Comment by bluetech** [comment]
The website is also updated now.
