### ISSUE TITLE
xkbcli list output awkward to parse

### ISSUE THREAD

**Issue by hickford** [xkbcommon/libxkbcommon#218]
I'm trying to use xkbcli to list all layouts and variants. The colon-separated records are ideal, but they're a little awkward to extract:

    xkbcli list |                 # Print models, layouts and options
    awk '/Layouts:/,/Options:/' | # Extract layouts records between headers
    grep -oP '^- \K.*'          | # Remove indent
    cut -f1 -d ':'                # Print first colon-separated column 

Thus it could be useful to have a command option to print specific information, such as just layouts:

    xkbcli list --detail=layouts | # Print just layouts (without header)
    grep -oP '^- \K.*'           | # Remove indent
    cut -f1 -d ':'                 # Print first colon-separated column 

Not sure if the indents could also be simplified somehow. While the models and layouts information is essentially flat, I see the options information has two levels.

https://manpages.debian.org/testing/libxkbcommon-tools/xkbcli-list.1.en.html
https://github.com/xkbcommon/libxkbcommon/blob/master/tools/registry-list.c

**Comment by whot** [comment]
tbh, I think a better option than trying to make this parseable/filtered with arguments would be to have a `--json` argument and let callers filter the output with `jq` or some other approach. This immediately makes anything possible that will ever be required, with minimal effort on our side.

**Comment by whot** [comment]
> While the models and layouts information is essentially flat, I see the options information has two levels.

fwiw, the nesting is:
- model
- layout
  - variant
- option group
  - option

**Comment by hickford** [comment]
Great idea, JSON would be easier to parse.

**Comment by whot** [comment]
do you feel like submitting a PR? :)

**Comment by hickford** [comment]
Might be beyond my C experience. Are there any constraints to adding a dependency on a JSON library (Fedora has cJson, json-c, jansson)? The alternative would be DIY printf.

**Comment by whot** [comment]
the format is simple enough that DIY printf will be less effort than going through a library (*producing* json is usually quite easy, *consuming* it is the trickier bit).

and what I'd do is hook it up in the CI so that we write out a few json files and then parse them with simple python scripts to make sure the format is correct. This way the difficult bits aren't in C.

**Comment by bluetech** [comment]
In 1.3.0 the format is now YAML. @whot included some examples how to process it with `yq` in the commit message https://github.com/xkbcommon/libxkbcommon/commit/f434c690cc7f5e47f122f54fa13ec26a533090ac.
