### ISSUE TITLE
Feature request: add xkb_state_layout_get_short_name()

### ISSUE THREAD

**Issue by rilian-la-te** [xkbcommon/libxkbcommon#22]
For now xkb_state_layout_get_name returns a long name, like Russian,
but can you add a function that returns a short name, like ru?

**Comment by rilian-la-te** [comment]
Do keymap have a possibility to return a rule names or keyboard description string?

**Comment by bluetech** [comment]
In general you can't know which rule-names a keymap was created from (if at all), and the layouts in the keymaps themselves only have long names. So we don't have a way to provide such a function. Also some keymaps are not human-language based (e.g. APL programming layout) or are using some variant so don't really have a well-known short name.

The inverse mapping short name -> layout name does exist, in the file `/usr/share/X11/xkb/rules/evdev.xml` or `evdev.lst`. They are simple enough to parse so libxkbcommon does deal with them itself. These files are useful for tools which *set* the keymaps, but not when you want to know a short name for an already compiled keymap.

**Comment by rilian-la-te** [comment]
But I have found such function (sorry, Vala & GLib)
```vala
        private void find_short_names_from_keymap()
        {
            try {
                var symbols_regex = new Regex("(xkb_symbols)(\\s+)(\".*?\")");
                MatchInfo info;
                symbols_regex.match(state.keymap.get_as_string(),0,out info);
                var symbols_str = info.fetch(3);
                var first_name_regex = new Regex("(_)([a-z][a-z]+)(_)");
                first_name_regex.match(symbols_str,0,out info);
                layout_short_names[0] = info.fetch(2);
                var next_names_regex = new Regex("(_)([a-z][a-z]+)(_)([0-9])");
                next_names_regex.match(symbols_str,0,out info);
                for (var i = 1; info.matches(); info.next(), i++)
                    layout_short_names[i] = info.fetch(2);
            } catch (Error e) {
                stderr.printf("Layouts cannot be parsed: %s\n",e.message);
            }
        }
```

**Comment by rilian-la-te** [comment]
This is just some regex and xkb_keymap_get_as_string

**Comment by bluetech** [comment]
These are strings we could theoretically expose (see the last few fields of `struct xkb_keymap` definition in `src/keymap.h`).  However they are just an amalgamation of some maps which were added along the way, they are not really meant to be exposed to the user. There is no guarantee on the order things appear there, or what happens when you have multiple layouts, etc. So I don't think using this is a good idea.

Basically, neither X11 or Wayland base protocols provide a way to get a short name for the layout. If you want the rule names, and you are not the one who's setting it, you can try:

1. If you are working with a specific desktop environment (e.g. gnome, kde) they probably have a specific way to get that info, e.g. by some dbus interface or a "gsettings" key.
2. The systemd "localed" also has a system-wide setting:
```
ran@ran:~$ busctl get-property org.freedesktop.locale1 /org/freedesktop/locale1 org.freedesktop.locale1 X11Layout 
s "us"
```
3. Check how "gnome-shell" and other systems do that.

**Comment by rilian-la-te** [comment]
I use awesome way (awesome wm function rewritten in vala). I can explain, how I do this.
1.
I call xkb_keymap_get_as_string()
Receive a full keymap.
2.
I search for layout names by regex:
(finding string like this ```xkb_symbols pc_us_ru_2_inet(evdev)_group(alt_shift_toggle)_compose(ralt)_terminate(ctrl_alt_bksp)"```)
3. Extract "us" and "ru" symbols by regex.
This is a right way?

**Comment by rilian-la-te** [comment]
Found the following in evdev.xml:

    <layout>
      <configItem>
        <name>af</name>
        
        <shortDescription>fa</shortDescription>
        <description>Afghani</description>
      </configItem>
this is possible to return a shortDescription key?

**Comment by bluetech** [comment]
Sorry for the delay!

As I explained before, I don't think using regexes on the `xkb_symbols` line is a good idea. It will certainly break for someone, or in the future.

Regarding evdev.xml, libxkbcommon doesn't parse it itself as there is no added value to that. The application is better off parsing it itself and getting the info it needs.

In any case, we won't (can't) add a `xkb_state_layout_get_short_name()`. Feel free to open another issue if there's something else.
