### ISSUE TITLE
setxkbmap does nothing

### ISSUE THREAD

**Issue by sezanzeb** [xkbcommon/libxkbcommon#223]
Is this the right project to report this?

On ubuntu with wayland e.g. `setxkbmap us` doesn't change my keyboard layout. It works when I switch to X11.

libxkbcommon 0.10.0, ubuntu 20.10

no Idea how I can get the newest version installed. Don't know what kind of debug output I could hand out to you. setxkbmap doesn't log anything.

**Comment by sezanzeb** [comment]
with -v I get this:

```
Warning! Multiple definitions of keyboard layout
         Using command line, ignoring X server
Trying to build keymap using the following components:
keycodes:   evdev+aliases(qwerty)
types:      complete
compat:     complete
symbols:    pc+us+inet(evdev)
geometry:   pc(pc105)
```

**Comment by bluetech** [comment]
`setxkbmap` only affects the keymap of the X server.

- Which Wayland compositor are you using? (Gnome Shell, KDE, etc)
- Why do you need to run `setxkbmap`?

**Comment by sezanzeb** [comment]
Gnome

---

The goal is to add support for arbitrary symbols to https://github.com/sezanzeb/key-mapper. At the moment only symbols that are already part of the system layout can be used. It works on two of my machines running X11, it doesn't work on the mentioned wayland pc and there: https://github.com/sezanzeb/key-mapper/issues/33

If there is an alternative way to accomplish it that can be automated and works on both wayland and X11 reliably, I'd love to know about it

I guess that might be a separate issue though. He is running KDE on X11.

The following configuration doesn't work there:

/usr/share/X11/xkb/symbols/key-mapper/Corsair_CORSAIR_HARPOON_RGB_WIRELESS_Gaming_Dongle:

```
default xkb_symbols "key-mapper" {                                                                                                                                                           
    key <93> { [ F24 ] };                                                                                                                                                                    
    key <97> { [ ccedilla ] };                                                                                                                                                               
};  
```

keycodes: https://github.com/sezanzeb/key-mapper/blob/xkb/data/key-mapper-keycodes

command: `setxkbmap -keycodes key-mapper-keycodes -symbols key-mapper/Corsair_CORSAIR_HARPOON_RGB_WIRELESS_Gaming_Dongle -device 18`

**Comment by fooishbar** [comment]
Wayland does not implement a generic way for clients to change the keymapping; you'd have to work through environment-specific configuration API.

**Comment by sezanzeb** [comment]
oh no.

I just tried to find how that can be done via commands in KDE/Mutter, but all of the information talks about their user interfaces. Having to support one module for each environment sounds bad anyway

**Comment by bluetech** [comment]
In xkbcommon>=1.0.0 we have some support for custom user configuration in the user's home directory: https://xkbcommon.org/doc/current/md_doc_user_configuration.html

So you'd need to create your configuration, and then tell the compositor to use it.

At least Gnome sets the layouts and options in its settings and listens to changes, so you can do:

```
$ gsettings set org.gnome.desktop.input-sources sources "[('xkb', 'us'), ('xkb', 'ru')]"
$ gsettings set org.gnome.desktop.input-sources xkb-options "['lv3:ralt_switch', 'compose:ralt']"
```

I don't know if it's possible to stitch that together into something stable that works well :)

**Comment by sezanzeb** [comment]
Thanks for the suggestion. It needs to be applied on a single device though that key-mapper creates via python-evdev.

Going to close this issue then. Thanks for your help
