### ISSUE TITLE
%destructor declaration break built on osx

### ISSUE THREAD

**Issue by discordianfish** [xkbcommon/libxkbcommon#23]
Hi,

I'm tried to compile libxbcommon on osx but yacc throws an syntax error. I tried both bison 2.3 and byacc 1.9 20141128. Reverting 7ec00933c178942b04f4716882132f7971db7d26 fixed the issue for me.

**Comment by bluetech** [comment]
bison 2.3 is ~9 years old... If only osx had the next minor version, 2.3a, according to the bison NEWS I think it would have worked :)  Is there no way to use a more up-to-date version?

The byacc version you mention should work, but you need to compile it with `--enable-btyacc` configure flag.

At the time I could not find a more portable way to avoid the (admittedly unlikely) memory leaks explained in 7ec0093, so I'd prefer not to add ifdefs for the destructors, unless it can't be avoided.

**Comment by discordianfish** [comment]
Hrm.. it doesn't seem to work with byacc either:

```
PKG_CONFIG_PATH=/opt/X11/lib/pkgconfig/ YACC=byacc ./configure --enable-btyacc
...
$ make
  YACC     src/xkbcomp/parser.c
byacc: e - line 219 of "/Users/fish/Downloads/libxkbcommon-0.5.0/src/xkbcomp/parser.y", syntax error
%destructor { FreeStmt((ParseCommon *) $$); }
^
make: *** [src/xkbcomp/parser.c] Error 1
```

**Comment by bluetech** [comment]
Oh, sorry, I meant that byacc itself needs to be configured with `--enable-btyacc`. See here: http://invisible-island.net/byacc/manpage/yacc.html#h2-EXTENSIONS

**Comment by bluetech** [comment]
Since I don't want to rip the `%destructor` statements out, or introduce ifdefs for this, osx users will need to either use byacc, or a little more recent version of bison.

**Comment by Zenitur** [comment]
Same in SLE 11 SP4

**Comment by bluetech** [comment]
Hmm, looking [here](https://www.suse.com/releasenotes/x86_64/SUSE-SLES/11-SP4/) this looks like a recent release? Why does it have 10 years old bison?

In any case, if you must, you can just patch out the `%destructor` statements; this will only expose you to a very small very unlikely memory leak in case a keymap fails to parse.

**Comment by Zenitur** [comment]
The patch for 0.7.1 version:
```diff
--- a/src/xkbcomp/parser.y	2016-08-20 11:30:04.000000000 +0000
+++ b/src/xkbcomp/parser.y	2016-08-20 11:30:13.000000000 +0000
@@ -216,6 +216,14 @@
 %type <file>    XkbFile XkbMapConfigList XkbMapConfig
 %type <file>    XkbCompositeMap
 
+%destructor { FreeStmt((ParseCommon *) $$); }
+    <any> <expr> <var> <vmod> <interp> <keyType> <syms> <modMask> <groupCompat>
+    <ledMap> <ledName> <keyCode> <keyAlias>
+/* The destructor also runs on the start symbol when the parser *succeeds*.
+ * The `if` here catches this case. */
+%destructor { if (!param->rtrn) FreeXkbFile($$); } <file>
+%destructor { free($$); } <str>
+
 %%
 
 /*
@@ -770,6 +778,7 @@
     struct parser_param param = {
         .scanner = scanner,
         .ctx = ctx,
+        .rtrn = NULL,
     };
 
     /*
@@ -799,6 +808,7 @@
                 FreeXkbFile(param.rtrn);
             }
         }
+        param.rtrn = NULL;
     }
 
     if (ret != 0) {
```

**Comment by Zenitur** [comment]
Apply with `patch -R -p1`
