### ISSUE TITLE
Is Meta_L/Meta_R a modifier or a normal key?

### ISSUE THREAD

**Issue by AlynxZhou** [xkbcommon/libxkbcommon#232]
Hi, I am working on [my own screenkey alternative](https://github.com/AlynxZhou/showmethekey) and I use xkbcommon for keymap handling. I need to know whether a key is a modifier or a normal key, and when I press Shift+Alt on my keyboard, I got a Meta_L/Meta_R. Refer to <https://github.com/xkbcommon/libxkbcommon/blob/afc5370c8638a3157f05a3cdea8452c545d1f44f/xkbcommon/xkbcommon.h#L247> it seems Meta is a modifier, but we have no mod name for it (see <https://github.com/xkbcommon/libxkbcommon/blob/master/xkbcommon/xkbcommon-names.h>) so I cannot query it with `xkb_state_mod_name_is_active`.

Should I handle it as a normal key? Or this is just a bug? Thanks.

**Comment by bluetech** [comment]
The question needs to be a bit more precise.

> I need to know whether a key is a modifier or a normal key

What do you mean by a "key"? For reference:

- `Meta_L` and `Meta_R` are keysyms.
- `Shift+Alt` can refer to multiple things - a combination of keycodes (physical keys) or keysyms. It also matters what state they are in (both pressed, locked, released etc.)
- `Meta` is a modifier.

I don't mean to be pedantic -- the answer depends on what exactly you want to achieve.

**Comment by AlynxZhou** [comment]
Hi, thank you for your reply, what I want to know is, for example, when user press `KEY_A`, I should display `a` because xkbcommon tells me that it's not a modifier. And when user press `KEY_LEFTCTRL` only, I will display nothing because xkbcommon tells me it's a modifier. I will only display `Ctrl` when user press it with other keys like `a`.

But for `Meta`, I am confused, the comment of xkbcommon says it's a modifier, but when user press `KEY_LEFTSHIFT` and `KEY_LEFTALT`, xkbcommon gives me `Meta_L` as keysym. If it's a modifier, I should display nothing like when user press `KEY_LEFTCTRL`, but when I query it with `xkb_state_mod_name_is_active`, it says `Meta_L` is not a modifier. I am not sure if this is a bug.

**Comment by wismill** [comment]
`Meta` is a _virtual_ modifier (see the [terminology](https://github.com/xkbcommon/libxkbcommon/blob/master/doc/keymap-format-text-v1.md#terminology-terminology)). `xkb_state_mod_name_is_active` queries only _real_ modifiers. `Meta` is mapped internally to a mask of _real_ modifiers. See [“Define and use a modifier”](https://github.com/xkbcommon/libxkbcommon/blob/master/doc/keymap-format-text-v1.md#define-and-use-a-modifier).

Also see #88 for further details. You would need #36 to query if `Meta` is active.

You cannot use `Meta_L`, as it is a keysym.
