### ISSUE TITLE
Are 1.2.0 and 1.2.1 stable releases?

### ISSUE THREAD

**Issue by ryandesign** [xkbcommon/libxkbcommon#233]
I see tags for 1.2.0 and 1.2.1 but they do not have the tar.xz files attached and the 1.1.0 tag is still marked as the latest release.

**Comment by bluetech** [comment]
The 1.1.0 release from github was a one-time thing (see #215). Our normal process is to announce to the wayland-dev mailing list and update the website. The tarballs are here: https://xkbcommon.org/download/

If the github releases are helpful I can consider doing them regularly although I'd prefer to have less steps for myself :)

**Comment by whot** [comment]
Note that I have a strong opinion here, but in case you do want to do both, the [xf86-input-wacom driver release.sh](https://github.com/linuxwacom/xf86-input-wacom/blob/master/release.sh) script uploads tarballs and tags them as releases. You can probably extract the required bits from there into your release scripts to save you some trial and error.

Come to think of it - I do have an opinion :)

I think it'd be better to remove the proper release from github and only have the tarballs on xkbcommon.org, because now the 1.1.0 will be forever marked as the latest release so this won't be the last bug on that topic.

**Comment by bluetech** [comment]
> I think it'd be better to remove the proper release from github and only have the tarballs on xkbcommon.org, because now the 1.1.0 will be forever marked as the latest release so this won't be the last bug on that topic.

Yeah I would do that but since that's the URL I gave for the 1.1.0 release, I wouldn't want to break it now.

I've added a note to the release https://github.com/xkbcommon/libxkbcommon/releases/tag/xkbcommon-1.1.0 maybe that would help. Also after some time we can maybe remove it anyway.

**Comment by ryandesign** [comment]
Thanks for clarifying and I totally understand not wanting to cause additional work for yourself for each release. I'm the maintainer of xkbcommon in MacPorts and I remember reading about the one-time release process for 1.1.0 at the time but had already forgotten about it by now.

Indeed the cause of confusion was the mention of release 1.1.0 on this project's GitHub main page. I think solving that would be a good idea to prevent confusion.

If you don't want to make further GitHub releases then the simplest solution would be to delete the 1.1.0 release but I can see how that is a problem since that's the download URL you announced.

One low-effort possibility would be to just create GitHub releases for new tags. You wouldn't have to attach any files to the release or fill in any release notes if you don't want to, although either attaching the file or providing a link to the download directory in the notes, like you did for the 1.1.0 release, would be helpful. If the creation of the GitHub releases can be automated using a script like @whot mentioned above and integrated into your existing release process, maybe that would make it easy enough to do.

**Comment by bluetech** [comment]
OK, I added some automation for this, so (hopefully) from the next release it should be created automatically.
