### ISSUE TITLE
osx' ld doesn't suppport `--version-script`

### ISSUE THREAD

**Issue by discordianfish** [xkbcommon/libxkbcommon#24]
When trying to compile on osx, I get: `ld: unknown option: --version-script=./xkbcommon.map`. With this option removed from the Makefile and after working around #23 I can built everything just fine.

**Comment by bluetech** [comment]
We could use the libtool version scripts instead, but I'd like to avoid it. Since we use symbol visibility and it works on osx too, it's OK to make the version script optional. I'll add an autoconf test for that.

**Comment by bluetech** [comment]
Should be fixed by 257e38c82124454808687d1208629069109474ce. If you could verify that the autoconf test works correctly in OSX, that would be nice.

**Comment by discordianfish** [comment]
I would verify this but unfortunately I can't get autogen.sh to work, getting:

```
configure.ac:45: error: must install xorg-macros 1.16 or later before running autoconf/autogen
```

I installed XQuartz and not sure if I just need to point autoreconf to the right location or actually miss something. With the configure script in the latest release things worked though. So if you have some ideas how to fix that, I'm happy to verify that your commit fixed it.

**Comment by bluetech** [comment]
Yes, if you start from autogen.sh you need to install "xorg-macros". Quickly it would be

```.sh
wget http://xorg.freedesktop.org/releases/individual/util/util-macros-1.19.0.tar.bz2
tar xf util-macros-1.19.0.tar.bz2
cd util-macros-1.19.0
./configure && make
```
Then either `cp xorg-macros.m4 <xkbcommon git checkout>/m4` for just xkbcommon or `make install` to install globaly.

Then `./autogen.sh` should work.

**Comment by discordianfish** [comment]
Ok, autogen.sh works now and (after removing the %destructor definitions) it built and linked properly.
