### ISSUE TITLE
FEATURE REQUEST make capslock able to act as ctrl and esc simultaniously 

### ISSUE THREAD

**Issue by IllustratedMan-code** [xkbcommon/libxkbcommon#248]
I made a feature request [here](https://bugs.kde.org/show_bug.cgi?id=437267) on the kde bug tracker for this functionality and I was directed here.
I would like the capslock key to be able to act as a ctrl when held down and another key is pressed, but should act as an esc key when tapped. This would act similarly to the [Mod-Tap](https://docs.qmk.fm/#/mod_tap?id=mod-tap) functionality in QMK keyboard firmware.

**Comment by wismill** [comment]
If you want QMK features using software, you would be better served by: keyd, kmonad, kanata and the likes. This feature is unlikely going to make it in xkbcommon.
