### ISSUE TITLE
XkbParseFile does not expect a trailing \0 in the file

### ISSUE THREAD

**Issue by Pernet** [xkbcommon/libxkbcommon#249]
Weston and Mutter (Wayland compositors) write the entire keymap string (with its trailing \0) in the keymap file provided to XkbParseFile, but XKB parser does not expect a trailing \0 in the file, so xkb_keymap_new_from_file function fails with "unrecognized token".

In Weston:
https://gitlab.freedesktop.org/wayland/weston/-/blob/main/libweston/input.c#L3180 (weston_xkb_info_create function)
In Mutter:
https://gitlab.gnome.org/GNOME/mutter/-/blob/master/src/wayland/meta-wayland-keyboard.c#L135 (meta_wayland_keyboard_take_keymap function)

_xkbcommon_lex should treat \0 case.
It may be treated as EOF.
https://github.com/xkbcommon/libxkbcommon/blob/f60bdb1680650a131e8e21ffa4a8a16775a35c9f/src/xkbcomp/scanner.c#L81

**Comment by bluetech** [comment]
Are you using `xkb_keymap_new_from_file()` to parse the keymap you get from the compositor? How do you create the `FILE*`?

If you want to parse a C string (terminated with `\0`) and you have the entire string, you can use `xkb_keymap_new_from_striing()`. Alternately you can use `xkb_keymap_new_from_buffer`, and pass an explicit length (without the `\0`).

**Comment by Pernet** [comment]
> Are you using `xkb_keymap_new_from_file()` to parse the keymap you get from the compositor? How do you create the `FILE*`?

Wayland server send a file descriptor to Wayland client (and the size of the file).
https://wayland.freedesktop.org/docs/html/apa.html#protocol-spec-wl_keyboard
All users of XKB I reviewed seems to mmap the file, then call xkb_keymap_new_from_string.
I have tried fdopen. I can read the whole file, and see this annoying \0.
https://pubs.opengroup.org/onlinepubs/9699919799/functions/fdopen.html

**Comment by bluetech** [comment]
`mmap` is the intended usage -- any reason you want to use `fdopen` instead?

**Comment by bluetech** [comment]
Closing, let me know if you have further questions.
