### ISSUE TITLE
xkb_keymap_key_get_syms_by_level behavior question

### ISSUE THREAD

**Issue by matthiasclasen** [xkbcommon/libxkbcommon#255]
I was writing some code to answer the question "How many ways can I type this Unicode character?" (compose sequences, dead keys, etc), and I wanted to take the current keyboard layout into account for what keysyms are available. But I hit a snag when I found that xkb thinks my current layout doesn't have a Multi_key (although I'm using it right now).

Dumping the layout we get from mutter, it clearly contains the right information:

```
<RCTL>               = 105;

[...]

        key <RCTL>               {
                type= "TWO_LEVEL",
                symbols[Group1]= [       Multi_key,       Multi_key ]
        };
```

But when I'm walking the layout with xkb_keymap_num_layouts_for_key, xkb_keymap_num_levels_for_key and
xkb_keymap_key_get_syms_by_level, Multi_key never shows up. I get Control_R for keycode 105. 

What am I missing ?

**Comment by fooishbar** [comment]
You’re missing the magic +8 offset.

**Comment by matthiasclasen** [comment]
I saw a notification about a comment about a "magic offset" that I can't find any trace of now.

Just to clarify: this is all on the client-side, only working with keysyms and xkb keycodes.
My understanding of the "magic offset" is that it is between evdev and xkb. But I am not dealing
with evdev at all here.

**Comment by bluetech** [comment]
To check this, I just [added](f8c430cf7157bb45aeeb3dacce69730bad3052a4) support for checking a keysym directly with `xkbcli how-to-type`, which works with `xkb_keymap_key_get_syms_by_level` and friends. With it I get

```
$ ./build/xkbcli-how-to-type --option compose:ralt --keysym Multi_key
keysym: Multi_key (0xff20)
KEYCODE  KEY NAME  LAYOUT   LAYOUT NAME          LEVEL#  MODIFIERS
108      RALT      1        English (US)         1       [ ]
108      RALT      1        English (US)         2       [ Shift ]
```

so it seems to work. I'm not sure why it doesn't work for you. If you can provide more details on how you set things up I can try to guess.

**Comment by matthiasclasen** [comment]
Ah, silly mistake on my part - I need to create a surface and wait for the compositor to send me the keymap before I can do these checks. My code was using the initial pc105/us keymap which does not have the compose option set.
