### ISSUE TITLE
layout switching stops after nbsp option is added

### ISSUE THREAD

**Issue by frogtile** [xkbcommon/libxkbcommon#256]
I am using sway (1.5.1),

my config file for sway previously had,

```
input type:keyboard {
	xkb_layout us,bd(probhat)
	xkb_options grp:win_space_toggle,compose:ralt
}
``` 
layout swtiching worked, using `Mod+Space`.

config file now has,

```
input type:keyboard {
	xkb_layout us,bd(probhat)
	xkb_options grp:win_space_toggle,compose:ralt,nbsp:zwnj2zwj3
}
```
Now I can't switch keyboard layout, `Mod+Space` doesn't do anything

**Comment by bluetech** [comment]
The `win_space_toggle` option does

```
partial modifier_keys
xkb_symbols "win_space_toggle" {               
  key <SPCE> {
    type="PC_SUPER_LEVEL2",
    symbols[Group1]= [ space, ISO_Next_Group ],
    symbols[Group2]= [ space, ISO_Next_Group ]
  };
};
```

and the `nbsp:zwnj2zwj3` option does 

```
partial
xkb_symbols "zwnj2zwj3" {                           
  key <SPCE> {
    type[Group1]="FOUR_LEVEL",
    symbols[Group1]= [ space, 0x100200c, 0x100200d ]
  };
};
```

so they conflict I'm afraid -- you need to choose one or the other.

**Comment by frogtile** [comment]
Fortunately, recently i have noticed that `bd(probhat)` layout has ZWNJ and ZWJ on \ and ` key.

(but, `gkbd-keyboard-display` shows them like `U+2...` instead of `U+200C`, even when the window size is larger.)

**Comment by bluetech** [comment]
OK, great. In any case I'll close this since libxkbcommon does not develop the keymap definitions themselves, that's another project, xkeyboard-config.
