### ISSUE TITLE
Multiple definitions of FOUR_LEVEL_KEYPAD in test/data/keymaps/host.xkb

### ISSUE THREAD

**Issue by nuko8** [xkbcommon/libxkbcommon#26]
In `xkb_types "complete"` of  `test/data/keymaps/host.xkb`, `FOUR_LEVEL_KEYPAD` is defined twice and both of the two definitions are identical one another.

I'm wondering if the duplication might be unnecessary for the `x11comp` test.

I raise this question because the test fails on my Mac OS X 10.9.5, leaving the message:

```
Multiple definitions of the FOUR_LEVEL_KEYPAD key type
Earlier definition ignored
...
round-trip test failed: dumped map differs from original
length: dumped 56580, original 56965
```

in `test-suite.log`.

In addition, the dumped map is just a `host.xkb` which only differs in the multiplicity of the definition from the original; the former only contains a single definition of `FOUR_LEVEL_KEYPAD`.

Actually, as indicated by the message and the dumped map, if I resolve the duplication by deleting one of the definitions in the original file, the test readily passes.

Is the duplication really needed?

Thanks

**Comment by bluetech** [comment]
I think the test should pass for you now after 74f85d05402411c4f18bd431c919fa631a37a90d. If you could verify, that would be great.

**Comment by nuko8** [comment]
Great.  That really works fine for me.  Thanks!

FWIW, I'm using xkbcomp 1.3.0 and XQuartz 2.7.7 (xorg-server 1.15.2).

**Comment by bluetech** [comment]
Thanks for testing!
