### ISSUE TITLE
Parsing xkb_geometry

### ISSUE THREAD

**Issue by bl4ckb0ne** [xkbcommon/libxkbcommon#261]
I am in the process of writing an on screen keyboard, and I plan on using the `xkb_geometry` to organize the layout.

I saw in the [compat.md][1] that the geometry support has been removed, leaving the gap to be filled by a side library. Does such library exist yet? 

If not, would you be open to either allow the user to plug their own parser callback (maybe around [here][2]), or to bring back a very simple geometry parsing (section, rows and keys)?

[1]: https://github.com/xkbcommon/libxkbcommon/blob/f60bdb1680650a131e8e21ffa4a8a16775a35c9f/doc/compat.md#compatibility
[2]: https://github.com/xkbcommon/libxkbcommon/blob/master/src/xkbcomp/keymap.c#L246

**Comment by whot** [comment]
tbh, I don't think the XKB geometry format is a useful one. It's not well understood by tools (compared to e.g. SVG that can just be rendered), it's detailed to a point of being unnecessary and the use-case of it is very narrow anyway.

And a quick check of xkeyboard-config shows that in the last 10 years, only 2 keyboards were added to the geometries files. So it's not exactly up-to-date, it simply relies on the default model being good enough for display.

I think there's a case for having visual pictures of keyboards, I don't think XKB geometry is it though.

**Comment by bl4ckb0ne** [comment]
Why isnt XKB geometry a good choice? I don't want to bring another custom format of my own just to organize the layout when XKB geometry has what I need.

**Comment by whot** [comment]
> Why isnt XKB geometry a good choice?

See my comment above

**Comment by bl4ckb0ne** [comment]
Figured it out, went with another format.
