### ISSUE TITLE
wrong layouts number returned with lv3:ralt_alt option

### ISSUE THREAD

**Issue by bam80** [xkbcommon/libxkbcommon#262]
The behavior produces a crash of KWin on Wayland currently, making it impossible to start a session:
https://bugs.kde.org/show_bug.cgi?id=440027

Here is the relevant part of /usr/share/X11/xkb/symbols/level3:
```
// The right Alt key never chooses the third level.
// This option attempts to undo the effect of a layout's inclusion of
// 'ralt_switch'.  You may want to also select another level3 option
// to map the level3 shift to some other key.
partial modifier_keys
xkb_symbols "ralt_alt" {
  key <RALT> {
    type[Group1]="TWO_LEVEL",
    type[Group2]="TWO_LEVEL",
    type[Group3]="TWO_LEVEL",
    type[Group4]="TWO_LEVEL",
    symbols[Group1] = [ Alt_R, Meta_R ],
    symbols[Group2] = [ Alt_R, Meta_R ],
    symbols[Group3] = [ Alt_R, Meta_R ],
    symbols[Group4] = [ Alt_R, Meta_R ]
  };
  modifier_map Mod1 { <RALT> };
};
```
_This option causing `xkb_keymap_num_layouts()` to return 4, despite the fact we requested only 2 layouts when creating the context with `xkb_keymap_new_from_names()`. The problem is we currently assume the former can't increase the latter._

The same configuration produces different internal keymap for KWin on X11 and Wayland (which uses libxkbcommon):
**X11** (taken as xkbcomp $DISPLAY out.xkb):
```
key <RALT> {
        type= "TWO_LEVEL",
        symbols[Group1]= [           Alt_R,          Meta_R ]
    };
```
vs
xkbcommon (**Wayland**):
```
key <RALT>               {
    type= "TWO_LEVEL",
    symbols[Group1]= [           Alt_R,          Meta_R ],
    symbols[Group2]= [           Alt_R,          Meta_R ],
    symbols[Group3]= [           Alt_R,          Meta_R ],
    symbols[Group4]= [           Alt_R,          Meta_R ]
  };
```
We don't understand yet which one is right, but probably these two should be the same?

**Comment by bam80** [comment]
Many thanks from KDE community! :) :tada:

**Comment by bam80** [comment]
Seems I faced similar issue again, but now that `xkb_keymap_num_layouts()` can only return 4 max, even if source RMLVO contained more layouts.
Is it a bug?

**Comment by wismill** [comment]
From [comment above](https://github.com/xkbcommon/libxkbcommon/issues/262#issuecomment-948307768):
> 
> xkbcomp only calls `MergeGroups` if the added key **and** the destination key have symbols defined for a group. This would skip the loop for groups 3 and 4 on the RALT definition here, resulting in 2 groups in total. libxkbcommon adds those two extra groups so we end up with 4 groups on this key and across the keymap.
> 
> My guess right now is that this behavior is incorrect, it just didn't trigger any real bug so far. From a short skim through xkeyboard-config that particular option seems to be the only one that relies on this particular behaviour - defining four groups and hoping the excessive ones get silently dropped.
> 

I observed that `xkbcomp` has the exact same behavior, but you need to have *different* symbols for each group to trigger it, else `xkbcomp` removes identical groups:

```diff
xkb_symbols "ralt_alt" {
  key <RALT> {
    type[Group1]="TWO_LEVEL",
    type[Group2]="TWO_LEVEL",
    type[Group3]="TWO_LEVEL",
    type[Group4]="TWO_LEVEL",
    symbols[Group1] = [ Alt_R, Meta_R ],
-   symbols[Group2] = [ Alt_R, Meta_R ],
+   symbols[Group2] = [ Alt_R, Alt_R ],
-   symbols[Group3] = [ Alt_R, Meta_R ],
+   symbols[Group3] = [ Alt_R, Meta_L ],
-   symbols[Group4] = [ Alt_R, Meta_R ]
+   symbols[Group4] = [ Alt_L, Meta_R ]
  };
  modifier_map Mod1 { <RALT> };
};
```

So we *could* add this extra step to mimic the `xkbcomp` behavior, but that would not prevent `libxkbcommon` nor `xkbcomp` to add more than 1 group per key from an included symbol file.

There are 2 properties at our disposal to detect if the parsed file is a whole keymap or an included file for a `specific* group:
1. `IncludeStmt::modifier`: this gives us what is the target group. So if set, we can force only one group per key. However, this is usually *not set* for the first group, so this is not reliable.
2. `SymbolsInfo::include_depth`: detect if currently using an included file. There is no include statement in resulting keymaps compiled by xkbcommon, so if this is set we could force to drop the extra groups. But in principle, an include statement at keymap level to import keys with various groups is also legitimate.

We could use 2) to raise a warning though, and add this warning detection to `test/xkeyboard-config-test.py.in`. This script is also run on `xkeyboard-config`, so we could *ensure* we never ship a symbol file with multiple groups there.

Also, when compiling a keymap from RMLVO names, we do know exactly how many groups are expected, so we could pass this info to the parser and discard:
- Extra groups after the first one for each included symbols file;
- Extra groups after the last expected one, in case the rules resolution added those.

This solution with RMLVO names seems robust and can be combined with the warning of the previous section.
