### ISSUE TITLE
xmlCleanupParser called early

### ISSUE THREAD

**Issue by hickford** [xkbcommon/libxkbcommon#273]
Looking at https://github.com/xkbcommon/libxkbcommon/blob/master/src/registry.c#L1200 xmlCleanupParser is called in the success path, but libxml2 might be used again later.

http://xmlsoft.org/html/libxml-parser.html#xmlCleanupParser

> This function name is somewhat misleading. It does not clean up parser state, it cleans up memory allocated by the library itself. It is a cleanup function for the XML library. It tries to reclaim all related global memory allocated for the library processing. It doesn't deallocate any document related memory. **One should call xmlCleanupParser() only when the process has finished using the library and all XML/HTML documents built with it. See also xmlInitParser() which has the opposite function of preparing the library for operations. WARNING: if your application is multithreaded or has plugin support calling this may crash the application if another thread or a plugin is still using libxml2. It's sometimes very hard to guess if libxml2 is in use in the application, some libraries or plugins may use it without notice. In case of doubt abstain from calling this function or do it just before calling exit() to avoid leak reports from valgrind !

**Comment by whot** [comment]
woah. good find, thanks for linking to the docs, I clearly didn't read those when implementing.

looks like (especially given the comment in the xml doc) we can't call `xmlCleanupParser()` at all then. We're a library, so we can't know if anything else in the same process is using libxml after us.

**Comment by bluetech** [comment]
I think we can just remove it; libxml2 adds destructor/atexit for it so it's probably going to be fine with valgrind as well.
