### ISSUE TITLE
registry ignores XML popularity attribute

### ISSUE THREAD

**Issue by hickford** [xkbcommon/libxkbcommon#278]
[registry.c](https://github.com/xkbcommon/libxkbcommon/blob/master/src/registry.c) ignores the [popularity attribute](https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/blob/master/rules/xkb.dtd) in XML, instead setting popularity exotic if the file name contains 'extras'.

Backwards compatibility suggests to continue to assume exotic in extras, but an improvement could be to read the popularity attribute in base.

See also https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/merge_requests/76

**Comment by whot** [comment]
I'd be happy to merge a PR that parses that property, but arguably - if something is exotic it needs to go into extras.xml for the foreseeable future to ensure backwards compatibility.
