### ISSUE TITLE
xkbcomp: allow trailing comma in SymbolsBody

### ISSUE THREAD

**Issue by stev47** [xkbcommon/libxkbcommon#28]
There is a trailing comma in xkeyboard-config at `symbols/level5:40` which leads to an error in the current parser.
Looking at `parser.y` and the declaration of `SymbolsBody` it seems that leading commas are allowed but trailing ones aren't. I'm guessing that is a mistake.
Allowing empty `SymbolsVarDecl` should solve the issue (allowing empty `SymbolsBody` might be removed).

**Comment by bluetech** [comment]
Did you mean another line? I don't see a trailing comma [here](http://cgit.freedesktop.org/xkeyboard-config/tree/symbols/level5?id=7e78b92cf760ab9b767c17a6f0491cf490b10869#n40).

**Comment by stev47** [comment]
Oh, a mistake on my part, there was never a trailing comma upstream. `xkbcomp` on X doesn't seem to allow trailing commas either.
This might be a nice-to-have, but I'm closing it.
