### ISSUE TITLE
If you have any plans to support the Latin-based Kazakh alphabet?

### ISSUE THREAD

**Issue by GeniusMilk** [xkbcommon/libxkbcommon#282]
# I wonder if you have any plans to support the Latin-based Kazakh alphabet? 

##### This link may help you understand what I mean.

[Kazakhstan Presents New Latin Alphabet, Plans Gradual Transition Through 2031](https://astanatimes.com/2021/02/kazakhstan-presents-new-latin-alphabet-plans-gradual-transition-through-2031/)

**Comment by bluetech** [comment]
Hi, please refer this question to the [xkeyboard-config](https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/issues) project, which contains the definitions of keymaps.
