### ISSUE TITLE
Is there a way to distinguish layout with dead keys programmatically?

### ISSUE THREAD

**Issue by bam80** [xkbcommon/libxkbcommon#287]
Or at least check if particular key is dead or not?

We have a bug about shortcuts with dead keys do not work on first press:
https://bugs.kde.org/show_bug.cgi?id=451966

Qt traverses configured layouts until it finds one with Latin symbols, to make shortcuts work on any layout.
I wonder if we could make it to skip Latin layouts with dead keys somehow..

**Comment by whot** [comment]
I think [xkb_keymap_key_get_syms_by_level](https://xkbcommon.org/doc/current/group__components.html#gad92b9334170316926595fbb5d634a181) should do the trick, it'll require iteration through the keymap though. And you'll need a list of keys that are dead keys.

**Comment by bluetech** [comment]
Closing, let us know if you still need an answer.
