### ISSUE TITLE
Why would xkb_x11_get_core_keyboard_device_id return -1?

### ISSUE THREAD

**Issue by IoIxD** [xkbcommon/libxkbcommon#289]
I have a program that is going to be deployed to a QEMU-like program. It works completely fine on my main development PC, but when running it in either QEMU or the alternative, xkb_x11_get_core_keyboard_device_id returns -1, meaning no keyboard events are listened to.

This is an admittedly newbie question (although I've spent nearly 4 hours trying to fix it) but I've never had to worry about something this low level when developing for Linux before. What would cause this, and how would I fix it?

**Comment by bluetech** [comment]
The code for the function is:

```c
XKB_EXPORT int32_t
xkb_x11_get_core_keyboard_device_id(xcb_connection_t *conn)
{
    int32_t device_id;
    xcb_xkb_get_device_info_cookie_t cookie = xcb_xkb_get_device_info(conn, XCB_XKB_ID_USE_CORE_KBD, 0, 0, 0, 0, 0, 0);
    xcb_xkb_get_device_info_reply_t *reply = xcb_xkb_get_device_info_reply(conn, cookie, NULL);

    if (!reply)
        return -1;

    device_id = reply->deviceID;
    free(reply);
    return device_id;
}
```

To see why it fails, I suggest copy/pasting the the above into your own code, but also pass the third argument to `xcb_xkb_get_device_info_reply` (instead of NULL) to see what is the X11 error. You can do it like this:

```c
xcb_generic_error_t *error;
reply = xcb_xkb_get_device_info_reply(conn, cookie, &error);
if (!reply) {
    printf("ERROR CODE: %d\n", error->error_code);
    return -1;
}
```

**Comment by bluetech** [comment]
If `reply` is `nil`, then I think `theError` would be not `nil`. So if you change the `if(reply != nil)` to `if(theError != nil)`, what is the value of `msg`?

**Comment by IoIxD** [comment]
theError is also nil.

**Comment by whot** [comment]
just a random thought: `DISPLAY` is set correctly and you do have a connection to the X server?

**Comment by IoIxD** [comment]
![image](https://user-images.githubusercontent.com/30945097/168695963-fdbf9c57-782a-4a61-8f48-f2182a6e42dc.png)

**Comment by bluetech** [comment]
This is almost certainly not an xkbcommon problem, and we don't have any more ideas, so closing.

**Comment by IoIxD** [comment]
Yes, xkb on this linux install was broken. I forgot to respond with this, sorry.
