### ISSUE TITLE
Why does xkb_state_serialize_mods and XKB_STATE_LOCKED not update when unlocked until the next keystroke?

### ISSUE THREAD

**Issue by n3rdopolis** [xkbcommon/libxkbcommon#297]
I admit I might be above what I am familiar with, and I don't know if opening this as an issue is the best way to ask for help here, and the first time I am using libxkbcommon...  

We are trying to add input device to Plymouth, there 3 authors who have commits in the pull request, the goal, instead of making it get input from the VT subsystem as it currently does, to use evdev devices. One of the last things that are needed to be done is to add Num Lock/Caps Lock support to it where if Num Lock is pressed on one keyboard, the state is synced between all devices.    
    
Right now the LED state is queried with `xkb_state_serialize_mods()` seen here https://gitlab.freedesktop.org/Diegovsky/plymouth/-/blob/dev_input/src/libply-splash-core/ply-input-device.c#L384 in the hopes when numlock/capslock/scrolllock is pressed, and they sync the state between all devices.   
   
it seems to work well when a lock is activated, however when a lock is DEactivated it doesn't work. Checking the state on EVERY key stroke, when I deactivate NumLock, 
and it seems that the behavior is the same when I poll it with `xkb_state_mod_name_is_active` instead, until the next keystroke after an unlock keystroke on NumLock or CapsLock, does it start returning that it's unlocked

I tried 
xkb_state_update_key(input_device->keyboard_state, XKB_KEY_NoSymbol + 8, XKB_KEY_DOWN);
xkb_state_update_key(input_device->keyboard_state, XKB_KEY_NoSymbol + 8, XKB_KEY_UP);
to fake a key event to no  avail, and I tried lookimg at Weston and wlroots to the best of my ability...

**Comment by n3rdopolis** [comment]
I rescind this, I was filtering to only act on XKB_KEY_DOWN, and it seems that when a lock is unlocked that it acts on XKB_KEY_UP evends

**Comment by whot** [comment]
just ftr, I'm pretty sure that's in the XKB protocol specification, which is obviously the grandfather of all this behaviour.
