### ISSUE TITLE
Unable to build on CentoS5 ?? no idea?

### ISSUE THREAD

**Issue by efontana** [xkbcommon/libxkbcommon#3]
[root@farm505 libxkbcommon-master]# ./autogen.sh
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4 ${ACLOCAL_FLAGS}
autoreconf: configure.ac: tracing
configure.ac:32: warning: The macro`AC_FOREACH' is obsolete.
configure.ac:32: You should run autoupdate.
autoconf/general.m4:196: AC_FOREACH is expanded from...
aclocal.m4:2707: _AM_SET_OPTIONS is expanded from...
aclocal.m4:2445: AM_INIT_AUTOMAKE is expanded from...
configure.ac:32: the top level
autoreconf: running: libtoolize --copy --force
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, `build-aux'.
libtoolize: copying file`build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: copying file`m4/libtool.m4'
libtoolize: copying file `m4/ltoptions.m4'
libtoolize: copying file`m4/ltsugar.m4'
libtoolize: copying file `m4/ltversion.m4'
libtoolize: copying file`m4/lt~obsolete.m4'
autoreconf: running: /usr/bin/autoconf --force --warnings=all
configure.ac:32: warning: The macro `AC_FOREACH' is obsolete.
configure.ac:32: You should run autoupdate.
autoconf/general.m4:196: AC_FOREACH is expanded from...
aclocal.m4:2707: _AM_SET_OPTIONS is expanded from...
aclocal.m4:2445: AM_INIT_AUTOMAKE is expanded from...
configure.ac:32: the top level
autoreconf: running: /usr/bin/autoheader --force --warnings=all
autoreconf: running: automake --add-missing --copy --force-missing --warnings=all
Makefile.am: C objects in subdir but`AM_PROG_CC_C_O' not in `configure.ac'
Makefile.am:82: user target`src/xkbcomp/parser.h' defined here...
automake: ... overrides Automake target `src/xkbcomp/parser.h' defined here
autoreconf: automake failed with exit status: 1

**Comment by SudakovIvan** [comment]
`-fgnu89-inline` gcc  flag helps (gcc 4.7.2). See  https://gcc.gnu.org/onlinedocs/gcc-4.7.1/gcc/Inline.html
