### ISSUE TITLE
test/x11comp started to fail

### ISSUE THREAD

**Issue by bluetech** [xkbcommon/libxkbcommon#30]
Presumably after a recent update to either xkbcomp or xserver. In retrospect, this test is not very future proof... But it is useful, so I should check out the diff.

**Comment by bluetech** [comment]
I've temporarily disabled it for now: 914e84e0188b5fbd67855f38f4499bb1412f4516

**Comment by wismill** [comment]
This test is re-enabled by #348. It seem the error may be caused by old versions of `xkeyboard-config`. I did not investigate further, but I think we should keep this issue opened until we assess to origin of the error, as it could be a regression.

**Comment by wismill** [comment]
No issue anymore, newer version of `xkeyboard-config` were tested without issue, so it does not seem worth to keep this open.
