### ISSUE TITLE
File reference not up to date?

### ISSUE THREAD

**Issue by jbriales** [xkbcommon/libxkbcommon#303]
In this line:
https://github.com/xkbcommon/libxkbcommon/blob/2530f6444bfad2bf67ee926e57df8987afeebf4a/include/xkbcommon/xkbcommon-keysyms.h#L117

I could not find such `keysyms.xml` file in the repo.

**Comment by whot** [comment]
See [the file source](https://github.com/xkbcommon/libxkbcommon/blob/master/include/xkbcommon/xkbcommon-keysyms.h#L122). it says:

```
 *   - the protocol specification in specs/keysyms.xml in this repo
 *     https://gitlab.freedesktop.org/xorg/proto/xorgproto
```
