### ISSUE TITLE
xkb_keymap_new_from_buffer does not allow terminating null bytes

### ISSUE THREAD

**Issue by whot** [xkbcommon/libxkbcommon#307]
If a  null-terminated buffer is given to `xkb_keymap_new_from_buffer()`, our keymap fails to parse:
```
xkbcommon: ERROR: (input string):1928:3: unrecognized token
xkbcommon: ERROR: (input string):1928:3: syntax error
xkbcommon: ERROR: Failed to parse input xkb string
```
Fairly easy to verify by modifying our existing keymap compile test to include the NULL-byte.

```diff
diff --git a/test/buffercomp.c b/test/buffercomp.c
index 12b67fe..88a369d 100644
--- a/test/buffercomp.c
+++ b/test/buffercomp.c
@@ -66,9 +66,15 @@ main(int argc, char *argv[])
         assert(0);
     }
 
+    free(dump);
+    xkb_keymap_unref(keymap);
+
+    /* Load a prebuild keymap but include the trailing NULL byte */
+    keymap = test_compile_buffer(ctx, original, strlen(original) + 1);
+    assert(keymap);
+    xkb_keymap_unref(keymap);
+
     free(original);
-    free(dump);
-    xkb_keymap_unref(keymap);
 
     /* Make sure we can't (falsely claim to) compile an empty string. */
     keymap = test_compile_buffer(ctx, "", 0);
```
This seems needlessly pedantic :) 

In our case the keymap comes from a different process (the compositor) so we don't control if the null-byte is included or not, it'd be nice to just have this handled correctly.

**Comment by whot** [comment]
cc @ofourdan

**Comment by ofourdan** [comment]
Yeah, [the documentation for xkb_keymap_new_from_buffer()](https://xkbcommon.org/doc/current/group__keymap.html#ga19e1a8824c7c51bf5ac8a8cb8b7d40d2) is somehow unclear, it reads:

> This is just like [xkb_keymap_new_from_string()](https://xkbcommon.org/doc/current/group__keymap.html#ga9d98e2e1348bd756bd3229d0b9432886), but takes a length argument so the input string does not have to be zero-terminated.

It does not say the buffer must **not** be zero-terminated.
