### ISSUE TITLE
Make a XKB_CONTEXT_YES_DEFAULT_INCLUDES flag?

### ISSUE THREAD

**Issue by RPigott** [xkbcommon/libxkbcommon#308]
Hi there.

I'm working on sway, which uses CAP_SYS_NICE to gain realtime priority. This has the unfortunate side-effect of borking `xkb_context_include_path_append_default` because secure_getenv refuses to read $HOME, $XDG_CONFIG_HOME, etc. and this is a hassle to avoid.

I would be interested in maybe a XKB_CONTEXT_YES_DEFAULT_INCLUDES flag (opposite of XKB_CONTEXT_NO_DEFAULT_INCLUDES) that would add these default configs using getenv on request. Sway doesn't support suid operation so I believe there would be no security risk to create our xkb context with such a flag.

Related: swaywm/sway#7311

**Comment by bluetech** [comment]
xref #129

**Comment by RPigott** [comment]
Sure, I can send that patch.

**Comment by bam80** [comment]
Thanks, I thin it will help us too :)
https://lxr.kde.org/source/plasma/kwin/src/xkb.cpp#0180
```c++
0179 /**
0180  * libxkbcommon uses secure_getenv to read the XKB_DEFAULT_* variables.
0181  * As kwin_wayland may have the CAP_SET_NICE capability, it returns nullptr
0182  * so we need to do it ourselves (see xkb_context_sanitize_rule_names).
0183  **/
0184 void Xkb::applyEnvironmentRules(xkb_rule_names &ruleNames)
