### ISSUE TITLE
Allow multiple characters/code points from one keypress

### ISSUE THREAD

**Issue by Lieutenant-L-T-Smash** [xkbcommon/libxkbcommon#317]
Enhancement request:

Allow a single entry in a Symbols file to include multiple characters or Unicode code points. the motivation is the ability to easily type certain accented letters used in some languages that can only be formed by using combining diacritics, so multiple code points are required. Letters such as č̭ (U+010D & U+032D) or V̱ (U+0056 & U+0331) currently require at least two keystrokes and cannot be mapped to a single key. There are legitimate, if rare, languages that use letters having no precomposed Unicode characters for them, and Unicode's policy makes it unlikely that they will be included if they can be made by using combining sequences. The input method should be able to emit such sequences.

See this question from over 10 years ago:
https://unix.stackexchange.com/questions/43073/custom-xkb-layout-in-which-one-key-creates-two-unicode-code-points

**Comment by wismill** [comment]
This feature is already implemented. Note that _it may work on Wayland only_.

Example:

```
key <AB03>	{[	 {U010D, U032D},	 {U010C, U032D}		]};
```

**Comment by Lieutenant-L-T-Smash** [comment]
Oh, that's interesting. Unfortunately, for me, it appears to be treating the {} definitions as null/empty and using the characters defined in the included base layout.

Would you point me to the changeset(s) and any documentation around this feature?

**Comment by wismill** [comment]
I did not develop this feature nor use it (_for now_). Doc is scarce: I think you need to browse the API doc or source code.

Also I insist it does not work with every app: e.g. it works for me in Kate and Konsole in a Plasma _Wayland_ session. I did not test X11 and I suppose it will not work.

**Comment by Lieutenant-L-T-Smash** [comment]
I had to do a bit of searching as the function got renamed and ten moved, but I think the initial changeset that introduced this feature (with the function xkb_key_get_syms) is:
https://github.com/xkbcommon/libxkbcommon/commit/bc074525420e54784543504a7a1a7cd6a0f9c998

**Comment by whot** [comment]
>  I did not test X11 but I suppose it will not work

Simply said, it will never work in X. The amount of effort required to make this work for all legacy applications is way beyond what anyone has time or motivation for, ignoring the API breaks we'd probably need to even get it working. And until backwards compatibility with X becomes a nonissue, we probably won't have any standard keymaps with multiple keysyms either.

**Comment by Lieutenant-L-T-Smash** [comment]
This neither needs to be supported by all applications, nor have keymaps included as standard. People working with specific languages can distribute the keymaps and point out compatible applications within their community. Something is better than nothing; don't let perfect be the enemy of good; etc.

I'm not aware of the architecture involved, but is X11 itself some kind of barrier to applications making use of this feature?

**Comment by wismill** [comment]
There is a workaround working in most cases, using [compose](https://manpages.debian.org/bullseye/libx11-doc/XCompose.3.en.html): use a codepoint in a [private use area](https://en.wikipedia.org/wiki/Private_Use_Areas) in your keymap, then add a compose entry with only that codepoint that output multiple characters.

**Comment by wismill** [comment]
I think this issue can be closed: there is a [workaround](https://github.com/xkbcommon/libxkbcommon/issues/317#issuecomment-1496961088) that seems to work everywhere; else it is a _downstream_ issue.

**Comment by Lieutenant-L-T-Smash** [comment]
Right, so feature is already complete in this project. Closed.

I'm still interested in why "it will never work in X" - is there some major architectural block, or just inertia and a lack of will?

**Comment by whot** [comment]
> I'm not aware of the architecture involved, but is X11 itself some kind of barrier to applications making use of this feature?

Nothing in the X/XKB protocol caters for multiple keysyms per keycode. You *may* be able to somewhat side-step this by negotiating the keymap separately from the X server and using libxkbcommon directly (which is roughly what happens in Wayland). That requires a lot of work [^1] and coordination and even if you do get it for some apps there will be unexpected behaviour when you mix those apps with others.

For a system that is effectively on life-support only (Xorg is unmaintained and Xwayland won't see any major changes to the server itself) that's unlikely to ever happen.

---
[^1]: *some* of the wayland work may actually have put the right scaffolding into the toolkits
