### ISSUE TITLE
libxkbcommon missing libX11 locale files on wayland-only systems

### ISSUE THREAD

**Issue by juanitotc** [xkbcommon/libxkbcommon#323]
If libxkbcommon is built and used on a linux wayland only system using the weston reference compositor, various apps will fail with the following error message:

```
xkbcommon: ERROR: couldn't find a Compose file for locale C
```

..because libX11 is not present and so /usr/local/share/X11/locale is missing.

Should libxkbcommon include these files for the wayland-only case and/or find another way of achieving the same thing?

**Comment by bluetech** [comment]
This needs a coordinated effort to move libX11 locale data to a separate project from libX11. I'd like to see this happen, but I don't think there is much drive for it. In the meantime the solution is for distros to split the data to a separate package themselves. For example Debian has the locale data in a `libx11-data` package which doesn't bring in libX11 itself: https://packages.debian.org/sid/libx11-data

**Comment by juanitotc** [comment]
OK - understood, thanks

**Comment by whot** [comment]
libX11-common in Fedora, just ftr

**Comment by wismill** [comment]
Closing, as this is a distribution issue not directly linked to xkbcommon. Feel free to reopen if you have any new information.
