### ISSUE TITLE
github pages job?

### ISSUE THREAD

**Issue by whot** [xkbcommon/libxkbcommon#326]
@bluetech any reason (other than ETIME) we don't have a pages job to have up-to-date documentation? Right now afair the xkbcommon.org doc requires a manual sync.

**Comment by bluetech** [comment]
The website (code [here](https://github.com/xkbcommon/website)), DNS and tarballs are hosted by @fooishbar, and I sync it using ssh on every release. So automating would require giving the CI ssh access.

**Comment by fooishbar** [comment]
I'd be perfectly happy moving it over to GitHub Pages, or GitLab Pages if you wanted to move it to fd.o ...

Let me know what you need for me. Happy to change DNS, give you access to DNS (in fact, check your email and you've got an invite from Joker), add accounts to the machine currently hosting it, etc etc.

**Comment by bluetech** [comment]
Thanks, I was able to connect to Joker.

Next step will be to set up a github pages clone of xkbcommon.org.

Then set it up to use the custom domain. Should take special care to keep all URLs in tact.

Then we can look at automating it.

**Comment by emersion** [comment]
Migrating to GitHub pages would be a step backwards wrt. #259.

**Comment by whot** [comment]
This was added in 134c6bb28eaa8ebdcea41e8454f5d158e96dcd14, see https://xkbcommon.github.io/libxkbcommon/doc/current/pages.html
