### ISSUE TITLE
Just variant in RMLVO does nothing

### ISSUE THREAD

**Issue by JohnGebbie** [xkbcommon/libxkbcommon#336]
It's surprising that if you only set the variant in the RMLVO, the variant is ignored.

I am using Go bindings but this:

```
names := xkb.RuleNames{Variant: "dvorak"}
ctx := xkb.ContextNew(xkb.ContextNoFlags)
keymap = ctx.KeymapNewFromNames(&names, xkb.KeymapCompileNoFlags)
```
shows:

    xkbcommon: DEBUG: Compiling from RMLVO: rules 'evdev', model 'pc105', layout 'us', variant '(null)', options ''
    xkbcommon: DEBUG: Compiling from KcCGST: keycodes 'evdev+aliases(qwerty)', types 'complete', compat 'complete', symbols 'pc+us+inet(evdev)'

Whereas this:

```
names := xkb.RuleNames{Layout: "us", Variant: "dvorak"}
ctx := xkb.ContextNew(xkb.ContextNoFlags)
keymap = ctx.KeymapNewFromNames(&names, xkb.KeymapCompileNoFlags)
```
shows:

    xkbcommon: DEBUG: Compiling from RMLVO: rules 'evdev', model 'pc105', layout 'us', variant 'dvorak', options ''
    xkbcommon: DEBUG: Compiling from KcCGST: keycodes 'evdev+aliases(qwerty)', types 'complete', compat 'complete', symbols 'pc+us(dvorak)+inet(evdev)'

If this is the intended behavior, how can I make keymap with user's default layout but a specified variant?

**Comment by wismill** [comment]
This is the intended behaviour: you cannot specify a variant without the corresponding layout. A variant is a _variation_ of a layout, so it does not make sense _alone_ but only _coupled_ with its layout.

For instance: what would be the variant “dvorak” of a non-latin script? of braille? There is none.

**Comment by JohnGebbie** [comment]
Sure but I'd be happy for it to error in that case.

For context, you can specify the layout and variant my uinput tool should simulate keycodes for, and you'd expect (and I thought!) setting just the variant would be the same layout as default but whatever variant of it.

The same behavior as:

```
setxkbmap -variant dvorak -print
```
Worst case, I'll hardcode the default layout to `us`.

**Comment by whot** [comment]
> If this is the intended behavior, how can I make keymap with user's default layout but a specified variant?

bit tricky, because the "default layout" is actually "the layout compiled into libxkbcommon", the user's preference may or may not make a  difference (see `XKB_CONTEXT_NO_ENVIRONMENT_NAMES`). 

This is unlike `setxkbmap` which gets the values from the X properties (`_XKB_RULES_NAMES` iirc) where they can be changed any time.

Long story short: a warning about a variant without a layout would be good to have for transparency but in your case hardcoding `us` if no layout is given is probably the best solution.

**Comment by JohnGebbie** [comment]
Thanks for making it clear! I decided to just have my tool bail with a message if the variant but not the layout is specified, rather than anything subtle.

I'm happy for this be closed, but I'll guess I'll leave it for the new pull request.
