### ISSUE TITLE
Exporting keymap from `xkb_keymap` in XKM format?

### ISSUE THREAD

**Issue by twaik** [xkbcommon/libxkbcommon#365]
It looks like I can create keymap with such a snippet: 
<details>

```
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <xkbcommon/xkbcommon.h>
#include <unistd.h>

int main() {
    struct xkb_context *ctx;
    struct xkb_keymap *keymap;
    char buf[4096] = {0};

    ctx = xkb_context_new(XKB_CONTEXT_NO_ENVIRONMENT_NAMES);
    if (!ctx) {
        fprintf(stderr, "Cannot create xkb context\n");
        return EXIT_FAILURE;
    }

    read(0, buf, sizeof(buf)/sizeof(buf[0]) - 1);
    buf[strlen(buf) - 1] = 0;
    printf("buffer: \n%.*s\nEOF\n", (int) strlen(buf), buf);

    keymap = xkb_keymap_new_from_buffer(ctx, buf, strlen(buf), 1, 0);
    if (!keymap) {
        fprintf(stderr, "Cannot create keymap from buffer\n");
        xkb_context_unref(ctx);
        return EXIT_FAILURE;
    }

    printf("Keymap created successfully from buffer\n");

    xkb_keymap_unref(keymap);
    xkb_context_unref(ctx);
    return EXIT_SUCCESS;
}
```
</details>

But how to get string in XKM format to export it to X server?

<details>
<summary> Old post </summary>

Hi. Is it possible to compile custom `xkbcomp`?
X server always invokes xkbcomp with the following arguments:
`-w 1 "-R/usr/share/X11/xkb" -xkm - -em1 "The XKEYBOARD keymap compiler (xkbcomp) reports:" -emp ">" -eml "Errors from xkbcomp are not fatal to the X server" /tmp/server-1.xkm`
Where 
- `-w 1` is `set warning level to 1`.
- `-xkm` to compile xkm
- `-` to read options from `stdin`
- `-em1 "The XKEYBOARD keymap compiler (xkbcomp) reports:" -emp ">" -eml "Errors from xkbcomp are not fatal to the X server"` to set warning and error messages
- `/tmp/server-1.xkm` to set output file path

Also X server sends text like this to `xkbcomp`'s `stdin`:
```
xkb_keymap "default" {
    xkb_keycodes             { include "evdev+aliases(qwerty)" };
    xkb_types                { include "complete" };
    xkb_compatibility        { include "complete" };
    xkb_symbols              { include "pc+us+ua:2+il:3+inet(evdev)" };
    xkb_geometry             { include "pc(pc105)" };
};
```
Text may vary for different keyboard layouts but anyway it is pretty standard.
Can we make something like this to handle such config?

I know it is better to use original xkbcomp, but I am building embedded X server and size of it's components is pretty much significant. Thank you.
</details>

**Comment by twaik** [comment]
It looks like I can create keymap with such a snippet: 
<details>

```
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <xkbcommon/xkbcommon.h>
#include <unistd.h>

int main() {
    struct xkb_context *ctx;
    struct xkb_keymap *keymap;
    char buf[4096] = {0};

    ctx = xkb_context_new(XKB_CONTEXT_NO_ENVIRONMENT_NAMES);
    if (!ctx) {
        fprintf(stderr, "Cannot create xkb context\n");
        return EXIT_FAILURE;
    }

    read(0, buf, sizeof(buf)/sizeof(buf[0]) - 1);
    buf[strlen(buf) - 1] = 0;
    printf("buffer: \n%.*s\nEOF\n", (int) strlen(buf), buf);

    keymap = xkb_keymap_new_from_buffer(ctx, buf, strlen(buf), 1, 0);
    if (!keymap) {
        fprintf(stderr, "Cannot create keymap from buffer\n");
        xkb_context_unref(ctx);
        return EXIT_FAILURE;
    }

    printf("Keymap created successfully from buffer\n");

    xkb_keymap_unref(keymap);
    xkb_context_unref(ctx);
    return EXIT_SUCCESS;
}
```
</details>

But how to get string in XKM format to export it to X server?

**Comment by wismill** [comment]
It is [not currently implemented](https://xkbcommon.org/doc/current/md_doc_compat.html).

I do not think there is any plan to implement it either, as the current support of X11 is only for _consuming_ keyboard events, not handling layout configuration. `xkbcomp` remains the reference tool to load layout configuration into X servers.

You may want to have a look at [xkbcomp’s repository](https://gitlab.freedesktop.org/xorg/app/xkbcomp) for further info on the XKM format.

**Comment by wismill** [comment]
Closing, as there is no feedback. Feel free to reopen if you have any new information.

**Comment by twaik** [comment]
Maybe it will be better to ask for libxkbcommon support in X.org project. In this case XKM format parser is not needed (I mean in X server).

**Comment by wismill** [comment]
The X server is in maintenance mode.
