### ISSUE TITLE
Question about XkbToControl results

### ISSUE THREAD

**Issue by hyoputer** [xkbcommon/libxkbcommon#368]
Hi, I have a question about the control modifier in [XkbToControl](https://github.com/xkbcommon/libxkbcommon/blob/master/src/state.c#L906).

When [xkb_state_key_get_utf32](https://github.com/xkbcommon/libxkbcommon/blob/master/src/state.c#L1047) is called and the control key is pressed, the return value would be modified by the function above. However, I couldn't find any documentation about the rules. Actually, I did come across information about the [control modifiers](https://www.x.org/releases/current/doc/kbproto/xkbproto.html#Interpreting_the_Control_Modifier), but I couldn't understand why the result is 0 when ctrl+2 is pressed. Could you please explain it to me?

**Comment by hyoputer** [comment]
Thank you for the explanation! This helped me a lot!
After reviewing the Wikipedia page you provided, I understand that Control + 2 is equivalent to Control + @. Does this mean the function "XkbToControl" should produce the same results in those cases?

**Comment by wismill** [comment]
Yes, this is my understanding. Documentation is scarce! It took me a while.

I do not know if this feature is much use these days, appart from some subset such as: `ctrl+c`, `ctrl+d`, etc.

I think it would be good to document it. @whot @bluetech explanations welcome!

**Comment by wismill** [comment]
Some findings that seem to validate my understanding:

- https://www.vt100.net/shuford/terminal/dec_keyboards_news.txt
  > On DEC VT-series terminals CTRL-3 gives escape.  No, there is NO ANSI
STANDARD for these key sequences!  They are all proprietary.  (The
VT200-series, though, does form an informal standard of sorts.)

  > CTRL-2 gives NUL, CTRL-4 gives FS, CTRL-5 gives GS, CTRL-6 gives RS,
  > CTRL-7 gives RS, and CTRL-8 gives US.  These are all on DEC terminals.

  While these sequences are not true for 7 and 8, they seem to give some origin.
- https://misc.openbsd.narkive.com/NvSWf6ax/which-key-shortcuts-are-safe-to-bind-and-some-q-s-about-history-and-os-diffs-re-ctrl-4-means
  
  In particular:
  > And I'll venture a guess why DEC added those combinations: In order
  to type ^[ ^\ ^] to produce the ESC, FS, GS characters, you need
  keys for [ \ ]. If you look at non-English keyboard layouts, you'll
  see that the corresponding keys have been re-purposed for other
  characters. In the old days of national ASCII variants, even the
  characters [ \ ] didn't exist in many national encodings. Later,
  when extended 8-bit character sets were introduced, [ \ ] were only
  made available in a secondary mapping reachable with an extra
  modifier key (AltGr or such). And that's the situation right into
  the present.

  > By contrast, combinations like ^3, ^4, ^5 were readily available on keyboards.
- [VT220: Table 3-5 Keys Used to Generate 7-Bit Control Characters](https://vt100.net/docs/vt220-rm/chapter3.html#T3-5)

**Comment by wismill** [comment]
I consider this question answered. Let's continue the discussion in the PR for the details.
