### ISSUE TITLE
Keysyms removed without prior deprecation

### ISSUE THREAD

**Issue by berolinux** [xkbcommon/libxkbcommon#403]
Commit 49690d936bf6cc6bf85058c1f0a545f0d5e37c77 removes various XKB_KEY_* defines that are still used, and have not been marked as deprecated before, in particular

```
/* extra dead elements for German T3 layout */
#define XKB_KEY_dead_lowline                  0xfe90
#define XKB_KEY_dead_aboveverticalline        0xfe91
#define XKB_KEY_dead_belowverticalline        0xfe92
#define XKB_KEY_dead_longsolidusoverlay       0xfe93
```

The commit message for this commit says it syncs with https://gitlab.freedesktop.org/xorg/proto/xorgproto/-/commit/1c8128d72df22843a2022576850bc5ab5e3a46ea which doesn't have anything to do with the 4 constants listed above, so possibly the removal was unintentional.

I've never seen a keyboard with those keys; but there is very commonly used code (such as Qt 6.6.0) that references those constants and gets broken by this.

**Comment by wismill** [comment]
We just redistribute `xorgproto` files. The commit of `xorgproto` references the version we use, not were they were removed.

Please read the [release notes](https://lists.freedesktop.org/archives/wayland-devel/2023-October/043121.html) for further information.

It is the responsibility of Qt to keep up to date with its dependencies. By the way it is already fixed, at least in the dev branch.
