### ISSUE TITLE
User help

### ISSUE THREAD

**Issue by FrolovRuslan1** [xkbcommon/libxkbcommon#409]
I want to write `xkb-switch`(it dont works correct)  for Wayland but when I want use _libxkbcommon_ it doesnt works correct i.e. layouts names isnt real (I have us, ru, but show only us)  so I had to use _libwayland_.  I can get `xkb_keymap` use _libwayland_ but I cant change layout to next index(I dont know how or _libxkbcommon_ doesnt work). My list layout function works correct and layouts names is real.(I have us, ru,and show us, ru)
It doesnt work:
```
xkb_state_update_key(state->state, XKB_KEY_ISO_Next_Group, XKB_KEY_DOWN);
xkb_state_update_key(state->state, XKB_KEY_ISO_Next_Group, XKB_KEY_UP);
```

**Comment by wismill** [comment]
Where does the `state` come from? If I understands your intention correctly, you would need to update the state of the _compositor_, not the local state of in your app. I do not think this is possible in general.

Could you provide some pointer to your current code?

**Comment by wismill** [comment]
The line 
```c
state.keymap = xkb_keymap_new_from_names(state.context, NULL, XKB_KEYMAP_COMPILE_NO_FLAGS);
```
is useless because you are loading the library default keymap (`NULL`). So you will always get the same result with after “It prints keyboard layout only via xkbcommon”.

Then in order to change the layout, you should:
- use a dedicated Wayland protocol (not sure that this one exists)
- use Wayland composer-specific API
- simulate a keypress via e.g. uinput or libei. You must ensure it will trigger the correct keysym in the current layout though.

**Comment by wismill** [comment]
Please have a look at the [Quick guide](https://xkbcommon.org/doc/current/md_doc_2quick-guide.html).

**Comment by FrolovRuslan1** [comment]
"is useless because you are loading the library default keymap (NULL)." 
So why my default keymap doesnt have ru, us layout, if its are exist ? 

"simulate a keypress via e.g. uinput or libei. You must ensure it will trigger the correct keysym in the current layout though." 
Is xkbcommon has tools for switch keyboard layout for doesnt use "simulate a keypress" ?

**Comment by wismill** [comment]
> So why my default keymap doesnt have ru, us layout, if its are exist ?

Default __library__ keymap config. It means hardcoded.

>  Is xkbcommon has tools for switch keyboard layout for doesnt use "simulate a keypress" ?

No. Please read the documentation.
