### ISSUE TITLE
Does libxkbcommon can support Android

### ISSUE THREAD

**Issue by xueshenan** [xkbcommon/libxkbcommon#411]
Hi everybody,
     I want to port weston to Android platform. And the weston is dependency on libxkbcommon, so I just compile libxkbcommon with Android ndk. But when the weston is launch, the xkbcommon will print the following error message:
``` shell
./release_android/bin/weston -B drm-backend.so                                                                                                         
Date: 2023-09-25 GMT
[04:39:49.818] weston 11.0.1
               https://wayland.freedesktop.org
               Bug reports to: https://gitlab.freedesktop.org/wayland/weston/issues/
               Build: 11.0.1+
[04:39:49.818] Command line: ./release_android/bin/weston -B drm-backend.so
[04:39:49.818] OS: Linux, 5.4.210-android12-9-g964a40699d48, #17 SMP PREEMPT Wed Nov 15 17:15:39 CST 2023, aarch64
[04:39:49.818] Flight recorder: enabled
[04:39:49.818] Starting with no config file.
xkbcommon: ERROR: failed to add default include path /usr/share/X11/xkb
[04:39:49.818] failed to create XKB context
```

So my questison is does the libxkbcommon can support Android?

**Comment by whot** [comment]
You'll need to install [xkeyboard-config](https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/) which provides the data files that should be in the directory xkbcommon tries to parse. Right now it looks like you don't have those which is the cause for this error.
