### ISSUE TITLE
After install, qt, slicer, cmake graphical interface can not use the keyboard, when using the keyboard input, the software will directly flash back.

### ISSUE THREAD

**Issue by ThreeStones1029** [xkbcommon/libxkbcommon#412]
I ran into this problem after installing and compiling the QT font library. When I finished installing it, I found that Qt couldn't use the keyboard. At the same time, I also found that cmake and slicer software can not use the keyboard, if I use the keyboard input, it will crash. I was looking at the system logs and saw that it had something to do with the libxcbcommon library, so I was sure it was because I had it installed and compiled. What should I do?
I tried the restart method, which brought more serious consequences, my gdm3 managed GUI couldn't open, and I had to replace the unity desktop managed by lightdm. However, the same problem still occurs when I reinstall these three software.
Has anyone encountered this problem? I don't want to reinstall the system.
My system is ubuntu20.04 and the error message is as follows:
`SlicerApp-real[543151]: segfault at 4 ip 00007fe31c7c5fe8 sp 00007ffdd5ab6480 error 4 in libxkbcommon.so.0.0.0[7fe31c7ad000+1b000]
Dec  1 16:09:51 jjf-Precision-Tower-7810 kernel: [195132.210905] Code: 00 00 89 d2 48 8d 04 52 48 8b 44 c6 08 8b 50 18 23 78 08 85 d2 74 31 48 8b 40 20 83 ea 01 48 8d 14 92 48 8d 4c 90 14 0f 1f 00 <8b> 70 04 8b 50 08 49 89 c0 85 f6 74 04 85 d2 74 04 39 d7 74 0c 48
`

**Comment by ThreeStones1029** [comment]
I found a solution. Indeed, this error is due to compiling libxcbcommon.
Since we need sudo make install during the compilation process, this will change some Settings of our system, resulting in some software cannot be entered.
My solution was to recompile libxkbcommon-0.8.4.
After downloading the corresponding installer, unzip it, cd it to your root directory and run this
`./configure --disable-x11
make
sudo make install`
Then i find the problem is fixed!, it seems that the previous libxkbcommon does not match some libraries on my system (ubuntu20.04).
The problem that confused me for a week has finally been solved, and my cmake can finally use the keyboard.

**Comment by wismill** [comment]
Glad you sorted the installation out.
