### ISSUE TITLE
`xkb_keysym_to_utf8()` requires output buffer size to be at least 7, but it should be 5 

### ISSUE THREAD

**Issue by LocalSpook** [xkbcommon/libxkbcommon#418]
As I understand it, a size of 7 was needed when UTF-8 sequences could be up to 6 bytes long. Now that they're limited to 4, `xkb_keysym_to_utf8()`'s requirement should be reduced accordingly.

**Comment by wismill** [comment]
I agree. We just need max 4 bytes for the character plus 1 for the null character. I added a test for this in #414.

**Comment by wismill** [comment]
A bit of history:
- [rfc2044](https://datatracker.ietf.org/doc/html/rfc2044) (1996, up to 6 bytes), superseded by [rfc2279](https://datatracker.ietf.org/doc/html/rfc2279) (1998, up to 6 bytes), superseded by [rfc3629](https://datatracker.ietf.org/doc/html/rfc3629) (2003, up to 4 bytes).
- Wikipedia: [UTF-8 History](https://en.wikipedia.org/wiki/UTF-8#FSS-UTF)
