### ISSUE TITLE
keysym resolution fails under some locales

### ISSUE THREAD

**Issue by rtcm** [xkbcommon/libxkbcommon#42]
This bug was reported by a tr_TR.UTF-8 locale user: https://bugzilla.gnome.org/show_bug.cgi?id=774374 .

I found out that under this locale the strcasecmp() call in keysym.c:compare_by_name() doesn't work as expected and we fail to find some keysym names. For instance, this sample program:

```
#include <stdio.h>
#include <locale.h>
#include <xkbcommon/xkbcommon.h>

static void
print_keysym (const char *name)
{
  xkb_keysym_t keysym = xkb_keysym_from_name (name, XKB_KEYSYM_NO_FLAGS);
  printf ("0x%x\n", keysym);
}

int
main (int argc, char **argv)
{
  if (argc != 2)
    {
      printf ("usage: %s <keyname>\n", argv[0]);
      return 0;
    }

  print_keysym (argv[1]);

  setlocale(LC_ALL, "");

  print_keysym (argv[1]);

  return 0;
}
```

when executed like `LC_ALL=tr_TR.UTF-8 ./a.out i` yields
`0x69
0x0`

I guess this is a glibc/locale bug since the keysym names are all just ASCII strings, but maybe libxkbcommon should use a different way to do this that doesn't rely on locale specific behavior?

**Comment by piotrdrag** [comment]
A new release with this bugfix would be greatly appreciated by the Turkish community, who can't input their language's special characters in Fedora 25.

https://bugzilla.redhat.com/show_bug.cgi?id=1414493

**Comment by bluetech** [comment]
I'll release 0.7.1 tonight!

**Comment by piotrdrag** [comment]
Wow, that was super quick. Thank you kindly!

**Comment by bluetech** [comment]
Released now. Note that the relevant patch (b5586a6c4294b46eb23d1fc527ff63dcd27e23ac) should apply cleanly to whatever version Fedora is using if a backport is preferred.
