### ISSUE TITLE
symbol map fails with recent lld (aka broken test for -Wl,--version-script)

### ISSUE THREAD

**Issue by bapt** [xkbcommon/libxkbcommon#424]
with lld 1.17, linking with a symbol map which contains symbols which actually do not exists now result in an error, which means the test in meson.build to check if -Wl,--version-script works always fails. because it tries to use the general map file with "int main(void) {}".

Either it should be tested with an empty map file, or another strategy should be defined

Or something like the following patch: https://cgit.freebsd.org/ports/tree/x11/libxkbcommon/files/patch-meson.build should be used.

**Comment by whot** [comment]
To save us from having to reproduce this - which of the symbols doesn't exist? This may just be a typo/copy/paste error?

**Comment by bapt** [comment]
Sorry for the delay, the problem is not with the map file, but with the test in meson in create a binary with no symbols and apply the xkbcommon.map version script on it, which results in failure. I am surprised there is an actual need for this test at all

**Comment by whot** [comment]
Looks like this was added for #24 back when we still used autotools and then taken over to meson. A quick google points me to https://github.com/mesonbuild/meson/issues/3047 so meson doesn't appear to have native version-script support yet.

Your patch looks good on a first glance and appears to work locally on my F39 machine, mind filing a pull request for that?
