### ISSUE TITLE
Keymap file failed to load: us,mao,us-

### ISSUE THREAD

**Issue by jmlich** [xkbcommon/libxkbcommon#428]
@eragrostis have reported following issue to geotagging project. I believe it is issue of xkbcommon. Log and steps to reproduce are at
https://github.com/jmlich/geotagging/issues/45

**Comment by wismill** [comment]
`us-` is a typo. As for `mao`, it seems that it was [removed](https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/commit/9143edaf7102522ef1f15740cdbea24419a74002) in xkeyboard-config 2.40. You need to choose `nz` with variant `mao`.
