### ISSUE TITLE
Make check for pkgconfig(x11) and pkgconfig(xau) for --enable-x11 option

### ISSUE THREAD

**Issue by Zenitur** [xkbcommon/libxkbcommon#43]
I have tried to compile xkbcommon with --enable-x11. Configuring says error. When I added some dependencies, configuring complete. You need to make check for pkgconfig(x11) and pkgconfig(xau) if the option --enable-x11 enabled.
[build_log_plus_config_log.zip](https://github.com/xkbcommon/libxkbcommon/files/787288/build_log_plus_config_log.zip)

**Comment by bluetech** [comment]
xkbcommon does not require `x11` or `xau` (directly anyway), for `--enable-x11` it requires `xcb` and `xcb-xkb`. From the log it looks like you are missing `xcb-xkb`:

```
[   62s] configure: error: xkbcommon-x11 requires xcb-xkb >= 1.10 which was not found. You can disable X11 support with --disable-x11.
```

**Comment by Zenitur** [comment]
I'm sorry. I'd forgot to add pkgconfig(xau) in xcb SPEC file. Please close this bug.

**Comment by bluetech** [comment]
No problem :)
