### ISSUE TITLE
Aliases

### ISSUE THREAD

**Issue by oliviercailloux** [xkbcommon/libxkbcommon#433]
The file `xkbcommon-keysyms.h` [indicates](https://github.com/xkbcommon/libxkbcommon/blob/1034f272e427565a974f84fe62778ae9fd224899/include/xkbcommon/xkbcommon-keysyms.h#L104-L109): _Where several mnemonic names are defined for the same keysym in this file, all but the first one listed should be considered deprecated, unless the comment explicitly states the alias, e.g.:_
- _#define XKB_KEY_dead_tilde            0xfe53_
- _#define XKB_KEY_dead_perispomeni      0xfe53 // alias for dead_tilde_.

In fact, for almost all keysyms to which more than one mnemonic name corresponds, all but one of those mnemonic names are explicitly marked as deprecated or as being an alias. For example, about [keysym 0x27](https://github.com/xkbcommon/libxkbcommon/blob/1034f272e427565a974f84fe62778ae9fd224899/include/xkbcommon/xkbcommon-keysyms.h#L569-L570):
- _#define XKB_KEY_apostrophe                    0x0027  /* U+0027 APOSTROPHE */_
- _#define XKB_KEY_quoteright                    0x0027  /* deprecated */_;

or about [keysym 0xff55](https://github.com/xkbcommon/libxkbcommon/blob/1034f272e427565a974f84fe62778ae9fd224899/include/xkbcommon/xkbcommon-keysyms.h#L204-L205):
- _#define XKB_KEY_Prior                         0xff55  /* Prior, previous */_
- _#define XKB_KEY_Page_Up                       0xff55  /* deprecated alias for Prior */_.

The only exceptions are about the keysyms 0xff37, 0xff3c, 0xff3d and 0xff3e. 

The mnemonic names associated to [keysym 0xff37](https://github.com/xkbcommon/libxkbcommon/blob/1034f272e427565a974f84fe62778ae9fd224899/include/xkbcommon/xkbcommon-keysyms.h#L167-L191) are:
- _#define XKB_KEY_Codeinput                     0xff37_
- _#define XKB_KEY_Kanji_Bangou                  0xff37  /* Codeinput */_
- _#define XKB_KEY_Hangul_Codeinput              0xff37  /* Hangul code input mode */_

The mnemonic names associated to keysym 0xff3c are:
- _#define XKB_KEY_SingleCandidate               0xff3c_
- _#define XKB_KEY_Hangul_SingleCandidate        0xff3c  /* Single candidate */_.

The mnemonic names associated to keysym 0xff3d are:
- _#define XKB_KEY_MultipleCandidate             0xff3d_
- _#define XKB_KEY_Zen_Koho                      0xff3d  /* Multiple/All Candidate(s) */_
- _#define XKB_KEY_Hangul_MultipleCandidate      0xff3d  /* Multiple candidate */_.

The mnemonic names associated to keysym 0xff3e are:
- _#define XKB_KEY_PreviousCandidate             0xff3e_
- _#define XKB_KEY_Mae_Koho                      0xff3e  /* Previous Candidate */_
- _#define XKB_KEY_Hangul_PreviousCandidate      0xff3e  /* Previous candidate */_.

Is the intent to make the mnemonic names `Kanji_Bangou`, `Hangul_Codeinput`, `Hangul_SingleCandidate`, `Zen_Koho`, `Hangul_MultipleCandidate`, `Mae_Koho` and `Hangul_PreviousCandidate` aliases (as for keysym 0xfe53), or deprecated aliases (as for keysym 0xff55)? In other words, for example, should the comment “Multiple/All Candidate(s)” be interpreted as explicitly stating the alias? Either way, could you perhaps consider to write the decision explicitly in the comment, as done for other keysyms corresponding to several mnemonic names? This would ease parsing and avoid possible hesitation. That the deprecation or aliasing decision is explicitly indicated for all keysyms but just those four ones is a bit puzzling.

**Comment by wismill** [comment]
Good catch! The explicit deprecation/alias work was done in [xorgproto](https://gitlab.freedesktop.org/xorg/proto/xorgproto/-/merge_requests/80). I guess I missed some.

The rule you cited still applies: by default, the aliases are deprecated.

By the way, I am curious to know how you use this information.

**Comment by oliviercailloux** [comment]
> by default, the aliases are deprecated.

Note that the “default” rule (“should be considered deprecated, unless the comment explicitly states the alias”) is slightly ambiguous, IMHO: in the line `#define XKB_KEY_Kanji_Bangou 0xff37 /* Codeinput */`, one could consider that the comment does explicitly state the alias.

I guess that the default rule should be interpreted as “unless the comment explicitly states the alias exactly by matching the following pattern”, or something similar, but that was not clear to me so far.

That said, once these four keysyms are corrected, no more ambiguity should arise.

**Comment by oliviercailloux** [comment]
> I am curious to know how you use this information

I am writing a parser for a project about drawing keyboard maps.

**Comment by oliviercailloux** [comment]
If I may use this opportunity for a clarification, is there really a difference between the case of `quoteright` which is just “deprecated” and `Page_Up` which is a “deprecated alias”, or are any mnemonic names that do not come first in the file about a given keysym aliases (in which case `quoteright` also is a “deprecated alias”)?

**Comment by wismill** [comment]
> I guess that the default rule should be interpreted as “unless the comment explicitly states the alias exactly by matching the following pattern”, or something similar, but that was not clear to me so far.

Yes, that is the intent.

> is there really a difference between the case of quoteright which is just “deprecated” and Page_Up which is a “deprecated alias”

No, deprecated aliases should have the second pattern in their comment. I see why it looks confusing.

> are any mnemonic names that do not come first in the file about a given keysym aliases (in which case quoteright also is a “deprecated alias”)?

So, to sum up:
- By definition, any name with the same keysym value than a previous name is an alias to the first name with this keysym value in the file (i.e., the _canonical_ name).
- Unless an alias has a comment that follows the pattern “alias for …”, _without_ “deprecated”, it is deprecated, regardless if it has “deprecated” in its comment or not.
- A name with “deprecated” in its comment is explicitly deprecated, regardless if it is an alias or not.
- Any other alias is deprecated.

My intent in the MR I linked was to make all deprecations _explicit_. But there may be still some missing/malformed comments, as you discovered.

Also, for the non-deprecated aliases, do you have a better suggestion for their comment?

**Comment by wismill** [comment]
> I am writing a parser for a project about drawing keyboard maps.

Interesting! Why parsing the keysyms header and not using the xkbcommon API?

**Comment by oliviercailloux** [comment]
> So, to sum up:

Thanks a lot, that is now very clear.

> My intent in the MR I linked was to make all deprecations _explicit_. But there may be still some missing/malformed comments, as you discovered.
> 
> Also, for the non-deprecated aliases, do you have a better suggestion for their comment?

IMHO all the redundant comments (meaning, those that can be deduced by the general rule) should be removed as they are more confusing than helpful. The general rule makes it clear what is a canonical or an alias mnemonic name, no need of comment for that. Aliases should have as comment either _/* deprecated */_ or nothing.

> Why parsing the keysyms header and not using the xkbcommon API?

In hindsight, not sure it was the wisest choice. (But now my parser is mostly done so I think that I’ll stick to this approach for now.) I thought that the API approach may reveal hard to make it portable (eg not clear to me how to run the resulting program on Windows without making it more difficult to install for my users), and my program is in Java so (slight) supplementary trouble in using a C API. Also, I was interested in understanding the raw data that the API comes from (just out of curiosity).

**Comment by oliviercailloux** [comment]
While we’re there, I’d like to raise another point which I suspect is an oversight. Please tell me if you prefer that I open a new issue on [xorgproto](https://gitlab.freedesktop.org/xorg/proto/xorgproto/-/issues) for this.

Most UCPs are associated to at most one mnemonic name, if disregarding the ones marked as “more specific” (using angle brackets) such as [_KP_ADD_](https://github.com/xkbcommon/libxkbcommon/blob/1034f272e427565a974f84fe62778ae9fd224899/include/xkbcommon/xkbcommon-keysyms.h#L253) or as deprecated. There are only two exceptions to this rule: _U+221A SQUARE ROOT_, which is associated to [_radical_](https://github.com/xkbcommon/libxkbcommon/blob/1034f272e427565a974f84fe62778ae9fd224899/include/xkbcommon/xkbcommon-keysyms.h#L1380) and [_squareroot_](https://github.com/xkbcommon/libxkbcommon/blob/1034f272e427565a974f84fe62778ae9fd224899/include/xkbcommon/xkbcommon-keysyms.h#L2112); and _U+2202 PARTIAL DIFFERENTIAL_, which is associated to [_partialderivative_](https://github.com/xkbcommon/libxkbcommon/blob/1034f272e427565a974f84fe62778ae9fd224899/include/xkbcommon/xkbcommon-keysyms.h#L1387) and [_partdifferential_](https://github.com/xkbcommon/libxkbcommon/blob/1034f272e427565a974f84fe62778ae9fd224899/include/xkbcommon/xkbcommon-keysyms.h#L2107). Shouldn’t one of each of these pairs be marked as deprecated?

**Comment by oliviercailloux** [comment]
> Shouldn’t one of each of these pairs be marked as deprecated?

Sorry to bug you again, but please tell me if you have a quick answer to that question, as this will permit me to move on with my parser.

**Comment by wismill** [comment]
I have no idea. You may try to bissect the original file in xorgproto. I would say go for the ones in the Unicode range, as there is no risk of ambiguity, if any.

**Comment by wismill** [comment]
I got curious: theses names were added 18 years ago in [commit eaffdc0d593b94d9036033911535371e73698573 ](https://gitlab.freedesktop.org/xorg/proto/xorgproto/-/commit/eaffdc0d593b94d9036033911535371e73698573). The corresponding bug report is [4688](https://bugs.freedesktop.org/show_bug.cgi?id=4688).

There is not much context. I would say Unicode keysyms should be preferred over the legacy keysyms, but let’s be honest: when you edit a file, having a human-readable name is much easier. For characters in the ASCII range, there is no choice: one must use the legacy keysyms.

**Comment by oliviercailloux** [comment]
Thanks a lot for having digged this far! But, I am not sure that I understand your answer completely.
My question is, why is there both
`#define XKB_KEY_radical                       0x08d6  /* U+221A SQUARE ROOT */`
and
`#define XKB_KEY_squareroot                 0x100221a  /* U+221A SQUARE ROOT */` 
(and similarly for [partialderivative](https://github.com/xkbcommon/libxkbcommon/blob/1034f272e427565a974f84fe62778ae9fd224899/include/xkbcommon/xkbcommon-keysyms.h#L1387) and [partdifferential](https://github.com/xkbcommon/libxkbcommon/blob/1034f272e427565a974f84fe62778ae9fd224899/include/xkbcommon/xkbcommon-keysyms.h#L2107)).

I understand that the answer is something like “for some legacy reason that has been lost in time and space”, but I do not understand the further comment about preferring Unicode keysyms over legacy keysyms that would be human-readable.
Both “radical” and “squareroot” are human-readable, aren’t them? Which one of these two do you refer to as being the Unicode keysym, if any?

It still seems to me (even more so now that it appears that probably the supplementary one has been added as part of a set, without, probably, considering that it was creating a duplicate) that one of these two could be declared as being deprecated, as having both does not seem to serve any purpose, so as to guarantee that UCPs are associated to at most one mnemonic name (if disregarding the ones marked as “more specific” or as deprecated), which I think could simplify some use cases and clarify the key map concept.

**Comment by wismill** [comment]
> My question is, why is there both [...]
> without, probably, realising at the time that it was creating a duplicate

That would be my guess.

>  but I do not understand the further comment about preferring Unicode keysyms over legacy keysyms that would be human-readable.

Ok, Unicode keysyms refers to the keysyms in the Unicode range 0x01000100 to 0x0110ffff, but I also used it for the special names `Uxxxx` for this range.

My reasoning was:
> On one hand for this _specific_ case I would prefer the Unicode _range_, because it has no ambiguity. So I would choose e.g. `squareroot` over `radical`. On the other hand, in the general case, I would not go 100% Unicode range: e.g. I would prefer `Amacron` (legacy, `0x03c0`) over `U0100` (Unicode, `0x01000100`), because the latter has no human readable name.)

In the end you should get the same characters when typing. Note that it will affect Compose files and it _may_ affect keyboard shortcuts though.

So the safest choice is: use (non-deprecated) legacy keysyms when possible else use Unicode keysyms.

**Comment by oliviercailloux** [comment]
> for this _specific_ case I would prefer the Unicode _range_, because it has no ambiguity. So I would choose e.g. `squareroot` over `radical`

Thanks again. The recommendation is now very clear. 

I stick to my suggestion to mark `XKB_KEY_radical` and `XKB_KEY_partialderivative` as deprecated, to make this recommendation clearer, but at least now I have a principled way of choosing a single mnemonic (at most) for a given UCP.

**Comment by oliviercailloux** [comment]
It might also be slightly ambiguous how to treat `#define XKB_KEY_SunPrint_Screen           0x0000ff61  /* Same as XKB_KEY_Print */` (and other lines with comments starting with “Same as”). According to the rule laid out here above, it is a deprecated alias; though the comment might suggest that it is just an alias.

**Comment by wismill** [comment]
I am going to close this, as it is actually an upstream issue for [`xorgproto`](https://gitlab.freedesktop.org/xorg/proto/xorgproto). Feel free to propose a MR there.
