### ISSUE TITLE
question: how to map from xcb key press/release event state field to xkb_mod_mask_t

### ISSUE THREAD

**Issue by wez** [xkbcommon/libxkbcommon#437]
To deal with some timing issues in certain keyboard automation or high speed keyboard input scenarios when mixing an IME with xkb, my application is following the suggestion in https://github.com/ibus/ibus/issues/2600#issuecomment-1904396417 to compute and call update_mask with the state supplied in the incoming X event.

At the moment I am literally passing these u32 value straight from the X event and having those take precedence over the the parameters values last provided in an UpdateState X event.

This seems to be working well for the most part: automated key events (either via `xdotool`, or programmable mechanical keyboards) now appear to be handled correctly.

Is this actually valid? Are the key/button mask bits in the key press/release event `state` field actually directly compatible with the `xkb_mod_mask_t` in this context, or should I be taking additional steps to decode and map the values?  Or just mask off some bits? 

Some background/context:
* https://github.com/ibus/ibus/issues/2600#issuecomment-1904396417
* https://github.com/fcitx/fcitx5/issues/893

**Comment by wismill** [comment]
@wez check the [`interactive-x11`](https://github.com/xkbcommon/libxkbcommon/blob/e7570bcb78a48c0e3fb48087991a85af95943e98/tools/interactive-x11.c#L236) tool for a complete example of using `xcb` with `xkbcommon`: it passes `xcb_xkb_state_notify_event_t` masks to `xkb_state_update_mask`.

**Comment by bluetech** [comment]
> Is this actually valid? Are the key/button mask bits in the key press/release event state field actually directly compatible with the xkb_mod_mask_t in this context, or should I be taking additional steps to decode and map the values? Or just mask off some bits?

Yes, this is [documented](https://xkbcommon.org/doc/current/group__x11.html) and if we break it, it will be considered a breaking change.
