### ISSUE TITLE
Weird <LFSH> error

### ISSUE THREAD

**Issue by fbruetting** [xkbcommon/libxkbcommon#44]
After setting my keybindings according to this thread [1], I often see the following error in the terminal, when I start programs:

```xkbcommon: ERROR: Key "<LFSH>" added to modifier map for multiple modifiers; Using Lock, ignoring Shift```

I'm using Fedora 26. This error appeared already some time ago and with setting my settings back and reset them, the errors disappeared. But what's even more strange is, that this influences applications so the don't run properly anymore. In Geary I have to enter my passwords repeatedly as the password popup reappears every time I enter my password, and Lollypop is completely responsiveless. This was also the case when I encountered this bug before, but this time, setting back my keyboard settings doesn't improve the situation.

If you need more information, I'll try to help!

[1] https://bugzilla.gnome.org/show_bug.cgi?id=777723

**Comment by bluetech** [comment]
Yes, these errors can be annoying. I will need some more info:

- Do you use Xorg or Wayland? (if you are using Gnome, you can choose this in the login page).
- Which command (for example) are you running which emits this message?
- Which version of the `xkeyboard-config` do you use?
- Which keyboard layout/RMLVO do you use? If you are using Gnome, that means which "Input Sources", and if you are using the "Tweak Tool" which non-default "Typing" options you use.

Also, predicting the future, I think I will need to ask you to compile a C program to dump the keyboard map. If you don't know how to do that, let me know :)

**Comment by fbruetting** [comment]
I use Wayland, xkeyboard-config 2.20, keyboard layout "Neo 2" (which as like Dvorak for German), and I made no changes to the tweak tool input options.

I started for example lollypop and Geary through the command line. Compiling is no problem at all.

**Comment by bluetech** [comment]
Ha, neo. This is an issue in the keymap: https://bugs.freedesktop.org/show_bug.cgi?id=30980. The description by Stephan Hilb there is correct.

I would suggest you ignore the error message until the keymap is fixed. If it bothers you, you can reduce xkbcommon's log level by settings an environment variable: `export XKB_LOG_LEVEL=critical` (the default is `error`).

**Comment by fbruetting** [comment]
I really don't understand these internals, but asked for fixing it as a reminder. So there is no fault in xkbcommon?

**Comment by bluetech** [comment]
I am sure xkbcommon has many faults, but at least this error message is not one of them; it comes from the keymap, as described by Stephan Hilb in the freedesktop bug. I will also reply there, so as not to split the discussion.

**Comment by dimitris-triantafyllidis** [comment]
> I am sure xkbcommon has many faults, but at least this error message is not one of them; it comes from the keymap, as described by Stephan Hilb in the freedesktop bug. I will also reply there, so as not to split the discussion.

I am getting this error with the option `shift:both_capslock` if I do
```
xkbcomp -xkb $DISPLAY xkbmap
xkbcomp -w 0 xkbmap $DISPLAY

```
, having previously run the following during the startup of Xorg / i3
```
setxkbmap -layout "us,gr" \
          -option "shift:both_capslock" \
          -option "compose:caps" \
          -option "grp:win_space_toggle" \
          -option "terminate:ctrl_alt_bksp"
```
In the file "xkbmap" there are the following two lines:
```
    modifier_map Lock { <LFSH> };
    modifier_map Shift { <RTSH> };
```
If I remove the first one, the error goes away but the behaviour is still the one intended with the option, at least with the few tries I performed.
