### ISSUE TITLE
no usable option to activate horizontal number keys on Azerty keyboard

### ISSUE THREAD

**Issue by joomlafun** [xkbcommon/libxkbcommon#451]
STEPS TO REPRODUCE
0° in option the keyboard menu have " caps lock toggles shift lock"
1. press on caps lock then press a number key on an Azerty keyboard

OBSERVED RESULT
This will  activate the horizontal number keys from the Azerty keyboard but will keep the "maintain shift key behavior"

EXPECTED RESULT
Should activate the horizontal number keys from the Azerty keyboard(not numlock) without having a "maintain Shift behaviour."
but in the current situation, if you forget to toggle off shift lock, then you click on your task bar and it duplicates an item, if you click on a mail in thunderbird, it add its to a selection, etc.

CONFIGURATION 
From the menu the caps lock key is configured either : 
![Screenshot_20240210_2124](https://github.com/xkbcommon/libxkbcommon/assets/63743077/05556145-7e4c-4c4f-ba73-9aacec9ef47f)

1°as caps lock behavior>caps lock toggles normal capitalization of alphabetic letters
2° caps lock toggles shift lock
If you use option 1, the numbers are not activated
If you use option 2, the numbers are activated but Caps then has a "maintain shift" behavior activated too

--> I think there should be a 3rd option to activate Caps lock without having the "maintain shift behaviors" in applications

SOFTWARE/OS VERSIONS
Linux/KDE Plasma:  kubuntu 23.10
(available in About System)
KDE Plasma Version: 5.27.8
KDE Frameworks Version: 5.110.0
Qt Version: 5.15.10

**Comment by wismill** [comment]
Please report to [`xkeyboard-config` project](https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config).

**Comment by joomlafun** [comment]
allright https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/issues/446
