### ISSUE TITLE
! include line in rules file does not require a newline

### ISSUE THREAD

**Issue by dottedmag** [xkbcommon/libxkbcommon#452]
I have noticed that rules file parser is pretty lenient about !include files. In particular, it does not require a newline after the include, so the following rules file is parsed without errors:
```
! include %S/inc-dst-simple ! include %S/inc-dst-simple ! layout = symbols
```
I guess this is an oversight, and nobody relies on this?

**Comment by whot** [comment]
> I guess this is an oversight, and nobody relies on this?

definitely an oversight, yes, thanks for finding this
