### ISSUE TITLE
Set Caps Lock to non-toggling without assigning it to Shift key, or make "last used layout" shortcut

### ISSUE THREAD

**Issue by Akselmo** [xkbcommon/libxkbcommon#464]
Hi there, I hope this is the right place.

I tried to fix this bug for keyboard shortcut handling for kwin: https://bugs.kde.org/show_bug.cgi?id=478208

In short, Caps Lock gets toggled when it's used as a shortcut for the "last used keyboard layout."

Now this is all expected, since XKB doesn't seem to have it's own option/rule for it. (Excuse my confusion with the terminology here).

I found out a way to make it happen using the compat file settings, like modifying `/usr/share/X11/xkb/compat/caps` by changing `LockMods` to `SetMods`. 

Meanwhile I could make something that does that behind the scenes for the user, I would much prefer for something that doesn't change random files, but can be directly toggled with something like `xmodmap` or other similar tool, without needing root access. Something that is handled by XKB system, instead of modifying a random file.

Is something like this possible already, or does it need implementation here? (Or somewhere else if I am in completely wrong place..)

Thanks!

**Comment by wismill** [comment]
Thank you for your report.

Since you use a setting in Plasma that may change the `CapsLock` key beahvior, we need to first investigate what it does.

Could you open a terminal, run the following, press the `CapsLock` key and report the output? A blank window should open, keep it focused while typing, then exit using `ESC` key.

```bash
# NOTE: You may need to install `libxkbcommon-tools` package
# If running X11 session
xkbcli interactive-x11
# If running Wayland session
xkbcli interactive-wayland
```

**Comment by Akselmo** [comment]
Here's the output

```sh
> xkbcli interactive-x11
keycode [ CAPS ] keysyms [ Caps_Lock        ] unicode [   ] layout [ English (US, intl., AltGr Unicode combining) (0) ] level [ 0 ] mods [ ] leds [ ] 
keycode [ CAPS ] keysyms [ Caps_Lock        ] unicode [   ] layout [ English (US, intl., AltGr Unicode combining) (0) ] level [ 0 ] mods [ Lock ] leds [ Caps Lock ] 
keycode [ ESC  ] keysyms [ Escape           ] unicode [ U+001B ] layout [ English (US, intl., AltGr Unicode combining) (0) ] level [ 0 ] mods [ ] leds [ ] 

```

As a side note:

I am on wayland session but interestingly only `xkbcli interactive-x11` works, with `xkbcli interactive-wayland` command i get `Command 'interactive-wayland' is not available`

**Comment by wismill** [comment]
Could you type some letters after `Caps` and before `Esc` to check that the layout actually switched? If so you should have a different name after `layout` in the output. But it may be an issue with `interactive-x11` on Wayland.

>  Forgot to mention I am not using the compat setting at the moment. Do you need me to enable that first?

No, we need the original setup with the “bug”.

> I am on wayland session but interestingly only `xkbcli interactive-x11` works, with `xkbcli interactive-wayland` command i get `Command 'interactive-wayland' is not available`

I forget to ask: what `xkbcli --version` gives you? We do need `interactive-wayland` to get correct results.

**Comment by Akselmo** [comment]
> Could you type some letters after `Caps` and before `Esc` to check that the layout actually switched? If so you should have a different name after `layout` in the output. But it may be an issue with `interactive-x11` on Wayland.

Using the capslock here to switch between the last keyboard layout, sorry I also forgot to use that previously.

```
akseli ❲~❳
> xkbcli interactive-x11
keycode [ AC01 ] keysyms [ a                ] unicode [ a ] layout [ English (US, intl., AltGr Unicode combining) (0) ] level [ 0 ] mods [ ] leds [ ] 
keycode [ AB05 ] keysyms [ b                ] unicode [ b ] layout [ English (US, intl., AltGr Unicode combining) (0) ] level [ 0 ] mods [ ] leds [ ] 
keycode [ AB03 ] keysyms [ c                ] unicode [ c ] layout [ English (US, intl., AltGr Unicode combining) (0) ] level [ 0 ] mods [ ] leds [ ] 
keycode [ AC01 ] keysyms [ A                ] unicode [ A ] layout [ Finnish (1) ] level [ 1 ] mods [ -Lock ] leds [ Caps Lock Group 2 ] 
keycode [ AB05 ] keysyms [ B                ] unicode [ B ] layout [ English (US, intl., AltGr Unicode combining) (0) ] level [ 1 ] mods [ -Lock ] leds [ Caps Lock Group 2 ] 
keycode [ AB03 ] keysyms [ C                ] unicode [ C ] layout [ Finnish (1) ] level [ 1 ] mods [ -Lock ] leds [ Caps Lock Group 2 ] 
keycode [ AC03 ] keysyms [ D                ] unicode [ D ] layout [ English (US, intl., AltGr Unicode combining) (0) ] level [ 1 ] mods [ -Lock ] leds [ Caps Lock Group 2 ] 
keycode [ ESC  ] keysyms [ Escape           ] unicode [ U+001B ] layout [ English (US, intl., AltGr Unicode combining) (0) ] level [ 0 ] mods [ ] leds [ ] 

```


> I forget to ask: what `xkbcli --version` gives you? We do need `interactive-wayland` to get correct results.

```
> xkbcli --version
1.6.0
```

**Comment by wismill** [comment]
You seem to have a packaging issue with `libxkbcommon-tools`, because you should have `xkbcli interactive-wayland` available. Maybe report it to your distribution? Meanwhile you may build `xkbcommon` from source with Wayland support.

How many layouts do you use? You may be interested to check the tab advanced options and look for “group”, then choose one of the options with Caps. Try it after _disabling_ the Caps shortcut.

**Comment by Akselmo** [comment]
>  Maybe report it to your distribution?

Yeah, will do. I am using Fedora 39 KDE for the record.

> How many layouts do you use?

For testing this I use two layouts. However, the user who sent the bug report to us previously uses three. I know you can use capslock in the "Switching to another layout" but the problem was with the "Last used" shortcut, which switches between the last two used layouts.

For this we would need something that allows us binding capslock without toggling it, since its set through our own shortcut system, due to XKB not providing a "Switch to last used layout" shortcut.

So, to me, solution is either:
1. XKB provides a shortcut group for "Switch to last used keyboard layout" 
2. XKB provides a setting for Caps lock behavior, that makes Caps Lock act like shift key, without remapping it to shift key. Basically, something easy to use for the compat setting without having to modify a file. (And if there is already one, I'd love to know!)

Now I understand this is very niche usecase and likely very low priority. But any help regarding this would be appreciated.

Sorry if I haven't been clear enough previously. :sweat_smile:

**Comment by wismill** [comment]
> For testing this I use two layouts. However, the user who sent the bug report to us previously uses three. I know you can use capslock in the "Switching to another layout" but the problem was with the "Last used" shortcut, which switches between the last two used layouts.

Thus my question.

> 1. XKB provides a shortcut group for "Switch to last used keyboard layout"

Note that XKB is first a protocol, but is also confused with its implementations (xkbcommon is one of them) and the keyboard configuration database ([`xkeyboard-config`](https://gitlab.freedesktop.org/xkeyboard-config) project). Such proposal would belong to xkeyboard-config, but there is no way to configure `LockGroup` to “last _used_ group”.

> 2. XKB provides a setting for Caps lock behavior, that makes Caps Lock act like shift key, without remapping it to shift key. 

I think this is a bad idea, because you may have to do the same if e.g. someone decide to use `NumLock` or any other keysym/mod that lock a component of the keyboard state. Anyway, such proposal belongs to xkeyboard-config.

I think the proper general solution would be:
- Plasma handle modifiers-only shortcuts without triggering locks
- Fix #310

**Comment by Akselmo** [comment]
Understood. :smile: 

> Plasma handle modifiers-only shortcuts without triggering locks

I think this is good way to do it, and it may be a bug in there after all. I'll ask around if there is something like this already implemented. 

Thanks for the help! I'll update this issue if I have any further questions.

**Comment by wismill** [comment]
I’ll close it for now, do not hesitate to re-open if you have some news, but please consider:
- Use relevant previous issues in this repo.
- Posting to `xkeyboard-config` for XKB config file modifications.
