### ISSUE TITLE
support multiple actions for a key per level

### ISSUE THREAD

**Issue by bam80** [xkbcommon/libxkbcommon#486]
Good idea! I read your comment on `xkeyboard-config`: we should check multiple actions per level too. Probably another MR.

_Originally posted by @wismill in https://github.com/xkbcommon/libxkbcommon/pull/421#pullrequestreview-1788284256_
            
              Actually multiple actions per level is not currently supported by the parser: not in symbols nor in compatibility files.

_Originally posted by @wismill in https://github.com/xkbcommon/libxkbcommon/issues/421#issuecomment-1870240328_

Still, could we implement one?

Original issue:
https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/issues/428

**Comment by wismill** [comment]
Working on it.

**Comment by wismill** [comment]
See #487 for the WIP. This is quite a big change, so please be patient.
