### ISSUE TITLE
Feature Request: Add Halmak Keyboard Layout

### ISSUE THREAD

**Issue by mateowoetam** [xkbcommon/libxkbcommon#495]
Hello,

I am writing to request the inclusion of the Halmak keyboard layout in `xibxkbcommon`. The Halmak layout is an optimized keyboard layout designed to improve typing efficiency, having some popularity. Implementation details for the Halmak layout in a Linux environment can be found in my example repository: [Halmak Linux Support](https://github.com/mateowoetam/halmaklinuxsupport).

The current implementation uses the identifier `zz` for the layout. However, I recommend using a more descriptive identifier, such as `hk`, to better reflect the Halmak name. This implementation also adds the Layout as a new language rather than a variant of one (like English) which I understand if you change.

Thank you for considering this addition.

**Comment by wismill** [comment]
You already opened a MR in xkeyboard-config, which is the correct place.
