### ISSUE TITLE
libxkbcommon doesn't compile anymore

### ISSUE THREAD

**Issue by jjardon** [xkbcommon/libxkbcommon#50]
../src/xkbcomp/parser.y:34:26: fatal error: xkbcomp-priv.h: No such file or directory
compilation terminated.
Makefile:1507: recipe for target 'src/xkbcomp/parser.lo' failed
make[1]: *** [src/xkbcomp/parser.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
In file included from ../src/xkbcomp/keywords.c:34:0:
../src/xkbcomp/parser-priv.h:33:20: fatal error: parser.h: No such file or directory
compilation terminated.
In file included from ../src/xkbcomp/scanner.c:25:0:
../src/xkbcomp/parser-priv.h:33:20: fatal error: parser.h: No such file or directory
compilation terminated.

Full logs:
http://build.gnome.org/continuous/buildmaster/builds/2017/07/31/29/build/log-libxkbcommon.txt

**Comment by fooishbar** [comment]
This is a result of d44ba481d7a2; I think parser-priv.h needs to include src/xkbcomp/parser.h rather than just parser.h. Though we should probably also rename compose's parser.h to something different. @bluetech?

**Comment by fooishbar** [comment]
Mind you, just having merged the Meson build will break Continuous differently. ;)

**Comment by bluetech** [comment]
@fooishbar The autotools build is still alive and well :)

My plan is to do a release this weekend announcing the meson build and urging to switch. Then, given it goes well -- xkbcommon can be built on various operating systems, and is integrated in various build systems, e.g. Qt, so you never know -- the release after that will remove the autotools build.

I don't know if Continuous supports meson? If it does, it would be nice if it could be the first to switch!

**Comment by jjardon** [comment]
Thanks for the quick fix!

BTW, continuous builds xkbcommon using meson now :)

**Comment by bluetech** [comment]
Cool, thanks @jjardon.

BTW, I noticed this commit https://git.gnome.org/browse/gnome-continuous/commit/?id=a3b583c5559f5e6102d2385bd933b1ee5fb7e9a2 which says "New build system for xkbcommon means new symbol version breakage.". Do you maybe know what this means? If there is any breakage, I'd like to fix it.

**Comment by jjardon** [comment]
@bluetech this is what happened (before to switcching to meson): http://build.gnome.org/continuous/buildmaster/builds/2017/08/01/12/build/log-lightsoff.txt

**Comment by bluetech** [comment]
Oh, that's definitely a regression, for some reason (probably one of my recent changes) the symbol versioning stopped working.

I apologize in advance that fixing it will probably break Continuous again though!
