### ISSUE TITLE
Add support for KEY_ROTATE_LOCK_TOGGLE

### ISSUE THREAD

**Issue by StefanBruens** [xkbcommon/libxkbcommon#55]
Modern convertible laptops typically use an accelerometer for automatic display rotation, and may have a hardware switch or button to turn on/off the automatic rotation.

Currently, there is a keycode for handling switches, SW_ROTATE_LOCK, but no keycode for buttons. A switch has distinct states, while for a button (which has press/release events) the state has to be tracked in software.

Proposed patch for adding this keycode, KEY_ROTATE_LOCK_TOGGLE (0x231), to the kernel:
https://patchwork.kernel.org/patch/10052039/

**Comment by bluetech** [comment]
The xkbcommon library itself does not need to be changed when new keycodes are added in the kernel. The needed mappings are defined in the xkeyboard-config project.

If you need to add a new keysym to correspond to the keysym, then xkbcommon does need to be updated. But we usually do it ourselves after a patch is sent to Xorg's kbproto repository.
