### ISSUE TITLE
document "augment, override, replace"  keywords

### ISSUE THREAD

**Issue by bam80** [xkbcommon/libxkbcommon#573]
> XKB has a bunch of merging machinery for this, with 3 different merge keywords `augment`, `override`, `replace`. 

_Originally posted by @bluetech in https://github.com/xkbcommon/libxkbcommon/pull/162#pullrequestreview-463822621_
            
Could we please [document](https://xkbcommon.org/doc/current/keymap-text-format-v1.html#autotoc_md24) these keywords?

Apparently, they could be present in different contexts.
I couldn't find any references to them in a wild.
Thanks.

**Comment by wismill** [comment]
At the beginning of the doc you linked there is a link to Ivan Pascal’s documentation. The best doc about the merge modes is [this page](https://web.archive.org/web/20190720032715/http://pascal.tsu.ru/en/xkb/gram-common.html#merge).

The behavior of the merge modes is not totally clear though; see #209.

**Comment by bam80** [comment]
That helped, thanks.
But that's on the Web Archive (which even doesn't open here easily), so eventually we would have to take over on the documentation, I think.

**Comment by wismill** [comment]
@bam80 Again, from the *beginning* of [the doc](https://xkbcommon.org/doc/current/keymap-text-format-v1.html):

> Due to the complexity of the format, this document is still *in construction*. Some additional resources are: […]

The doc is _**WIP**_ but this project is seriously undermanned. Feel free to file a MR to improve the doc. Please do not open further issues about topics already marked as TODO in the doc.
