### ISSUE TITLE
X11->Unicode range

### ISSUE THREAD

**Issue by andrecbarros** [xkbcommon/libxkbcommon#58]
There is a bug with Keysym to Unicode translation for values of Keysym > 0x01000000. The real range is a bit more strict than the code that deals with it on xkb_keysym_to_utf32 use.

To speed up the translations of Keysyms with values inside keysymtab, I suggest the use of range boundaries, like what you can find on my fork.

Best regards,
André

**Comment by bluetech** [comment]
Hi,

I am not clear on what the bug is. An example of the form "input: X, expected output: Y, actual output: Z" would help me understand.

**Comment by andrecbarros** [comment]
Enter a invalid keysym, like 0x0100001, it will be translated to 0x01, what is clearly wrong.

**Comment by andrecbarros** [comment]
About the speed up on using range boundaries, it is about 40%, may you want I can send some tests to you.

Best regards,
André

**Comment by bluetech** [comment]
I have two slightly conflicting sources on this.

The X11 protocol [here](https://www.x.org/releases/X11R7.7/doc/xproto/x11protocol.html#Unicode_KEYSYMs) says the following:

> Unicode KEYSYMs: These occupy the range #x01000100 to #x0110FFFF and represent the ISO 10646 / Unicode characters U+0100 to U+10FFFF, respectively. The numeric value of a Unicode KEYSYM is the Unicode position of the corresponding character plus #x01000000. In the interest of backwards compatibility, clients should be able to process both the Unicode KEYSYM and the Legacy KEYSYM for those characters where both exist.

This explicitly excludes the ASCII range from the Unicode-keysym range.

A comment in the file `src/keysym-utf.c` [here](https://github.com/xkbcommon/libxkbcommon/blob/b63196e91e7d78e88a9012f3f44152eeef5358cf/src/keysym-utf.c#L16) says:

```
 * We allow to represent any UCS character in the range U-00000000 to
 * U-00FFFFFF by a keysym value in the range 0x01000000 to 0x01ffffff.
 * This admittedly does not cover the entire 31-bit space of UCS, but
 * it does cover all of the characters up to U-10FFFF, which can be
 * represented by UTF-16, and more, and it is very unlikely that higher
 * UCS codes will ever be assigned by ISO. So to get Unicode character
 * U+ABCD you can directly use keysym 0x0100abcd.
```

The code performs the following which matches the comment above:

```c
uint32_t xkb_keysym_to_utf32(xkb_keysym_t keysym) {
...

/* also check for directly encoded 24-bit UCS characters */
if ((keysym & 0xff000000) == 0x01000000)
    return keysym & 0x00ffffff;

...
}
```

Do you propose to change the code to follow the X11 specification, or something different?

**Comment by andrecbarros** [comment]
Actually, currently valid Unicode code points are restrict to 0x000000 to 0x010FFFF (take a look on last spec).
Also, there is no easy mapping of Keysyms to control chars in the range 0x00 to 0x1f. The valid cases are already treated by current code.

**Comment by andrecbarros** [comment]
Also, any value like 0x0##FFFF with ## > 10 will be invalid in Unicode but accepted by current implementation.

**Comment by andrecbarros** [comment]
As a side note, I currently have an implementation that translate XML entity names to Unicode code points in C. I don't know if there is a "demand" for it but be able to treat them on libxkbcommon would be a plus for me.
The code is straightforward with slight optimized matching techniques, or so it seems to me, may someone find it somewhat pertinent I may push it on my fork.

**Comment by bluetech** [comment]
Let's leave performance optimizations aside for moment, we can discuss them afterwards.

Regarding the functional changes, what do you think about the following diff for fixing the bug?

```diff
diff --git a/src/keysym-utf.c b/src/keysym-utf.c
index 1ccfc0e..99f467e 100644
--- a/src/keysym-utf.c
+++ b/src/keysym-utf.c
@@ -881,9 +881,10 @@ xkb_keysym_to_utf32(xkb_keysym_t keysym)
         keysym == XKB_KEY_KP_Enter || keysym == XKB_KEY_KP_Equal)
         return keysym & 0x7f;
 
-    /* also check for directly encoded 24-bit UCS characters */
-    if ((keysym & 0xff000000) == 0x01000000)
-        return keysym & 0x00ffffff;
+    /* also check for directly encoded Unicode keysyms */
+    if (0x01000100 <= keysym && keysym <= 0x0110FFFF) {
+        return keysym - 0x01000000;
+    }
 
     /* search main table */
     return bin_search(keysymtab, ARRAY_SIZE(keysymtab) - 1, keysym);
```

> As a side note, I currently have an implementation that translate XML entity names to Unicode code points in C. I don't know if there is a "demand" for it but be able to treat them on libxkbcommon would be a plus for me.

XML entities are out of scope libxkbcommon. You should still publish it though, it might be useful for others.

**Comment by andrecbarros** [comment]
Works exactly like:
-    if ((keysym & 0xff000000) == 0x01000000)
+    if (keysym >= 0x01000100 && keysym <= 0x0110ffff)
         return keysym & 0x00ffffff;

**Comment by andrecbarros** [comment]
OK, will leave the optimization for some other thread. I really think it is straightforward an carries a good performance boost for no additional relevant complexity.

**Comment by bluetech** [comment]
The diff contains two functional changes:

1. Disallow the "Unicode ASCII" keysyms - `0x01000100 - 0x01000099` - use `0x00 - 0x99` instead.
2. Disallow Unicode keysysm above the Unicode codepoint range - `0x01110000 - 0x01FFFFFF`.

I think we should definitely apply change (2) - such keysyms do not make sense.

As for change (1), I don't think we should apply it:

- It might cause regressions, if there's code out there relying on this mapping.
- The mapping is nice; it means there is a direct simple mapping between all Unicode codepoints and Unicode keysyms - add `0x01000000` - without a special case for the ASCII range.
- The duplication does not worry me - many other legacy codepoints are duplicated with Unicode, after all.

---

Regarding the optimizations, can you describe what they are/how they work?

**Comment by andrecbarros** [comment]
Sorry, I am at miss here. The code you proposed is, in essence, the same of 2nd part of patch, is that what you mean?

About the optimization, take a look at the comment in front of the indexes, they mark the positions on keysymtab where numerical ranges start. As you can see, when a '>>8' is applied, that generates numbers in the range 0..0x21. That means I don't need to apply a binary search on entire table, just on bounds present on the new auxiliary table and we can pick the exactly range by just doing a 'keysym >> 8". There is no regression about it, I can send a code to test it if you want (I already did test, not because I thought it would be needed but because I anticipated that someone would ask for it).

**Comment by andrecbarros** [comment]
Complementing, look at what happens when any number between 0x1400 and 0x2000 is provided:
first == 762
last = 761

It means all them can be rejected really quickly (this is the best case scenario for this kind of optimization).
The worst case happens for numbers in ranges full of numbers so we have, roughly, 256 cases to test (there is no range as complete as this hypothesis, the worst case is about almost 100 numbers), so it would take 8 tests at max to check the whole interval (like I said, there is no case like that, 6 is, probably, the worst case) instead of the 9..10 without it.

I may attach here the file with tests so that you can see by yourself (the test includes a case where only numbers from keysymtab compose the input and another with the whole range). Looks OK to you?

**Comment by andrecbarros** [comment]
OK, here are the tests:

[keysym-utf-tests.c.txt](https://github.com/xkbcommon/libxkbcommon/files/1958124/keysym-utf-tests.c.txt)

Rename to keysym-utf-tests.c, put on src/ directory of libxkbcommon and compile with:
gcc -g -ggdb -D KEYSYM_UTF_DEBUG -o keysym-utf-tests keysym-utf-tests.c utf8.c -I.. -I/usr/include $( pkg-config --cflags x11 ) $( pkg-config --libs xkbfile xcb x11 )

Run with:
./keysym-utf-tests

Check the results, I think all your concerns will be cleared.

Best regards,
André

**Comment by andrecbarros** [comment]
One last recommendation, if you really keep bin_search static, then there is no reason to not instead merge it inside the xkb_keysym_to_utf (or declare it inline), then you can squeeze a bit more speed from the code, again, without anything being compromised.

**Comment by andrecbarros** [comment]
OK, inside benchmarks there is a glitch on 4th test case, I repeated the same value on entire loop. Fixed it and implemented my suggestion. The result surprised me, it was even better than I supposed to merge the binary search inside xkb_keysym_to_utf.

[keysym-utf-tests.c.txt](https://github.com/xkbcommon/libxkbcommon/files/1958228/keysym-utf-tests.c.txt)

Best regards,
André

**Comment by andrecbarros** [comment]
Another glitch, it does not affect the result, though.

[keysym-utf-tests.c.txt](https://github.com/xkbcommon/libxkbcommon/files/1958249/keysym-utf-tests.c.txt)

**Comment by andrecbarros** [comment]
OK, pushed the changes on my fork. Also there you will find why the code is faster.

Note that the instrumentation for debug purposes also contains the function that generates the range boundaries auxiliary table, i.e., keysymtab_bounds: print_limits.

Perhaps, if you end up accepting the changes, I may provide a python external version you may integrate on your data generational routines.

Feel free to ask for any clarification.

Best regards,
André
