### ISSUE TITLE
Surrogates not handled

### ISSUE THREAD

**Issue by andrecbarros** [xkbcommon/libxkbcommon#60]
Surrogates (0xd800..0xdfff) are not handled by utf32_to_utf8 and by xkb_keysym_to_utf32. They are invalid code points on utf32 and utf8 but used for code pairs in utf16. is_valid_utf8 works as it should and return numbers inside this range as invalid. 

Please, see my fork about it. I recoded the utf32_to_utf8 and is_valid_utf8 to be more straightforward (and easier to maintain). As an added benefit we get an utf8_to_utf32 function.

Regards,
André

**Comment by bluetech** [comment]
So apparently we are encoding [`WTF-8`](https://en.wikipedia.org/wiki/UTF-8#WTF-8) instead of UTF-8, heh.

Sounds like we should reject these codepoints, however I'm not really sure of the implications. I will need to look at it further. Informative comments are welcome!
