### ISSUE TITLE
Project homepage redesign.

### ISSUE THREAD

**Issue by TonCherAmi** [xkbcommon/libxkbcommon#70]
Hey, I've made an attempt at redesigning the project homepage.
You can take a look at the result [here](https://toncherami.github.io/xkbcommon).

Regarding the technologies used, it is just bootstrap (CSS only), I've also used the [iosevka](https://github.com/be5invis/iosevka) font.

The source resides [here](https://github.com/TonCherAmi/xkbcommon), it is licensed under the MIT license so you are free to do as you please with it.

Hope you like it!

**Comment by bluetech** [comment]
Wow, thanks! It looks good to me.

I only have one suggestion: the release tables feels a little non-intuitive to me, it is hard to see the chronological progression at a glance. Maybe it would be better to keep it a list? (The table format also requires horizontal scrolling on small screen).

I think it would also be nice to for the design to somehow reflect the "keyboardness" of the library. The favicon kinda looks like keys I suppose :)

Also cc @fooishbar, the original "designer".

**Comment by TonCherAmi** [comment]
@bluetech I've reworked the release table using `.list-group`, it seems to be an improvement, what do you think?

Yeah, that would be neat, I can't say I have any decent ideas though. The favicon is an absolute abomination to be sure, sorry about that. Making it was, however, the hardest part of it all (shoutout to gimp).

**Comment by whot** [comment]
fwiw, while I like the look and feel of the site, I find the font really hard to read.

**Comment by fooishbar** [comment]
Thanks a lot for taking this on! I agree with @whot on the font, in that whilst it looks jazzy, it would be nice to have something a bit more traditionally legible. Whilst making changes, it'd also be worth dropping the reference to Bugzilla, since we don't use that at all anymore.

I have no objections at all to modernising the site, so please proceed at will.

**Comment by TonCherAmi** [comment]
I've replaced Iosevka with Ubuntu Mono, hopefully you will find it to be more legible.

**Comment by TonCherAmi** [comment]
The license mentions that the only thing required is that
> The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

I suppose that `copy` would mean the repository as a whole, meaning that including it in the files themselves is not necessary. I believe it should allow you to do anything you wish with the source as long as you keep the license there.

The font is licensed under the Ubuntu Font License, it seems to require both copyright notice and license to be included, I pushed them to the repository.
```
-------------------------------
UBUNTU FONT LICENCE Version 1.0
-------------------------------

PREAMBLE
This licence allows the licensed fonts to be used, studied, modified and
redistributed freely. The fonts, including any derivative works, can be
bundled, embedded, and redistributed provided the terms of this licence
are met. The fonts and derivatives, however, cannot be released under
any other licence. The requirement for fonts to remain under this
licence does not require any document created using the fonts or their
derivatives to be published under this licence, as long as the primary
purpose of the document is not to be a vehicle for the distribution of
the fonts.

DEFINITIONS
"Font Software" refers to the set of files released by the Copyright
Holder(s) under this licence and clearly marked as such. This may
include source files, build scripts and documentation.

"Original Version" refers to the collection of Font Software components
as received under this licence.

"Modified Version" refers to any derivative made by adding to, deleting,
or substituting -- in part or in whole -- any of the components of the
Original Version, by changing formats or by porting the Font Software to
a new environment.

"Copyright Holder(s)" refers to all individuals and companies who have a
copyright ownership of the Font Software.

"Substantially Changed" refers to Modified Versions which can be easily
identified as dissimilar to the Font Software by users of the Font
Software comparing the Original Version with the Modified Version.

To "Propagate" a work means to do anything with it that, without
permission, would make you directly or secondarily liable for
infringement under applicable copyright law, except executing it on a
computer or modifying a private copy. Propagation includes copying,
distribution (with or without modification and with or without charging
a redistribution fee), making available to the public, and in some
countries other activities as well.

PERMISSION & CONDITIONS
This licence does not grant any rights under trademark law and all such
rights are reserved.

Permission is hereby granted, free of charge, to any person obtaining a
copy of the Font Software, to propagate the Font Software, subject to
the below conditions:

1) Each copy of the Font Software must contain the above copyright
notice and this licence. These can be included either as stand-alone
text files, human-readable headers or in the appropriate machine-
readable metadata fields within text or binary files as long as those
fields can be easily viewed by the user.

2) The font name complies with the following:
(a) The Original Version must retain its name, unmodified.
(b) Modified Versions which are Substantially Changed must be renamed to
avoid use of the name of the Original Version or similar names entirely.
(c) Modified Versions which are not Substantially Changed must be
renamed to both (i) retain the name of the Original Version and (ii) add
additional naming elements to distinguish the Modified Version from the
Original Version. The name of such Modified Versions must be the name of
the Original Version, with "derivative X" where X represents the name of
the new work, appended to that name.

3) The name(s) of the Copyright Holder(s) and any contributor to the
Font Software shall not be used to promote, endorse or advertise any
Modified Version, except (i) as required by this licence, (ii) to
acknowledge the contribution(s) of the Copyright Holder(s) or (iii) with
their explicit written permission.

4) The Font Software, modified or unmodified, in part or in whole, must
be distributed entirely under this licence, and must not be distributed
under any other licence. The requirement for fonts to remain under this
licence does not affect any document created using the Font Software,
except any version of the Font Software extracted from a document
created using the Font Software may only be distributed under this
licence.

TERMINATION
This licence becomes null and void if any of the above conditions are
not met.

DISCLAIMER
THE FONT SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO ANY WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF
COPYRIGHT, PATENT, TRADEMARK, OR OTHER RIGHT. IN NO EVENT SHALL THE
COPYRIGHT HOLDER BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
INCLUDING ANY GENERAL, SPECIAL, INDIRECT, INCIDENTAL, OR CONSEQUENTIAL
DAMAGES, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF THE USE OR INABILITY TO USE THE FONT SOFTWARE OR FROM OTHER
DEALINGS IN THE FONT SOFTWARE.
```

**Comment by bluetech** [comment]
OK. I will hopefully have time to deploy this later today. In the mean time, how do you feel about moving https://github.com/TonCherAmi/xkbcommon over to xkbcommon/website? I don't have any experience with that but I think it is possible to do that and make you a collaborator on the repo.

**Comment by TonCherAmi** [comment]
Great! I wouldn't mind transferring ownership personally, I'll go ahead and try it I guess.

**Comment by bluetech** [comment]
I created the repo (https://github.com/xkbcommon/website) and invited you as a collaborator; let me know how it goes.

**Comment by bluetech** [comment]
Thanks. I'll leave a note here once it's up.

**Comment by bluetech** [comment]
The website is deployed now - thanks again @TonCherAmi.

Unfortunately there is currently an SSL error due to an expired certificate - cc @fooishbar. But that's unrelated to this issue.
