### ISSUE TITLE
https certificate expired

### ISSUE THREAD

**Issue by jbicha** [xkbcommon/libxkbcommon#71]
The Lets Encrypt certificate for https://www.xkbcommon.org/ expired on October 17. Please renew and install the updated certificate.

**Comment by fooishbar** [comment]
Ugh, I have no idea why this keeps happening: certbot renews but fails to restart nginx. I've restarted nginx by hand now, and since I'm fresh out of ideas, put in the most simple and stupid cronjob to restart nginx unnecessarily often. Thanks for letting us know.

+ @bluetech
