### ISSUE TITLE
How to get and set the currently active layout?

### ISSUE THREAD

**Issue by Hi-Angel** [xkbcommon/libxkbcommon#72]
I'm trying [to allow sway to store a layout per window](https://github.com/swaywm/sway/issues/2361#issuecomment-433642415). I figured that currently active layout is stored in `xkb_state`.

As I understand, libxkbcommon doesn't have any "layout-changed" hook, so I need to manually check active layout every time `xkb_state` being touched *(is that correct?)*.

Then questions come down to:

1. How to get an id of currently active layout?
2. How to set the currently active layout with an id.

The closest I could find was [this issue](https://github.com/xkbcommon/libxkbcommon/issues/20), but they're getting layout name with `xkb_keymap_layout_get_name()`, whereas I guess I gonna need an index; and I couldn't find in `xkbcommon.h` anything with infix `layout_set` anyway.

**Comment by bluetech** [comment]
Before I answer your questions, I'd like to understand how are you planning to architect things, since that would affect the answer. Will each window have it's own `xkb_state`? What would you like to happen when a new window is created?

**Comment by Hi-Angel** [comment]
> Will each window have it's own xkb_state?

Per my understanding `xkb_state` contains not only layout, but also lots of other stuff. I want only to have layout per window, so I'm guessing instead I need to keep with each window a `xkb_layout_index_t` which is an ID of a layout in libxkbcommon.

> What would you like to happen when a new window is created?

I imagine, this window should have "default layout", which I'm going to get just after compositor was started, and then assign it to every new window.

**Comment by Hi-Angel** [comment]
Currently `xkb_state` is stored per keyboard device *(the `struct wlr_keyboard` from wlroots)*. I think of keeping it that way.

**Comment by Hi-Angel** [comment]
Anyway, thank you for the tips, I guess the question can be closed.

**Comment by Hi-Angel** [comment]
I'm a bit confused though: the `xkb_state_serialize_layout()` accepts a non-const `xkb_state` . Does it modify `xkb_state` somehow? Don't see anything in description.

**Comment by bluetech** [comment]
No, it doesn't modify the `xkb_state`. None of the method receivers are marked `const`. I guess it didn't sufficiently bother anyone. Also, in a few cases, interior mutability is used (ref counts, caches, scratch buffers etc.), that's another reason.

**Comment by Hi-Angel** [comment]
> Let us know how it goes.

So, I [wrote the code](https://github.com/Hi-Angel/sway/commit/52f50cacccc3cb84dce5e3f414ada1ab8d644934), but it seems not to work as expected, I wonder if you know anything about it. Could it be the reason you called it a "hacky way"?

After I change layout with `xkb_state_update_mask()`, and start typing in an application, the first letter always being typed with the previous language layout, and only then xkbcommon seems to finally switch it.

I did some debugging today, and after new app receives focus, I restore layout exactly once, and then there's plenty of time before I press a key, so I don't think it could be a race, I'm pretty sure it has something to do with xkbcommon per se.

**Comment by bluetech** [comment]
I noticed a bug in the code you linked, maybe that's causing the problem?

**Comment by Hi-Angel** [comment]
Thanks, good point, I changed LOCKED to DEPRESSED/LATCHED, pushed, and retested. Unfortunately it changed nothing.

**Comment by Hi-Angel** [comment]
So, turns out, it's enough to press any key, even a modifier one *(e.g. <kbd>Ctrl</kbd>)*, to finally make layout flush. Today I tried setting `rbreak` to every `xkb_` function to look which ones gets called, in the hope of figuring which one makes xkb_state to flush, but long story short, I didn't succeed.

I guess, to move forward I need to find some magic function that makes layout to flush. Probably, somehow emulating a keypress would work, will see.

**Comment by Hi-Angel** [comment]
Actually, I just started wondering if sway simply bypasses xkb at some point. I see there some "keycodes" and "modifiers" which are stored in internal `wlr_keyboard`, and then gets passed to a client. I wonder if those can be the reason for this confusion, because whenever they appear in that struct, it's surely far before layout gets changed.

**Comment by bluetech** [comment]
`xkb_state` is a straight-forward state machine, with inputs and outputs. If you want to see whether this behavior is caused by xkbcommon or sway, write a program which creates and `xkb_keymap` and an `xkb_state` from it, update the state like you do in your program and check the output. If you can reproduce the problem this way, please paste it here. [Here](https://github.com/xkbcommon/libxkbcommon/blob/293c704cbedd95779351a7295683159e93e12de7/test/state.c#L299) is some `xkb_state` test for example.

**Comment by Hi-Angel** [comment]
I have a question. I have option `grp_led:scroll` set, which lights on a LED upon switching to the second layout. It usually works fine. However when I change layout with `xkb_state_update_mask()`, the LED does not light on *(not until I press any key)*. Why would that be?

**Comment by bluetech** [comment]
When you say the LED does not light up, do you mean `xkb_state_led_index_is_active()` returns 0, or do you mean the actual keyboard LED doesn't light up?

**Comment by Hi-Angel** [comment]
The actual keyboard LED doesn't. I didn't check status of `xkb_state_led_index_is_active()`, but can do this evening.

**Comment by Hi-Angel** [comment]
I checked status of `xkb_state_led_index_is_active()`, and it does return `1` *(LED is active)* just after I called `xkb_state_update_mask()`. Even though the LED actually is not lit up, not until I press any key.

**Comment by Hi-Angel** [comment]
Thanks. Could you please elaborate on this sentence:

> After you update the `xkb_state`, you need to trigger all of the updates which depend on it.

I assumed structs `xkb_keymap` and `xkb_state` kind of "own" keyboard device. What else possibly could be needed to update?

**Comment by fooishbar** [comment]
xkbcommon does not 'own' the keyboard device or the Wayland connection. It is an abstract library implementing the state machine required to interpret keypresses and provide higher-level information (e.g. 'keycode 38 with the current state means capital A'). Inputs into xkbcommon only update that internal state machine.

Compositors typically open the input devices directly themselves, use libinput to receive the events, pass those events to libxkbcommon, then depending on the result, will update keyboard LEDs and send wl_keyboard modifiers/key events to clients (cf. the 'layout flush' discussion earlier).

If you search wlroots sources for `xkb_state_update_key()`, you will probably see this taking place: events received from libinput (or elsewhere), passed into xkbcommon, then wlroots taking responsibility for updating the keyboard devices (with LED changes) and Wayland clients (with `modifiers`/`key` events). You can see [what Weston does](https://gitlab.freedesktop.org/wayland/weston/blob/master/libweston/input.c#L1993) also.

Probably the best thing to do is to run the same items after `xkb_state_update_mask()` as you do after `xkb_state_update_key()` inside wlroots.
