### ISSUE TITLE
Compose API does not support non-utf8 locales

### ISSUE THREAD

**Issue by gatispaeglis** [xkbcommon/libxkbcommon#76]
If I pass for example "el_GR.ISO8859-7" to xkb_compose_table_new_from_locale() and enable XKB_LOG_LEVEL_DEBUG (in XKB context) I see the following error message:

"/usr/share/X11/locale/iso8859-7/Compose:84:29: string literal is not a valid UTF-8 string"

Is this by design or a bug? I could not find in the documentation any info about this. The locale path do contain these locales. I am guessing there are people that use them?

I remember one bug report about Qt's custom Compose table parser - https://bugreports.qt.io/browse/QTBUG-35770 There was a bug that it was asserting on non-utf8 locales, due to programming error. This bug report indicates that there are users that for some reason use non-utf8 locales.

**Comment by gatispaeglis** [comment]
I am not convinced either that people intentionally want to use non-utf8. Maybe I can simply flip the switch and see if anyone will complain :)

> Try to convince these users to use a UTF-8 locale, unless there is actually a good usecase.

That currently seems like the most sane option. 

> Tell me it's really needed and I'll try the iconv route :)

Hopefully that won't be the case, but one option would be that libxkbcommon returns raw data, instead of decoded composed symbol. In Qt then we could use http://doc.qt.io/qt-5/qtextcodec.html

As this was by design, I think you can close this report until (if ever) more information becomes available.

**Comment by bluetech** [comment]
OK, feel free to reopen if needed.
