### ISSUE TITLE
Doxygen causes segmentation fault on

### ISSUE THREAD

**Issue by stdefeber** [xkbcommon/libxkbcommon#78]
Nearly at the end of the build I get the following:

GEN      doc/html
/bin/sh: line 4: 25382 Done                    ( cat doc/Doxyfile; echo "INPUT = README.md doc/quick-guide.md doc/compat.md xkbcommon/xkbcommon.h xkbcommon/xkbcommon-names.h xkbcommon/xkbcommon-x11.h xkbcommon/xkbcommon-compose.h"; echo "OUTPUT_DIRECTORY = /tmp/SBo/libxkbcommon-0.8.2/doc" )
     25383 Segmentation fault      | ./scripts/doxygen-wrapper "/usr/bin/doxygen" - "/tmp/SBo/libxkbcommon-0.8.2"
make[1]: *** [Makefile:2389: doc/html] Error 139
make[1]: Leaving directory '/tmp/SBo/libxkbcommon-0.8.2'
make: *** [Makefile:1023: all] Error 2

Besides this there is a typo at line 216, being a "\n", in file 
xkbcommon-compose.h

Where doxygen seems to fail on as well !

br,

Simon,
Slackware-current, 02-01-2019

**Comment by bluetech** [comment]
I cannot reproduce with doxygen 1.8.14.

I suggest trying a newer Doxygen version, and if that still segfaults, report it to Doxygen.

As a workaround, if you don't need the docs, you can disable them during configure.

> Besides this there is a typo at line 216, being a "\n", in file xkbcommon-compose.h

This is intended, it inserts a literal newline.

**Comment by stdefeber** [comment]
OK. Thanks. 
I have doxygen 1.8.15 and will retry with 1.8.14 or else use it without the docs.
