### ISSUE TITLE
Discrepancy in definition of Ocaron

### ISSUE THREAD

**Issue by kevemueller** [xkbcommon/libxkbcommon#80]
To whom it may concern,
there is a discrepancy the line defining Ocaron:

Currently it reads
`#define XKB_KEY_Ocaron                     0x10001d1  /* U+01D2 LATIN CAPITAL LETTER O WITH CARON */`
To be consistent with the contract set out in the preamble of the file it should read:
`#define XKB_KEY_Ocaron                     0x10001d1  /* U+01D1 LATIN CAPITAL LETTER O WITH CARON */`

Also wrong, but harder to decide:
`#define XKB_KEY_approxeq                   0x1002248  /* U+2245 ALMOST EQUAL TO */`
`#define XKB_KEY_notapproxeq                0x1002247  /* U+2247 NOT ALMOST EQUAL TO */`
could be
`#define XKB_KEY_approxeq                   0x1002248  /* U+2248 ALMOST EQUAL TO */`
`#define XKB_KEY_notapproxeq                0x1002249  /* U+2249 NOT ALMOST EQUAL TO */`
or
`#define XKB_KEY_approxeq                   0x1002245  /* U+2245 APPROXIMATELY EQUAL TO */`
`#define XKB_KEY_notapproxeq                0x1002247  /* U+2247 NEITHER APPROXIMATELY NOR ACTUALLY EQUAL TO */`
I tend to support the second option.

Thanks in advance for fixing.
Cheers,
Keve

**Comment by bluetech** [comment]
@whot Seems like @kevemueller edited the issue and added another suggestion (I missed it since I read the email). Maybe you have an opinion on that as well? :)

**Comment by whot** [comment]
cc @fooishbar because I'm sure he still remembers which one he wanted after almost 14 years.

**Comment by fooishbar** [comment]
Yeesh. I'm pretty sure I wanted the former, having got the symbol correct but the name wrong.

The Neo layout currently uses `approxeq` (i.e. 2245) as-is on level 4 for Num Lock (seriously ...), however the US Mac layout notes that `approxeq` is confused between 2245 and 2248 and explicitly selects 2248. The current Icelandic Mac layout just uses `approxeq`, though the old layout explicitly selects 2248, and is probably correct. 2248 is also used in Arabic, Bulgarian, Polish, Russian, and IPA (!) layout variants.

I'm not sure if Neo users have strong feelings on the matter. I personally don't: though I prefer 2248, I only added those symbols for a custom layout I wrote to better take notes in the maths classes for the university degree I dropped out of 13 years ago.

**Comment by knittl** [comment]
@fooishbar Hi, Neo-Layout member here. We used `approxeq` in the layout definition of the Neo layout, because it mapped (maps?) to [U+2248](https://www.compart.com/en/unicode/U+2248) ("Almost Equal To", i.e. "≈"). The keysym `approxeq` was chosen not because we expected "approximately equal" (U+2245), but because it generated U+2248.

This is documented in the [Neo reference description](https://git.neo-layout.org/neo/neo-layout/src/branch/master/A-REFERENZ-A/neo20.txt) (German only). So yes, we (Neo) have strong feelings :) layer 4 of the numlock key must produce the ≈ character.

**Comment by fooishbar** [comment]
I would recommend you change it to explicitly specifying `U2248`.
