### ISSUE TITLE
Mismatches in mapping for approxeq and notapproxeq

### ISSUE THREAD

**Issue by kevemueller** [xkbcommon/libxkbcommon#82]
To whom it may concern,
follow up on #80.  Sorry, but I edited the post after initial submission. 
As that one is closed, the relevant part here again.
Including @bluetech and @whot who reacted on it.

Also wrong, but harder to decide:
#define XKB_KEY_approxeq 0x1002248 /* U+2245 ALMOST EQUAL TO */
#define XKB_KEY_notapproxeq 0x1002247 /* U+2247 NOT ALMOST EQUAL TO */
could be
#define XKB_KEY_approxeq 0x1002248 /* U+2248 ALMOST EQUAL TO */
#define XKB_KEY_notapproxeq 0x1002249 /* U+2249 NOT ALMOST EQUAL TO */
or
#define XKB_KEY_approxeq 0x1002245 /* U+2245 APPROXIMATELY EQUAL TO */
#define XKB_KEY_notapproxeq 0x1002247 /* U+2247 NEITHER APPROXIMATELY NOR ACTUALLY EQUAL TO */
I tend to support the second option.

Thanks in advance for fixing.
Cheers,
Keve

**Comment by svenssonaxel** [comment]
Fixed in xorg-proto by deprecating `XK_approxeq` and `XK_notapproxeq`, so now you can sync it.

**Comment by bluetech** [comment]
I synced to the latest xorg-proto which marks these as deprecated.
