### ISSUE TITLE
Can not build static library

### ISSUE THREAD

**Issue by uilianries** [xkbcommon/libxkbcommon#84]
Hi! 

I'm trying to build libxkbcommon using Meson + Ninja, but when I set to build as static library, the symbols are not exported, however for shared library it works fine.

#### Steps

    git clone https://github.com/xkbcommon/libxkbcommon.git
    cd libxkbcommon
    git checkout xkbcommon-0.8.2
    mkdir build
    meson ${PWD} build --backend=ninja --default-library=static
    ninja -C build/
    nm build/libxkbcommon.a

You could execute the same steps using `--default-library=shared` instead.

#### Environment
OS: Linux Ubuntu 18.10 amd64
Meson: 0.49.0
Ninja: 1.8.2
Compiler: GCC 7.3.0

/cc @ericLemanissier

Regards!

**Comment by whot** [comment]
This appears to be a [meson bug](https://github.com/mesonbuild/meson/issues/3937)

**Comment by uilianries** [comment]
Thanks for pointing the error, but maybe you should warning the users about that, like a message in your Meson script when the trying to build static library. The error is not your fault, but affects directly your project.

**Comment by bluetech** [comment]
This is fixed in libxkbcommon 0.8.3 (just released).

**Comment by uilianries** [comment]
Thanks so much! I gonna update my copy
