### ISSUE TITLE
Static build with meson produces empty libxkbcommon-x11.a

### ISSUE THREAD

**Issue by DavidEGrayson** [xkbcommon/libxkbcommon#86]
I noticed that the recent pull request #85 fixed a bug that was causing Meson to produce an empty `libxkbcommon.a` file.  However, the other library built by this project, `libxkbcommon-x11.a`, remains empty because it was built in the same way but it was not addressed by the pull request.

My workaround for now is to run `mv libxkbcommon-x11-internal.a libxkbcommon-x11.a` before `ninja install`.

In case anyone cares, I am using Nix, the functional package manager, to cross-compile libxkbcommon and a number of other libraries to produce static, standalone executables.  Here is my build recipe for libxkbcommon: https://github.com/DavidEGrayson/nixcrpkgs/tree/6826a88be34cd76448d0c1d06d09da799a983a54/pkgs/libxkbcommon

**Comment by bluetech** [comment]
Eek, thanks. I'll get to this today or tomorrow.

**Comment by whot** [comment]
mea culpa, I didn't click that anything with `x11` in the name would ever need to be statically linked ;)

I have the patch ready [here](https://github.com/whot/libxkbcommon/tree/wip/static-lib-sources), will file a MR once we clarify our position on the `libxbkcommon-x11-internal` lib (feel free to c-p if you're in a hurry).

**Comment by bluetech** [comment]
Thanks @whot.

You asked in the commit whether to keep `libxkbcommon_x11_internal`. Only reason is that if someday we do want to test an internal function in libxkbcommon-x11 it will be possible. So just for consistency I'd keep it. I'll cp your first commit and do another release soon.

**Comment by whot** [comment]
righty-o, works for me :) thanks for the cherry-pick
