### ISSUE TITLE
fuzz directory missing from http://xkbcommon.org/ tarball

### ISSUE THREAD

**Issue by manesm52** [xkbcommon/libxkbcommon#87]
I attempted to download and build the 0.8.3 release from the http://xkbcommon.org/ website.  Meson failed during configuration and upon investigating, the "fuzz" directory was not present in the tarball.  I can use git clone or download the tarball from https://github.com/mesonbuild/meson/releases and build just fine, but something strange must happened setting up the tarballs for the website http://xkbcommon.org/.

**Comment by wak-google** [comment]
Yeah, it's missing a whole bunch of stuff from the dist tarball. They must have stopped maintaining parity in the autotools builds.

**Comment by bluetech** [comment]
Thanks for letting us know. This is fixed in master and will be released later today.

When we finally drop autotools, we'll just use the git archive tarballs.
