### ISSUE TITLE
libxkbcommon-0.8.4 fails to cross compile

### ISSUE THREAD

**Issue by maxice8** [xkbcommon/libxkbcommon#89]
It eagerly uses pkg-config to find an executable and ends up with:

```
wayland_scanner = find_program(wayland_scanner_dep.get_pkgconfig_variable('wayland_scanner'))
```

```
/usr/aarch64-linux-gnu/usr/bin/wayland-scanner code /usr/aarch64-linux-gnu/usr/share/wayland-protocols/unstable/xdg-shell/xdg-shell-unstable-v6.xml interactive-wayland@exe/xdg-shell-unstable-v6-protocol.c
/bin/sh: /usr/aarch64-linux-gnu/usr/bin/wayland-scanner: cannot execute binary file: Exec format error
ninja: build stopped: subcommand failed.
```

**Comment by fooishbar** [comment]
Does it work if you put `native: true` as an argument to the `wayland_scanner_dep = dependency(...)` call?

**Comment by maxice8** [comment]
On Sat, Feb 23, 2019 at 12:55:36AM -0800, Daniel Stone wrote:
> Does it work if you put `native: true` as an argument to the `wayland_scanner_dep = dependency(...)` call?
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/xkbcommon/libxkbcommon/issues/89#issuecomment-466630770

I am working on a PR and will make it soon, just testing it builds here.
