### ISSUE TITLE
grp:caps_toggle doesn't work with ctrl:swapcaps

### ISSUE THREAD

**Issue by YaLTeR** [xkbcommon/libxkbcommon#93]
Hello! Sorry if this isn't the correct place to report this issue.

I'm using [sway](https://github.com/swaywm/sway) (a Wayland compositor), which uses `libxkbcommon` for keyboard layout configuration. I'm using two keyboard layouts and trying to configure layout switching to use Caps Lock while also swapping Caps Lock with Ctrl, so the settings are as follows:
```
xkb_layout us,ru
xkb_options grp:caps_toggle,ctrl:swapcaps
```
While `grp:caps_toggle` works by itself, when combined with `ctrl:swapcaps` it seems to be ignored, so the physical Caps Lock key acts as Ctrl (as intended), but the physical Ctrl key still acts as Caps Lock (rather than toggling the keyboard layout).

**Comment by bluetech** [comment]
These rules are defined like this, in xkeyboard-config:

```
// grp:caps_toggle
hidden partial modifier_keys
xkb_symbols "grouplock" {
    replace key <CAPS> { [ ISO_Next_Group, Caps_Lock ] };
};

// ctrl:swapcaps
partial modifier_keys
xkb_symbols "swapcaps" {
    replace key <CAPS> { [ Control_L ] };
    replace key <LCTL> { [ Caps_Lock ] };
    modifier_map Control { <CAPS> };
    modifier_map  Lock { <LCTL> };
};
```

They both try to `replace key <CAPS>`. I think what you want is for the `grp:caps_toggle` to take priority, but incidentally in this case, in xkbcommon at least, the priority is determined according to who comes later in the file `/usr/share/X11/xkb/rules/evdev`, and it happens that `grp:caps_toggle` comes before.

I'd recommend either find more specific non-conflicts xkb_options to use, add your own custom option, or report the issue to the xkeyboard-config project, which defines the rules.

**Comment by YaLTeR** [comment]
Just in case anybody else stumbles upon this: I went with the custom rule option, and recently even submitted a [merge request](https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/merge_requests/28) into xkeyboard-config (where it unfortunately seems to be being ignored).
