### ISSUE TITLE
Add wildcard parsing for options

### ISSUE THREAD

**Issue by whot** [xkbcommon/libxkbcommon#99]
A common use-case (I think) for keyboard layouts is to want to override one or two symbols only. i.e. what `xmodmap` provides, but we don't really have an answer to that. 

libxkbcommon parses from `$HOME/.xkb` already and `setxkbmap`/`xkbcommon` can do the same with `-I`.  Alas, this basically only works for layouts/variants thanks to the right wildcards but not for options. So this works:
```
$ cat $HOME/.xkb/symbols/custom 
partial alphanumeric_keys 
xkb_symbols "foo" {
    include "us(basic)"
    name[Group1]= "English (US)";
    key.type[group1]="ONE_LEVEL";
    key <TLDE> {        [      VoidSymbol ]       };
};
```
Together with:
```
$ setxkbmap -layout custom -variant foo -print | xkbcomp -I$HOME/.xkb - $DISPLAY
```
But that's limited in that only one can be selected at a time, you can't pick-and-match like you do with options. It would be better to be able to set this through:

```
$ setxkbmap -layout us -option "custom:foo"
```
But that doesn't work because we don't have a wildcard in the rules file for options. So what is needed in xkeyboard-config is something like this:
```
! option        =       symbols  
  .... all existing entries
  * = +%o
```
This requires parsing of `%o` in libxkbfile and libxkbcommon and the correct expansion. I've dabbled around with this in libxkbfile and the options are basically:

1. `* = +custom(%o)`, specified as `-option foo`. This would force users to have all options in `$HOME/.xkb/symbols/custom`.
1. `* = +%o`, specified as `-option custom(foo)`
1. `* = +%o` with auto-replacing `custom:foo` to `custom(foo)`. Nicest for integration, but highest risk of misparsing something.

If we go with this, we need to synchronise this well enough that we ship xkeyboard-config with the new rules file after we shipped all other related packages that shouldn't fail on the new wildcard match.

Opinions? Anything I forgot?

cc @svu, @fooishbar 

Somewhat related to #40

**Comment by svu** [comment]
To me this looks like a very good idea, making things flexible (and may be less commits for exotic options in xk-c)

**Comment by whot** [comment]
@bluetech, @fooishbar  - any comments? Not asking you to do the work, just to be happy with the patches when I send them. Too much work to get it rejected :)

@svu, thanks and yes, that's the intent here. If we can then figure out a tool to write these option snippets, life will be much easier (for everyone but whoever writes that tool ;)

**Comment by bluetech** [comment]
I agree with the motivation, enabling pick-and-match would be nice. 

[Although the custom keymaps stuff doesn't help much for GUI users like Gnome's Tweak Tool, they only show options listed in the `evdev.xml` file I believe.]

---

You propose adding

```
! option        =       symbols  
  .... all existing entries
  * = +%o
```

Options make sense not only for symbols, but also the other components, keycodes, types, compat, geometry. Do you propose adding rules for those as well?

---

> any comments? Not asking you to do the work

I looked at the xkbcommon code. The complication is that in these rules

```
! option = symbols  
  baz    = +%o
  *      = +%o
```

the `%o` expansion is "context-dependent": it should expand to the option that was matched, out of all of the options in the MLVO (the user configuration). This differs from the [other expansions](https://github.com/xkbcommon/libxkbcommon/blob/06a80beed8a408eebffa2fe80854fcda38d82ee2/doc/rules-format.txt#L66) - they don't care what was matched, they expand from the MLVO directly. So you get into trouble with this:

```
! option  option   = symbols  
  baz     quux     = +%o
```

---

> If we go with this, we need to synchronise this well enough that we ship xkeyboard-config with the new rules file after we shipped all other related packages that shouldn't fail on the new wildcard match.

If we actually do this, I would love to try and get something for https://github.com/xkbcommon/libxkbcommon/issues/37 in as well, but let's not get ahead of ourselves :)

**Comment by bluetech** [comment]
> So you get into trouble with this:

Actually, in xkbcommon at least, repeating `option` like this is not allowed, so this is not possible.

Here are a few other issues:

---

With a rule like this:

```
! model         =       keycodes
  pc98          =       evdev(pc98)
  applealu_jis  =       evdev+macintosh(jisevdev)
 $jollamodels   =       evdev+jolla(jolla)
  olpc          =       evdev+olpc(olpc)
  olpcm         =       evdev+olpc(olpcm)
  *             =       evdev
```

even if you don't specify a model in the RMLVO, the `*` case still matches, i.e. it sets the default. I guess that for options this behavior can be changed.

---

At least in xkbcommon, a rule is only matched once. So, if a user specifies options `custom:foo,custom:bar,custom:baz`, only `foo` would be matched. This can perhaps be changed.

---

At least in xkbcommon, all option rules are attempted, even if already matched. So, if a user specifies options `grp:shift_toggle,custom:foo`, the `grp:shift_toggle` will match the wildcard too. 

https://github.com/xkbcommon/libxkbcommon/blob/06a80beed8a408eebffa2fe80854fcda38d82ee2/src/xkbcomp/rules.c#L806-L812

---

If you make a typo in the name of an option, or not implement the custom option, previously you would get a warning (non fatal)

```
xkbcommon: ERROR: Unrecognized RMLVO option "baz" was ignored
```

Now you will get this error if the `~/.xkb/symbols/custom` exists and non-empty:

```
xkbcommon: ERROR: Couldn't process include statement for 'custom(baz)'
xkbcommon: ERROR: Abandoning symbols file "(unnamed)"
xkbcommon: ERROR: Failed to compile xkb_symbols
xkbcommon: ERROR: Failed to compile keymap
```

and this error if it does not exist:

```
xkbcommon: ERROR: Couldn't find file "symbols/custom" in include paths
xkbcommon: ERROR: 3 include paths searched:
xkbcommon: ERROR: 	./test/data/
xkbcommon: ERROR: 	/usr/share/X11/xkb
xkbcommon: ERROR: 	/home/ran/.xkb
xkbcommon: ERROR: Abandoning symbols file "(unnamed)"
xkbcommon: ERROR: Failed to compile xkb_symbols
xkbcommon: ERROR: Failed to compile keymap
```

This can perhaps be improved.

**Comment by whot** [comment]
Apologies for the long delay, other bits took higher priority, so I'm only back to looking at this now.

A few thoughts:
>  [...] they only show options listed in the evdev.xml file I believe.

I think we should be able to extend this so that the `xml` and `.lst` files are read from the same directories.

> Options make sense not only for symbols, but also the other components, keycodes, types, compat, geometry. Do you propose adding rules for those as well?

I hadn't given thought to those but a naïve "sure, why not" seems appropriate :wink: 

> even if you don't specify a model in the RMLVO, the * case still matches, i.e. it sets the default. I guess that for options this behavior can be changed.

I think this and the error messages you pointed out are the same UX issue. For options, the `*` character produce error messages adjusted to it's function as wildcard.

The more I think about it, the more I think that `foo:baz` should auto-translate to `foo(baz)` and the implementation should handle the issues behind it.

> Actually, in xkbcommon at least, repeating option like this is not allowed, so this is not possible.

Unless I understood, this doesn't matter here . this is just the `setxkbmap` cmdline interface and translates into the same components that xkbcommon uses and was just used as an example. What matters is how an options string like `foo:bar,baz:bat` is interpreted and that's the same.

> At least in xkbcommon, a rule is only matched once. So, if a user specifies options custom:foo,custom:bar,custom:baz, only foo would be matched.

Is that based on assumptions of the wildcard handling? I just tried the closest I can think of and it worked fine:
`./build/rmlvo-to-keymap --options "grp:shift_toggle,grp:win_switch"`
Am I missing something here?

> At least in xkbcommon, all option rules are attempted, even if already matched. So, if a user specifies options grp:shift_toggle,custom:foo, the grp:shift_toggle will match the wildcard too.

That I don't have any good answer for except for "don't match wildcards on already-matched rules".

**Comment by whot** [comment]
fwiw, I briefly looked into the alternative which is to load the `evdev` ruleset from the system dirs **and** the home directory and concat the two before processing. This would be the simplest addition as it would run underneath everything and doesn't require changing to the parsing code.

I'm not 100% what to think of that yet. 

It looks like it can be supported in xkbcommon starting in `xkb_components_from_rules`, mostly depends on how many details are lurking here.

But mutter for example uses `XkbRF_Load()` and that very specifically takes a single file name only.  Given that's the first example I looked at, there's bound to be plenty others that wouldn't like the new behaviour. Which suggests that we'd have to add new API to libxkbfile for this to make it more explicit in the callers and meanwhile anything where libxkbcommon and $other overlap, we get different keymaps. I'm not sure whether that's a price worth paying. maybe @garnacho has a comment there regarding mutter and how much effort this would be.

**Comment by bluetech** [comment]
BTW, regarding this:

> But that's limited in that only one can be selected at a time, you can't pick-and-match like you do with options.

That's not strictly true, you can do

```
$ ./build/rmlvo-to-kccgst -l 'us(intl)+custom(foo)+custom(bar),fr'
keycodes: evdev+aliases(qwerty)
types:    complete
compat:   complete
symbols:  pc+us(intl)+custom(foo)+custom(bar)+fr:2+inet(evdev)
```

This has a few weaknesses:

- Doesn't play nice with variants -- they just append `(thevariant)` to the end.

    This can be worked around as demonstrated above -- by including the variant in the layout itself, though it makes an assumption that these are the same.

- With current `evdev` rules, can only affect symbols (through layout) and keycodes (through model), so can't add/change types or compat.

    For the use case of overriding some symbols, compat isn't needed, and types 

- With current `evdev`, the `inet(evdev)` is always appended last, so the custom symbols can't override the `inet` symbols, because the last takes precedence.

    It should be possible to change the merge-modes so it doesn't take precedence. But those are not handled very rigorously, I'll need to check.

**Comment by fooishbar** [comment]
I don't have any strong objection to adding the wildcard parsing. Rules concatenation would work but also probably shouldn't really necessary.

Not really sure what to think about `%o` transforming `foo:bar` into `foo(bar)`, or whether they should be broken out to different keys, e.g. `* = +%k(%v)`, or `*:* = +%1(%2)`. The latter seems like it could be more futureproof.

**Comment by whot** [comment]
ftr, I think using the `include` from #108  is a better option than wildcards, so right now I don't think what's proposed here needs to go ahead.

**Comment by whot** [comment]
Closing this based on the above comment
